### ISSUE TITLE
[Linux] Editor does not start (main.js error)

### ISSUE THREAD

**Issue by rokups** [AtomicGameEngine/AtomicGameEngine#1004]
Tested on Archlinux using master branch from today. What i did was basically this:

    git clone https://github.com/AtomicGameEngine/AtomicGameEngine.git
    cd AtomicGameEngine
    ./Build_AtomicEditor.sh
    ./Artifacts/Build/Linux/Source/AtomicEditor/AtomicEditor

Window briefly flashes and i get error box saying "Error executing main.js". Clicking OK exits editor. Full log produced below:

    [Fri Sep  9 15:06:36 2016] INFO: Opened log file /home/rokups/.local/share/AtomicEditor/Logs/AtomicEditor.log
    [Fri Sep  9 15:06:36 2016] INFO: Created 5 worker threads
    [Fri Sep  9 15:06:36 2016] INFO: Added resource path /home/rokups/src/open/AtomicGameEngine/Resources/CoreData/
    [Fri Sep  9 15:06:36 2016] INFO: Added resource path /home/rokups/src/open/AtomicGameEngine/Resources/EditorData/
    [Fri Sep  9 15:06:36 2016] INFO: Set screen mode 1024x768 windowed resizable
    [Fri Sep  9 15:06:36 2016] INFO: Initialized input
    [Fri Sep  9 15:06:36 2016] DEBUG: Loading resource Textures/Ramp.png
    [Fri Sep  9 15:06:36 2016] DEBUG: Loading temporary resource Textures/Ramp.xml
    [Fri Sep  9 15:06:36 2016] DEBUG: Loading resource Textures/Spot.png
    [Fri Sep  9 15:06:36 2016] DEBUG: Loading temporary resource Textures/Spot.xml
    [Fri Sep  9 15:06:36 2016] DEBUG: Loading resource Techniques/NoTexture.xml
    [Fri Sep  9 15:06:36 2016] DEBUG: Loading resource RenderPaths/Forward.xml
    [Fri Sep  9 15:06:36 2016] INFO: Initialized renderer
    [Fri Sep  9 15:06:36 2016] INFO: Set audio mode 44100 Hz stereo interpolated
    [Fri Sep  9 15:06:36 2016] INFO: Initialized engine
    [Fri Sep  9 15:06:36 2016] DEBUG: Launching Broker /usr/bin/mono /home/rokups/src/open/AtomicGameEngine/Resources/ToolData/AtomicNET/Release/AtomicNETService/AtomicNETService.exe
    Cannot open assembly '/home/rokups/src/open/AtomicGameEngine/Resources/ToolData/AtomicNET/Release/AtomicNETService/AtomicNETService.exe': No such file or directory.
    [0909/150636:ERROR:browser_main_loop.cc(231)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
    [Fri Sep  9 15:06:36 2016] INFO: Initialized system user interface
    [Fri Sep  9 15:06:36 2016] DEBUG: Loading resource UI/DefaultStyle.xml
    [Fri Sep  9 15:06:36 2016] DEBUG: Loading resource Textures/UI.png
    [Fri Sep  9 15:06:36 2016] DEBUG: Loading temporary resource Textures/UI.xml
    [Fri Sep  9 15:06:36 2016] DEBUG: Loading resource Fonts/Anonymous Pro.ttf
    [Fri Sep  9 15:06:36 2016] DEBUG: Font face Anonymous Pro (11pt) has 624 glyphs
    [Fri Sep  9 15:06:36 2016] ERROR: (Unknown Filename) - Failed loading module: main.js - Line: -1
    ~/src/open/AtomicGameEngine % ./Artifacts/Build/Linux/Source/AtomicEditor/AtomicEditor
    [Fri Sep  9 15:06:49 2016] INFO: Opened log file /home/rokups/.local/share/AtomicEditor/Logs/AtomicEditor.log
    [Fri Sep  9 15:06:49 2016] INFO: Created 5 worker threads
    [Fri Sep  9 15:06:49 2016] INFO: Added resource path /home/rokups/src/open/AtomicGameEngine/Resources/CoreData/
    [Fri Sep  9 15:06:49 2016] INFO: Added resource path /home/rokups/src/open/AtomicGameEngine/Resources/EditorData/
    [Fri Sep  9 15:06:49 2016] INFO: Set screen mode 1024x768 windowed resizable
    [Fri Sep  9 15:06:49 2016] INFO: Initialized input
    [Fri Sep  9 15:06:49 2016] DEBUG: Loading resource Textures/Ramp.png
    [Fri Sep  9 15:06:49 2016] DEBUG: Loading temporary resource Textures/Ramp.xml
    [Fri Sep  9 15:06:49 2016] DEBUG: Loading resource Textures/Spot.png
    [Fri Sep  9 15:06:49 2016] DEBUG: Loading temporary resource Textures/Spot.xml
    [Fri Sep  9 15:06:49 2016] DEBUG: Loading resource Techniques/NoTexture.xml
    [Fri Sep  9 15:06:49 2016] DEBUG: Loading resource RenderPaths/Forward.xml
    [Fri Sep  9 15:06:49 2016] INFO: Initialized renderer
    [Fri Sep  9 15:06:49 2016] INFO: Set audio mode 44100 Hz stereo interpolated
    [Fri Sep  9 15:06:49 2016] INFO: Initialized engine
    [Fri Sep  9 15:06:49 2016] DEBUG: Launching Broker /usr/bin/mono /home/rokups/src/open/AtomicGameEngine/Resources/ToolData/AtomicNET/Release/AtomicNETService/AtomicNETService.exe
    Cannot open assembly '/home/rokups/src/open/AtomicGameEngine/Resources/ToolData/AtomicNET/Release/AtomicNETService/AtomicNETService.exe': No such file or directory.
    [0909/150649:ERROR:browser_main_loop.cc(231)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
    [Fri Sep  9 15:06:49 2016] INFO: Initialized system user interface
    [Fri Sep  9 15:06:49 2016] DEBUG: Loading resource UI/DefaultStyle.xml
    [Fri Sep  9 15:06:49 2016] DEBUG: Loading resource Textures/UI.png
    [Fri Sep  9 15:06:49 2016] DEBUG: Loading temporary resource Textures/UI.xml
    [Fri Sep  9 15:06:49 2016] DEBUG: Loading resource Fonts/Anonymous Pro.ttf
    [Fri Sep  9 15:06:49 2016] DEBUG: Font face Anonymous Pro (11pt) has 624 glyphs
    [Fri Sep  9 15:06:49 2016] ERROR: (Unknown Filename) - Failed loading module: main.js - Line: -1

Edit:
@CTrauma  - paging man in charge ;)

**Comment by JoshEngebretson** [comment]
You need to run from ```Artifacts/AtomicEditor``` which is where the engine and resources are built for a redistributable build.

**Comment by rokups** [comment]
Running `./Build_AtomicEditor.sh` does not produce any files in that folder though.

**Comment by JoshEngebretson** [comment]
Hm, that would likely mean the build is failing, do you have any log of the build mentioning an error?

**Comment by rokups** [comment]
This is strange because cmake in terminal seems to finish successfully. However i found this in `Artifacts/Build/Linux/Atomic.log`
[Atomic.txt](https://github.com/AtomicGameEngine/AtomicGameEngine/files/464204/Atomic.txt)

Could this be it?

**Comment by JoshEngebretson** [comment]
It looks like you are missing the PCL stuff for mono, on Debian* it is: 

```sudo apt-get install  referenceassemblies-pcl```

**Comment by rokups** [comment]
Getting corresponding package from aur fixed it, thanks.
