### ISSUE TITLE
C#: Components defined in the main project can no longer be obtained from a node

### ISSUE THREAD

**Issue by mattbenic** [AtomicGameEngine/AtomicGameEngine#1016]
CSComponent subclasses defined in the main AtomicProject assembly (ie in .cs files contained under Resources) cannot be obtained from a node with GetCSComponents. It appears as if these components are instantiated as instances of CSComponent class, instead of the subclass.

CSComponent subclasses defined in separate dlls are still instantiated correctly and can be obtained with GetCSComponent.

Quite likely related to this, the main AtomicProject assembly can no longer be selected as the assembly for a CSComponent in scene

**Comment by JoshEngebretson** [comment]
This is a bit confusing, can it be replicated with the New C# Project using the 3D template on master? https://github.com/AtomicGameEngine/AtomicGameEngine/tree/master/Data/AtomicEditor/ProjectTemplates/Project3D/CSharp

**Comment by JoshEngebretson** [comment]
It might be a good idea to fire up a Tests repo, where we can put minimal reproduction cases of issues on branches, and eventually unit tests.

**Comment by JoshEngebretson** [comment]
I don't have an issue selecting main assembly for components, however I have been able to replicate the GetCSComponents issue returning CSComponents, here's the case in the AtomicTests repo branch for this issue: https://github.com/AtomicGameEngine/AtomicTests/blob/JME-ISSUE-1016/Issue-1016/Resources/Scripts/AtomicMain.cs

![screen shot 2016-09-16 at 11 31 13 am](https://cloud.githubusercontent.com/assets/376203/18597123/54185f9c-7c01-11e6-9153-56c239d1cc69.png)

**Comment by JoshEngebretson** [comment]
I verified the that CSComponents as the proper managed type and updated CSComponent GetTypeName to reflect the managed type name and not return the native type name, which would have always been "CSProject"

This now works in the test case: https://github.com/AtomicGameEngine/AtomicTests/blob/JME-ISSUE-1016/Issue-1016/Resources/Scripts/AtomicMain.cs

Here's the relevant PR: https://github.com/AtomicGameEngine/AtomicGameEngine/pull/1017

**Comment by mattbenic** [comment]
Awesome, thanks :) The Tests repo is a great idea. I'll use that in future for relevant cases. Apologies for the lousy wording on the original issue.

**Comment by mattbenic** [comment]
Reopening this for now because I'm still running into it with latest code. I'll try and get you a test case. I'm still seeing the instance of the component defined in AtomicProject returned as a CSComponent rather than the specific class.

**Comment by mattbenic** [comment]
My bad, it is fixed. I neglected to update the dll reference in my scene after moving the component back to AtomicProject
