### ISSUE TITLE
read from uninitialized variable in Valgrind

### ISSUE THREAD

**Issue by EternalXY** [AtomicGameEngine/AtomicGameEngine#1032]
When running the engine through a Valgrind memory check on Linux, everything comes up clean except for 1 variable that is reported as read before being initialized: tooltipHoverTime_ in UI.cpp.
Looking at the code, it looks like the constructor doesn't initialize its value, although I don't think this will really cause problems as moving the mouse will reset it.

**Comment by JoshEngebretson** [comment]
Thanks, closed via #1151
