### ISSUE TITLE
Update dts-generator to TS 2.0

### ISSUE THREAD

**Issue by shaddockh** [AtomicGameEngine/AtomicGameEngine#1034]
As a follow-up to #1030, `dts-generator` emits a peer dependency warning.  Once `dts-generator` is updated to consume TS 2.x, then update it so that the warning goes away and the `npm shrinkwrap` can be applied. See https://github.com/SitePen/dts-generator

**Comment by shaddockh** [comment]
It appears that dts-generator has recently been updated to TS 2.x, so this can be scheduled in a milestone now.

**Comment by JoshEngebretson** [comment]
Cool, if you want to do it for Build 1 or Build 2, go ahead and assign yourself and set the issue milestone, if beyond that we can setup Build 3.
