### ISSUE TITLE
CSComponents reference a different assembly to that referenced by .csproj

### ISSUE THREAD

**Issue by mattbenic** [AtomicGameEngine/AtomicGameEngine#1055]
Methods like Node.GetCSComponent no longer work because the type comparison between the required type and the type of the actual component fails.
This appears to be because they are sourced from different dlls: 

![capture](https://cloud.githubusercontent.com/assets/278871/18943803/1ea3f652-8622-11e6-9016-cd09f3900457.PNG)

This can be reproduced with the test project at https://github.com/LumaDigital/AtomicTests/tree/MB_CSharpExternalDllTest/CSharpTests/ExternalDllTest

**Comment by mattbenic** [comment]
Commit e4ba18ff (CSComponent improvements..) and related in PR 1038 looked like a likely candidate, so reverted to febdfa27 and confirmed that these tests work there.

**Comment by JoshEngebretson** [comment]
Thanks for the test case, going to need to sort this today, we have the assemblies in resources which are used for a) inspection of components and b) to generate references in the generated solution.  The later is introducing another copy of the assembly which goes into the bin.  

.NET loads assemblies on demand when a type from the assembly is first used, this is a problem as we may first/only use them in a scene, so need a mechanism to ensure external dll's are pre-loaded.  The AppDelegate system ensures that the main project assembly is loaded as the AppDelegate subclass is instantiated and so we know the main assembly is loaded.

So, the app preloads both the project dll's and then the referenced copy is loaded from the bin folder, and we have a type mismatch... which is good as it at least exposes the problem.  The types are also compiled into the executable, so we have duplicate types for the executable and the (portable) project dll.

Commenting out the component load from the resources folder gets this test passing: https://github.com/AtomicGameEngine/AtomicGameEngine/blob/master/Source/AtomicNET/NETNative/Desktop/NETIPCPlayerApp.cpp#L79

This is a possible workaround, as long as you are ensuring component assemblies are being loaded before CSComponentCore.ParseComponents is being called at init.  You can do this by referencing one of their types with a typeof(TheTypeInAssembly) in the Program.cs or wherever the main entry point of the app is... the test project is loading the assemblies on the front-end already

I also noticed that atomic project references are being added to AtomicNET projects in dev builds, so need to fix that...

**Comment by mattbenic** [comment]
I'm working around by using an older commit for now, which is fine until you sort it, thanks :)

I was previously manually loading dlls only referenced from scene objects, but that's no longer necessary since the first scene we load has a CSComponent from that dll. Obviously having to do the load manually isn't ideal, but it isn't terrible either. We used cache.GetResource<NETAssembly>("assemblyname.dll"), but that could be wrapped in an AtomicNET.LoadLibrary().

Alternatively that load could be injected into the Program.cs when the project is generated?

**Comment by JoshEngebretson** [comment]
Ok, #1056 should address this, I was able to get the test passing by making sure the external dll was referenced (and thus loaded) in Program.cs

I filed #1058 to track an automated way of handling this (cross platform), please reopen if this is still an issue
