### ISSUE TITLE
Editor crashes when laptop wakes

### ISSUE THREAD

**Issue by Type1J** [AtomicGameEngine/AtomicGameEngine#1074]
On my laptop, the editor crashes when it wakes from a sleep.

It seems to be related to trying CEF and graphics objects.

I don't have much information, but it's pretty easy to reproduce.

**Comment by Type1J** [comment]
More info:

```
    void D3D9Blit(const IntRect& dstRect, unsigned char* src, unsigned srcStride, bool discard = false)
    {
#ifndef ATOMIC_D3D11

        RECT d3dRect;

        d3dRect.left = dstRect.left_;
        d3dRect.top = dstRect.top_;
        d3dRect.right = dstRect.right_;
        d3dRect.bottom = dstRect.bottom_;

        int level = 0;
        DWORD flags = discard ? D3DLOCK_DISCARD : 0;

        D3DLOCKED_RECT d3dLockedRect;
        IDirect3DTexture9* object = (IDirect3DTexture9*) webTexture2D_->GetTexture2D()->GetGPUObject();

        if (FAILED(object->LockRect(level, &d3dLockedRect, (flags & D3DLOCK_DISCARD) ? 0 : &d3dRect, flags)))
        {
            ATOMIC_LOGERROR("WebTexture2D - Could not lock texture");
            return;
        }
```
The result of GetGPUObject() that gets assigned to "object" is 0 (nullptr). It crashed on the if statement because the call to LockRect attempts to read "object" as a nullptr.

This happens when any text file is open in the editor on a laptop, you close the lid, then open it sometime later.

**Comment by Type1J** [comment]
The previous comment's code was from WebTexture2D.cpp

**Comment by JoshEngebretson** [comment]
The web texture blitting needs some attention, it should be abstracted... this should be a relatively easy crash to fix though
