### ISSUE TITLE
[AtomicTool] Cannot run net compile command on machine other than the one that built the tool

### ISSUE THREAD

**Issue by mattbenic** [AtomicGameEngine/AtomicGameEngine#1081]
AtomicTool is looking for the AtomicTool templates under the code root path generated in the project when running CMake. Should be able to specify an alternate AtomicNET or Resources path.

**Comment by JoshEngebretson** [comment]
I guess this means AtomicTool needs to leave the local farm and travel to Redistributable City!  🐷

**Comment by mattbenic** [comment]
For reference, here are the commands I'm currently using to buil, run from a batch in the game project. AtomicTool.exe is currently alongside a packaged AtomicEditor.exe (just a built \Artifacts\AtomicEditor copied to another dir) :

	rd /s /q Build
	rd /s /q AtomicNET
	..\..\AtomicEditor_ArtBuild\AtomicTool.exe "Path\To\Our\AtomicProject\AtomicProject.atomic" net compile "Path\To\Our\AtomicProject\AtomicProject.atomic" -platform WINDOWS -config Release
	..\..\AtomicEditor_ArtBuild\AtomicTool.exe build WINDOWS

**Comment by JoshEngebretson** [comment]
Ok great, that helps clarify what needs to happen

**Comment by JoshEngebretson** [comment]
Closed via #1135, for example```AtomicTool net compile C:\Dev\MyProject\MyProject.atomic -platform Desktop -config Release``` yields:
![atomicnetcompile](https://cloud.githubusercontent.com/assets/376203/20020953/09c0759a-a291-11e6-945f-889762d13db8.PNG)

I also tested running outside of artifacts, note that the build script now copies the binary alongside the AtomicEditor executable (so AtomicTool will also have access to resources)
