### ISSUE TITLE
DebugHud not exposed to C#

### ISSUE THREAD

**Issue by weinandvv** [AtomicGameEngine/AtomicGameEngine#1109]

**Comment by JoshEngebretson** [comment]
DebugHud runs under the SystemUI subsystem which is internal.  Can you describe what you are working on a bit more, it is possible to wrap the functionality without exposing the class itself

**Comment by weinandvv** [comment]
I'm currently trying to show the DebugHud with all the profiler information while running the player. Part of my code includes this line: DebugHud hud = AtomicNET.GetSubsystem<DebugHud>(); which I'm unable to use since the DebugHud isn't exposed yet. Not sure if @mattbenic could describe the issue better?

**Comment by mattbenic** [comment]
We're trying to toggle the DebugHUD within the player. We started exposing it through JSBind by adding a SystemUI module, but _think_ it chokes on the nested SystemUI namespace.

Would exposing methods on the player itself be acceptable?

**Comment by JoshEngebretson** [comment]
Try the new FeatureExamples sample by downloading the bin off the site and opening it, has a pretty nice DebugHud in player code, including toggle:

https://github.com/AtomicGameEngine/AtomicExamples/blob/master/FeatureExamples/CSharp/Resources/Scripts/Sample.cs#L212

**Comment by JoshEngebretson** [comment]
One other quick note, SystemUI is pretty much only around for the "legacy" DebugHud/Console implementations which use the original Urho UI, the plan is to update the DebugHud/Console (not expose SystemUI)

**Comment by JoshEngebretson** [comment]
I'll close this, if there needs to be access to some DebugHud functionality a new issue can be opened
