### ISSUE TITLE
Expose additional fixture data queries for Box2D collisions

### ISSUE THREAD

**Issue by JoshEngebretson** [AtomicGameEngine/AtomicGameEngine#111]
Right now, the PhysicsBeginContact2D event only contains node and body information for the contact, it does not contain additional b2Fixture data such as the shape involved, etc.  This should be something that can be queried, however the PhysicsBeginContact2D event data should be kept minimal to minimize overhead.

**Comment by Alan-FGR** [comment]
Is this relevant?
Merge with other issue for 2D physics API holes.

**Comment by Alan-FGR** [comment]
Check https://github.com/AtomicGameEngine/AtomicGameEngine/issues/1197
