### ISSUE TITLE
[C#] Improve messaging on Visual Studio/Xamarin Studio requirement

### ISSUE THREAD

**Issue by JoshEngebretson** [AtomicGameEngine/AtomicGameEngine#1118]
When creating/opening a project with C# selected, a dialog box is opened with VS/XS requirement if these aren't installed.  

In this case, we shouldn't close the create project window and it should be made clear that JS/TS are available without using C# or installing VS/XS

**Comment by JimMarlowe** [comment]
The messaging about the VS/XS requirement for linux is wrong. It guides the linux user to download Xamarin Studio, which does not support linux. I needs another dialog box or something to show the download instructions for getting mono+monodevelop installed. NETProjectSystem.cpp correctly identifies monodevelop as the IDE to use with linux, it needs to use this information.

**Comment by JoshEngebretson** [comment]
It probably needs to link to a page describing the instructions for getting mono+monodevelop installed as this is pretty involved due to PCL requirements and the various linux distros
