### ISSUE TITLE
[Linux]  AtomicEditor leaves running process AtomicNETService.exe

### ISSUE THREAD

**Issue by JimMarlowe** [AtomicGameEngine/AtomicGameEngine#1125]
When you start the AtomicEditor, a mono + AtomicNETService.exe is also started, this is expected. On linux, when you close the editor, the AtomicNETService.exe is not stopped, so they hang around. Subsequent AtomicEditors start another AtomicNETService.exe and so on. 
OSX and Windows do not appear to have this problem. Im hoping @CTrauma can test this on linux distros other than Mint, to see how big the problem really is. 
   In diagnosing the problem, I'm finding that AtomicNETService.exe process is never told to send the event to engine it is running, to exit. It has a case in it's command loop to do this. Perhaps the process that is suppose to send this dies quicker on linux than other platforms, or they are suppose to be stopped some other way.

**Comment by JimMarlowe** [comment]
How to test: bring up AtomicEditor, then close it, then  'ps -ef | grep mono' and see of there is a  "/usr/bin/mono /home/AtomicGameEngine/Artifacts/AtomicEditor/Resources/ToolData/AtomicNET/Release/AtomicNETService/AtomicNETService.exe --ipc-server=12 --ipc-client=13 --ipc-id=1"
found.

**Comment by CTrauma** [comment]
Going to test this on Ubuntu/Fedora/Arch and report back here

**Comment by CTrauma** [comment]
Results are in.. looks like a general problem across all major distros.

Ubuntu 16.04.1 LTS:

```ctrauma   30317   8819  2 10:56 pts/1    00:00:01 /usr/bin/mono /home/ctrauma/projects/AtomicGameEngine/Artifacts/AtomicEditor/Resources/ToolData/AtomicNET/Release/AtomicNETService/AtomicNETService.exe --ipc-server=18 --ipc-client=19 --ipc-id=1
```

Arch:

```
ctrauma   18437      1  2 14:38 pts/0    00:00:00 /usr/bin/mono /home/ctrauma/AtomicGameEngine/Artifacts/AtomicEditor/Resources/ToolData/AtomicNET/Release/AtomicNETService/AtomicNETService.exe --ipc-server
=19 --ipc-client=20 --ipc-id=1
```
Fedora release 24 (Twenty Four) core-4.1-amd64:core-4.1-noarch:

```
ctrauma   69098   1473  2 15:42 pts/0    00:00:00 /usr/bin/mono /home/ctrauma/projects/AtomicGameEngine/Artifacts/AtomicEditor/Resources/ToolData/AtomicNET/Release/AtomicNETService/AtomicNETService.exe --ipc-server=17 --ipc-client=18 --ipc-id=1

```

**Comment by JoshEngebretson** [comment]
I just verified that it isn't happening on Windows/OSX.  I didn't have time to trace though the OSX stuff which mostly uses the *nix stuff too, good eye @JimMarlowe

**Comment by JoshEngebretson** [comment]
BTW, the "exit" command I believe is a crumb from bootstrapping the code for the service.  The IPC system should gracefully handle a parent process exiting (thus exiting main loop of child), though it doesn't seem to be working on Linux atm.

If you hit play in the editor and launch a player process, and exit the editor while the player is running, does it stay up on Linux?  On OSX, it exits both... which lends credence to the "exit" command being a red herring 🐟

**Comment by JimMarlowe** [comment]
The player exits if the editor is closed. 
I have this memory that keeps wanting to tell me something about child process on linux, but the herrings keep getting in the way, otherwise you could monitor the parent pid and if it goes goes away, exit, but that's a little bass-akwards.

**Comment by JoshEngebretson** [comment]
That's good news, just to double check was this a C# project?  If not, that would be a good thing to try... if it exits too, this means that the AtomicNETService needs a little of whatever sauce is missing from the managed player subprocess.

**Comment by JimMarlowe** [comment]
No, this happens any time you bring up the editor, you don’t need to load a program.

**Comment by JoshEngebretson** [comment]
Sorry, I meant whether the managed player exited when running a C# project from the editor, then exiting the editor while the player is still running.  The AtomicNETService is launched at the editor start (if available) regardless if C# is in use or not...

**Comment by JimMarlowe** [comment]
A player running a c# project will also exit with the editor.
in http://stackoverflow.com/questions/284325/how-to-make-child-process-die-after-parent-exits 
I will see if I can implement answer 142, with #idfef LINUX around it, failing that, answer 51.

**Comment by JoshEngebretson** [comment]
I tested #1127 on Ubuntu and it should now cleanly exit child processes (ie. they will receive exit requests and can handle them accordingly).
