### ISSUE TITLE
Linux: Could not get application preferences directory 

### ISSUE THREAD

**Issue by christoffersch** [AtomicGameEngine/AtomicGameEngine#1138]
Successful install of Atomic on Kubuntu, but trying to run it results in this error:

`christoffer@christoffer-XPS-15-9550:~/Desktop/AtomicGameEngine/Artifacts/AtomicEditor$ ./AtomicEditor
[Sat Nov  5 17:31:30 2016] WARNING: Could not get application preferences directory
[Sat Nov  5 17:31:30 2016] WARNING: Could not get application preferences directory
[Sat Nov  5 17:31:30 2016] WARNING: Could not get application preferences directory
terminate called after throwing an instance of 'Poco::AssertionViolationException'
  what():  Assertion violation
Aborted (core dumped)
`

**Comment by christoffersch** [comment]
Well, for some reason, reinstalling Atomic made it work:

`INFO: Creating default Atomic Editor preferences: /root/.local/share/AtomicEditor/Preferences/prefs.json
`

**Comment by christoffersch** [comment]
Solution is to run ./AtomicEditor as super-user haha :)

**Comment by JimMarlowe** [comment]
There is no requirement to build or run Atomic as root on a linux system. Atomic can be built and run as a normal user and all generated preference files will be put in the users home directory. 
The errors that you are getting appear to be from mixing user and root privileges when trying to run the AtomicEditor.
The instructions for building on linux are here https://github.com/AtomicGameEngine/AtomicGameEngine/wiki/Building-the-Atomic-Editor-from-Source#linux and work well.

**Comment by JoshEngebretson** [comment]
Thanks for the report, if this can be replicated using the provided build instructions, can be reopened.
