### ISSUE TITLE
[Editor] F-key focus not working when using BoneBoundingBox

### ISSUE THREAD

**Issue by weinandvv** [AtomicGameEngine/AtomicGameEngine#1166]
Issue comments and explanation:
https://github.com/AtomicGameEngine/AtomicGameEngine/pull/1150#issuecomment-260668732

**Comment by JoshEngebretson** [comment]
Ok great, adding to Build 1 milestone https://github.com/AtomicGameEngine/AtomicGameEngine/milestone/2

**Comment by JoshEngebretson** [comment]
Closed via #1179
