### ISSUE TITLE
[Editor] Closing a scene that is not the currently focused one causes further scene changes to not appear in the scene Hierarchy view

### ISSUE THREAD

**Issue by mattbenic** [AtomicGameEngine/AtomicGameEngine#1167]
Yeah, that's a confusing description, I don't know how else to put it :) To repro:

-Open the Roboman3 JS example
-Create a new scene called Test2.scene, save it and close it
-Open Test.scene (the normal example scene)
-Open Test2.scene (the newly added one)
*Note that Test2.scene is now open in the scene view, with an extra tab above the scene view for Test.scene
-WITHOUT switching to Test1.scene, close it by clicking the X next to its name
-Drag a prefab into the scene view
*Note that while the object appears in the scene view, the Scene Hierarchy view does NOT include the new object

**Comment by JoshEngebretson** [comment]
Thanks for the detailed reproduction steps, adding to Build 1 with high priority
