### ISSUE TITLE
[Website] Cut a new Atomic demo reel video for landing page

### ISSUE THREAD

**Issue by LaraEngebretson** [AtomicGameEngine/AtomicGameEngine#1175]
Update the current landing page video (from March 2015!) with a new demo reel video featuring all the latest and greatest Atomic technology.

**Comment by JoshEngebretson** [comment]
I am going to put some thoughts here and will continue to edit this comment...

#### Video clips

Atomic demo/feature clips should be around **5 seconds** in length, depending on how easy it is to digest what is being shown.  Keep in mind that people will pretty much know what they are looking at, this is just in an Atomic context, so quick videos will do nicely.

We have a bunch of footage for features/demos already that can edit together, some notable exceptions in Atomic's Chromium WebView and PBR scene example

#### Script 

Thoughts, in no particular order, front loaded with fun stuff (don't go right into platform/language lists and things) 

- Platforms
- Languages and IDE integrations
- Scene editor
- 2D/3D rendering/physics features
- Low level graphics API (blaster)
- High performance C++ core

**Comment by Alan-FGR** [comment]
OK, I'm gonna improve this so we can extract a decent clip:
![](https://thumbs.gfycat.com/BreakableBruisedBubblefish-size_restricted.gif)
Assets are from here:
http://www.gameart2d.com/hill-climb-racing---free-car-sprites.html
http://www.gameart2d.com/free-platformer-game-tileset.html
And the ground texture is from Nobiax, however, it doesn't look very good, doesn't fit the style, maybe the grass texture also could contrast a bit more with the background...
TODO:
* Add the head of the character 😈 
* Add some bushes, mushrooms and some other objects in that tileset
* Add some particles, maybe dust and exhaust gas
* Add a few crates that react to the vehicle? Maybe destructible
* Add clouds on the background?
* Try to find a better texture for the ground

**Comment by JoshEngebretson** [comment]
@Alan-FGR Those would be great adds, let me know if you are running into any blockers adding them.  Thanks!

**Comment by Alan-FGR** [comment]
I pinged @JoshEngebretson on Gitter about this, but I'm adding the clips here just in case:
https://drive.google.com/open?id=0B6RP3uoh07LuTTN6SFNqRjhRY1U

**Comment by dragonCASTjosh** [comment]
ill try put in some of my rendering improvements although you will have to add the HDR and Gamma correction hacks in yourself

**Comment by Alan-FGR** [comment]
Maybe I should open new issue, but I really think we should compile a comprehensive feature list, and maybe gather some realistic performance data, to market it around... I'm using Atomic for some time and even for me it's still not clear what features it have on top of Urho for example.

**Comment by dragonCASTjosh** [comment]
i know @JoshEngebretson was talking about GDC, maybe he could do a feature trailer similar to [https://www.youtube.com/watch?v=l88n8a4Yphw](https://www.youtube.com/watch?v=l88n8a4Yphw)

**Comment by Alan-FGR** [comment]
@dragonCASTjosh Well, that video is quite good but it's too much visual oriented in my opinion. I'm sure that's what attract users, but it's not easy to do something like that, and especially on the editor side we don't have *that* much to show at the moment really... what's your opinion on doing a less visual oriented video showing more of the tech for example pathfinding, 2D and 3D physics, the new PBR, and maybe an overview of the editor? They don't have to be good looking to show the features, but of course we'd need something more 'presentable' than the Urho demos for example. I don't know if fancy graphics are the way to go at the moment, maybe they are, but I honestly don't see something too fancy happening soon unless we can count on some high-quality art assets I'm not aware of... the one of the reasons I'm doing the 2D racing game example is exactly to be used to promote Atomic. I honestly think that at this point there's no better way to do that, examples not only show the capabilities of the engine, but also help people get started, and can be used to make videos like that too.

**Comment by dragonCASTjosh** [comment]
@Alan-FGR i will likely have high quality assets from my team before GDC so there should be some good graphics stuff to show there. Also the video doesn't have to about graphics i was thinking more the format and aims of the video

**Comment by Alan-FGR** [comment]
@dragonCASTjosh Well, if we have the assets then by all means we should use them... Yes, the format is nice but imho it's nothing special, in terms of presentation these tech demo videos all look the same to me, just clips with description on screen, and I find the music annoying.
