### ISSUE TITLE
[Editor] Fix up default project template language selection

### ISSUE THREAD

**Issue by JoshEngebretson** [AtomicGameEngine/AtomicGameEngine#1190]
In a pinch, default to JavaScript as this will always work, right now we default to C# with an info box about downloading visual studio/xamarin studio if these are missing.  When the dialog box closes, the "new project" dialog also goes away which is poor for usability

**Comment by JimMarlowe** [comment]
further information from gitter : On #1190 it comes down to if we detect that we have C# tooling or not, if so, we should select C# as default, otherwise JS (this is debatable and could be an option someday)
We could also add it as a pref, whatever you chose last ... maybe we should just default to JS, add C# as an option, make the messaging better, and not close the new project window if can't detect C#?
I also intend to address #1118 at the same time for guiding linux users in the right direction.

**Comment by JimMarlowe** [comment]
My thought for the New Project Selection...

New Project dialog 
    Please Select project type [ 2D | 3D | Empty ]

(goes to)

Create Project dialog
    Project Name [MyGame]
    App ID [com.companyname.mygame]
    Platforms [ win/osx/lin | android | ios | webgl ]
    Project Directory [ <path>/AtomicProjects ]
    Project Language [CSharp | Javascript | Typescript ]      ** this is where you'd like the preference for (only) New Projects?

  Create | Cancel

    If the user has chosen to create a new C# project and they do not have the c# stuff installed, give a modal error message, telling them they can not create the project without C# support installed, and they can get installation instructions (The current platform c# install dialog ) (and cancel the create project dialog) or go back (to the create project dialog) and select a different language.
 
 For an existing example - the Language field will always show which language is appropriate for a given example, and it re-uses the Create Project dialog.
   If they have chosen an example that is only c# and they don't have the C# installed, give a modal  error message that tells them they can not create this example without the c# support installed. They can get the installation instructions or cancel the operation of creating the example. If it is a multi-language example, you could follow the new project behavior, but this is cleaner.

**Comment by JoshEngebretson** [comment]
The default preference being JavaScript would be good, so defaulting to JS until the user chooses a different language and successfully creates a project based on it.  Whatever language was used to create the last project becomes the preference and thus the default.

All new project templates (2D/3D/Empty) have JS/TS/C# templates, so always valid, minus if you don't have C# tooling available.  If you don't, then the C# info box should come up with download links for VS/XS/Link to wiki for Linux (I don't think an error modal in addition to this would be necessary).

If an example doesn't have the language they have set as a preference, would go JS/C# (if they have tooling)/TS in that order, and we can let the C# info box do the work in the case of examples which solely have C# (they wouldn't have any other options anyway, though good to see these examples exist, and there are language filters at the top)

Whew, hopefully this makes sense, and lemme know if anything seems wonky.  I think it is pretty close to what you are describing :)
