### ISSUE TITLE
[Website] Simplification and Updates

### ISSUE THREAD

**Issue by JoshEngebretson** [AtomicGameEngine/AtomicGameEngine#1192]
The website is crusty and needs a scouring, planning to collapse pages, tighten, and present the Atomic technology better.  Also, download page will become builds page, with messaging on what builds/milestones are...

**Comment by Alan-FGR** [comment]
I don't know if I agree with the renaming of 'download(s)' because I suspect 'builds' is less recognizable as the place where you'd get it, especially for newbies and non-tech-savvy people. Anyway, just something to consider (or not).

**Comment by Alan-FGR** [comment]
Another reminder... if Build 1 is going to have AtomicNET officially, don't forget to link the API docs on the website too :)
