### ISSUE TITLE
[C#] Add tooltip support for script exposed variables

### ISSUE THREAD

**Issue by mattbenic** [AtomicGameEngine/AtomicGameEngine#1194]
- [ ] Add hover tooltip support to inspectors
- [ ] Add a description or tooltip parameter to the [Inspector] attribute
- [ ] Expose that value to the CSComponent inspector

**Comment by JoshEngebretson** [comment]
This is brilliant, adding to Atomic Build 2, I also filed #1195 which will introduce localized tooltips for core engine inspector fields
