### ISSUE TITLE
[Suggestion] Scene Editor like Godot

### ISSUE THREAD

**Issue by GodotIsAMess** [AtomicGameEngine/AtomicGameEngine#1202]
Hey folks,

While looking over Atomic's source and using the engine for a bit and also how they manage scenes, it's actually pretty similar to Godot's scene system. Except I really like Atomic's better just because the ability to use Ducktape, C#, etc. Since I come from JS :)

My biggest gripe is the UI development is really lacking. Now, I apologize if this sounds condescending, but honestly that's why I went back to Godot as it's so easy to create rich UI's and prototype / mockup stuff.

I think Atomic would sweep the floor though if a Scene Editor type of system was implemented. I  also have been around Godot for about year and have seen other people say the same thing trying Atomic.  Anyways, just my two cents.. Thanks for reading!

**Comment by JoshEngebretson** [comment]
Hello, the Scene Editor does need work in general and there are a number of usability issues filed to improve it.  Thanks for the feedback.
