### ISSUE TITLE
[macOS] Startup error when running binary app bundle: Failed to add resource path 'CoreData'

### ISSUE THREAD

**Issue by smelukov** [AtomicGameEngine/AtomicGameEngine#1209]
- Download
- Execute
- Got error: `Failed to add resource path 'CoreData', check the documentation on how to set the 'resource prefix path'`

Can't find `how to set the 'resource prefix path'`

MacOS 10.12.1

**Comment by JoshEngebretson** [comment]
Does your app path have a space in it?  This issue had been sporadically seen and thought solved

**Comment by smelukov** [comment]
>Does your app path have a space in it?

No - `/Applications/AtomicEditor.app`

**Comment by JoshEngebretson** [comment]
Thanks for the report, If you run it from your Downloads folder instead of /Applications does the issue persist?

**Comment by smelukov** [comment]
@JoshEngebretson yep

**Comment by JoshEngebretson** [comment]
Just to make sure, this is the version downloaded?

http://docs.atomicgameengine.com/downloads/AtomicEditor_MacOSX_a0505c2173c28314ab7039aba214924e49b6f742.zip

If you wouldn't mind rebooting and seeing if the issue magically goes away, that would be good to know.  The last time this popped up, quoting paths in the binary "fixed it".   Starting to think it maybe something with current directory and resolving the packaged resource folder.

**Comment by smelukov** [comment]
@JoshEngebretson 
> Just to make sure, this is the version downloaded?

yep

> If you wouldn't mind rebooting and seeing if the issue magically goes away, that would be good to know.

The issue is still remaining... even after reboot

**Comment by JoshEngebretson** [comment]
How about opening a terminal and running ./AtomicEditor from inside the app bundle?

**Comment by smelukov** [comment]
@JoshEngebretson It works!

**Comment by smelukov** [comment]
Thanks! But what's wrong with it?

**Comment by JoshEngebretson** [comment]
That is a very good question :)  I haven't seen this personally, though have in the office and when haven't since last fixed.  I have a feeling it is the current folder, need to look into it.  I will assign to Build and look into it soon.

**Comment by JoshEngebretson** [comment]
@smelukov Hello, if you have time, could you please try the latest build and see if you are still experiencing the issue?  Thanks! [Atomic Build 2 - Git Hash: 74ce6f6d521bfda17e7e91a0f3eba7f5a59074c1](http://docs.atomicgameengine.com/downloads/AtomicEditor_MacOSX_Build1_74ce6f6d521bfda17e7e91a0f3eba7f5a59074c1.zip)

**Comment by smelukov** [comment]
@JoshEngebretson Hello! Yes, it works! Thank you ;)
