### ISSUE TITLE
[Wiki] Add development build information for setting up IDE, debugging, etc

### ISSUE THREAD

**Issue by JoshEngebretson** [AtomicGameEngine/AtomicGameEngine#1211]
Much of this info already exists and needs to be brought over to Wiki, updated as necessary

https://qa.atomicgameengine.com/28/how-to-build-from-source-in-debug?show=28#q28

**Comment by christoffersch** [comment]
Wiki page created: https://github.com/AtomicGameEngine/AtomicGameEngine/wiki/How-to-set-up-a-Debug-Development-Build
