### ISSUE TITLE
[Wiki] Add information about setting up Atom/VSCode for writing Atomic Editor TS scripts

### ISSUE THREAD

**Issue by JoshEngebretson** [AtomicGameEngine/AtomicGameEngine#1212]
This is related to #1211 as you first will want a development environment

**Comment by shaddockh** [comment]
There is a Q&A topic on this that can help populate the wiki:  https://qa.atomicgameengine.com/159/how-can-you-edit-typescript-projects-outside-atomic-editor

**Comment by JoshEngebretson** [comment]
That's right! Excellent :)

@christoffersch Do you mind if I assign the port to you?

**Comment by christoffersch** [comment]
@JoshEngebretson you may :)

**Comment by christoffersch** [comment]
Wiki page created: https://github.com/AtomicGameEngine/AtomicGameEngine/wiki/Using-TypeScript-with-External-Editors

**Comment by JoshEngebretson** [comment]
Fantastic, thanks!!!

**Comment by JoshEngebretson** [comment]
Do you have a plan for linking the page in?  We might need to start some high level breakdown as more pages are added, not sure, looking really good!

**Comment by christoffersch** [comment]
I'm thinking that, just as with the "[Getting Started with Atomic](https://github.com/AtomicGameEngine/AtomicGameEngine/wiki/Getting-Started)", I might make one called "Complete List of Pages" or something like that (that doesn't have the pages in getting started, however). What do you think of that?

**Comment by JoshEngebretson** [comment]
I think: 👍 

Thanks
