### ISSUE TITLE
Missing textures in cs example

### ISSUE THREAD

**Issue by CTrauma** [AtomicGameEngine/AtomicGameEngine#1224]
Creating and running  project based on Basic3D and choosing **js** for scripting shows a spinning treasure chest with proper textures . Log output shows the following:  

[Wed Nov 30 22:58:40 2016] INFO: Loading scene from Scenes/Scene.scene
[Wed Nov 30 22:58:40 2016] DEBUG: Loading resource b00f01294b1cc469d4db9f862c9296b7.mdl
[Wed Nov 30 22:58:40 2016] DEBUG: Loading resource Models/Materials/DefaultMaterial.material
[Wed Nov 30 22:58:40 2016] DEBUG: Loading resource Techniques/Diff.xml
[Wed Nov 30 22:58:40 2016] DEBUG: Loading resource Textures/chest.png
[Wed Nov 30 22:58:40 2016] DEBUG: Loading resource Components/Spinner.js

Creating and running  project based on Basic3D and choosing **cs** for scripting shows a spinning treasure chest with proper missing textures . Log output shows the following:  

[Wed Nov 30 22:54:03 2016] INFO: Loading scene from Scenes/Scene.scene
[Wed Nov 30 22:54:03 2016] DEBUG: Loading resource 2788364e8ff6f81f4b566a9d58e3fb5b.mdl
[Wed Nov 30 22:54:03 2016] DEBUG: Loading resource Models/Materials/DefaultMaterial.material
[Wed Nov 30 22:54:03 2016] DEBUG: Loading resource Techniques/Diff.xml
[Wed Nov 30 22:54:03 2016] ERROR: Could not find resource Textures/Chest.png

Looks like a problem with case, the cs project is looking for Chest.png and not chest.png.

Looking into it further, will try to provide a PR asap

**Comment by CTrauma** [comment]
Looks like the case of the filename in DefaultMaterial.material is incorrect

```
<?xml version="1.0"?>
<material>
	<technique name="Techniques/Diff.xml" quality="0" loddistance="0" />
	<texture unit="diffuse" name="Textures/Chest.png" />
	<parameter name="UOffset" value="1 0 0 0" />
	<parameter name="VOffset" value="0 1 0 0" />
	<parameter name="MatDiffColor" value="0.8 0.8 0.8 1" />
	<parameter name="MatEmissiveColor" value="0 0 0 1" />
	<parameter name="MatEnvMapColor" value="1 1 1" />
	<parameter name="MatSpecColor" value="0.5 0.5 0.5 16" />
	<cull value="ccw" />
	<shadowcull value="ccw" />
	<fill value="solid" />
	<depthbias constant="0" slopescaled="0" />
</material>
```

fixing

**Comment by CTrauma** [comment]
Fix case of png file in material #96  PR in Examples repo

**Comment by benwolf** [comment]
Just found this on my copy, nice work CTrauma :camel:

**Comment by JoshEngebretson** [comment]
Awesome! Thanks @CTrauma 

I filed #1226 to investigate asset case sensitivity as can introduce hard to track down load issues
