### ISSUE TITLE
[Wiki] Broken platform images on build page

### ISSUE THREAD

**Issue by JoshEngebretson** [AtomicGameEngine/AtomicGameEngine#1234]
@christoffersch  Great job converting all the image links to use local versions of the image files 👍  

It looks like the platform pngs have issues on the editor build page, they won't display in windows either when cloned from the repo

https://github.com/AtomicGameEngine/AtomicGameEngine/wiki/Building-Atomic---The-Quick-and-Easy-Way

Can we switch up to use the same logos as on the downloads here? http://atomicgameengine.com/#download-the-atomic-editor  

Can use the same sizing as currently on the wiki page, though definitely want the Windows 10 logo instead :)  Thanks!

**Comment by christoffersch** [comment]
I'm on it! :) Yes, we'll use the same icons.

**Comment by christoffersch** [comment]
Should be good now :+1:
