### ISSUE TITLE
[Example] Virtual DPad JS script is throwing exception

### ISSUE THREAD

**Issue by JoshEngebretson** [AtomicGameEngine/AtomicGameEngine#1249]
An exception is being thrown in roboman, could be also happening in physics platformer and others with dpad.  Attempting to call an undefined function, callstack here: https://github.com/AtomicGameEngine/AtomicGameEngine/issues/1205#issuecomment-265221164

**Comment by JimMarlowe** [comment]
BindButton (+other stuff) is missing from input.cpp.h, it was overwritten in a core update, and it had no // ATOMIC BEGIN, // ATOMIC END guards.
