### ISSUE TITLE
[Wiki] Tutorial on C# basics

### ISSUE THREAD

**Issue by christoffersch** [AtomicGameEngine/AtomicGameEngine#1252]
It'd be great to have a tutorial for newbeginners getting into Atomic and C#. I think it would be good to have an overview of the default Atomic scripts and a little overview on how to create custom components.

Suggestions welcome :)

**Comment by christoffersch** [comment]
Wiki page created: https://github.com/AtomicGameEngine/AtomicGameEngine/wiki/Basic-Scripting-in-CSharp

**Comment by Alan-FGR** [comment]
Nice work @christoffersch... as the documentation progresses though, I think it would be beneficial to keep the same docs for all languages and just provide a way to 'switch' the language so we don't have to maintain them separately (we'll probably have lots of redundant stuff)... something like the Unity docs for example. I don't know how that could be done with the github wiki, maybe some inline css could do but that's not gonna be ideal to maintain.
