### ISSUE TITLE
[Desktop] - EngineConfig issues with deployed applications 

### ISSUE THREAD

**Issue by JoshEngebretson** [AtomicGameEngine/AtomicGameEngine#1276]
EngineConfig is not being read or applied properly in deployed apps.  Window title is a good test to see if this is working, more info below.

This may only be affecting deployed native apps though deployed managed application should be tested as well, ensuring Engine.json is being properly deployed and loaded from the right location in deployed apps.

Related Q&A:
https://qa.atomicgameengine.com/248/settings-not-working-for-window-size-maximized

from Gitter
```
I've got (obviously) a question, I build, using the build command from the editor (not the one for managed project. (simple default 3D project with just the chest asset, nothing fancy)
Then try to add an Engine.json (under Settings/Engine.json ) I've saw a few comments about it in the Q&A section.
But it's like it never picks up anything from that file.
I first thought it was using the player but even after modifying EngineConfig::ApplyConfig(engineParameters_); call in AtomicPlayerApp::ReadEngineConfig()
to force override any previous value by what's in the Engine.json I'm still unable to have anything from that file picked up (ofc I did rebuild Atomic and the project after doing so)
Same goes with directly modifying the default value of static void ApplyConfig(VariantMap& settings, bool overwrite = false) to true..
```

**Comment by JimMarlowe** [comment]
The linked Q&A question is related, the sizing of the player is being controlled by Editor preferences (because it is an editor) instead of Setting/Engine.json. Once we can self-identify the executable type, we can switch the player to do the right thing.
