### ISSUE TITLE
[TypeScript] import statements w/o path specified don't resolve

### ISSUE THREAD

**Issue by shaddockh** [AtomicGameEngine/AtomicGameEngine#1277]
if you import another module from a component and don't provide a path, it should base the path on the root of the Resources directory, ie:
```typescript
import * as myModule from "Scripts/mymodule";
```

should find that file at ```<game project>/Resources/mymodule.ts```
However, the TypeScript compiler complains that the file cannot be found.

If you do the same in vanilla js, it works
```javascript
var mymodule = require("Scripts/mymodule");
```

The routines that setup and invoke the TypeScript compiler need to be able to handle this situation.  The workaround is to specify relative paths, such as:
```typescript
import * as myModule from "./mymodule";
//or
import * as myModule from "../Modules/mymodule";
```

**Comment by JoshEngebretson** [comment]
Closed via #1293
