### ISSUE TITLE
makeWebRequest no longer functions

### ISSUE THREAD

**Issue by JimMarlowe** [AtomicGameEngine/AtomicGameEngine#1283]
This code, which had previously worked, no longer returns when called, and no errors are generated,  making for a less than rewarding web experience.

    // Non-blocking http request runs asynchronously.
    var request = web.makeWebRequest("GET", wsite );

The WebRequest examples also fail in the same way.

**Comment by JoshEngebretson** [comment]
Currently on day 2.5 of no power, the web events were updated and I also updated examples.  May have missed one?

**Comment by JimMarlowe** [comment]
No, you didn't miss any, I had old examples in my AtomicProjects dir and my program was also based on the old APIs.  Ive updated my program and it functions again, though its gonna be problematic since I have an older Atomic installed in the OS, and then I often run the src compiled version too, and there is no way to detect which version of Atomic API the program is running against.
