### ISSUE TITLE
Problem building on Ubuntu 16.04

### ISSUE THREAD

**Issue by jw3126** [AtomicGameEngine/AtomicGameEngine#1289]
I followed the [build instructions](https://github.com/AtomicGameEngine/AtomicGameEngine/wiki/Detailed-instructions-for-building-on-Linux) using Ubuntu 16.04, but when executing the build script `sh Build_AtomicEditor.sh` I get the following error 
```

Building Atomic Editor, this process will take a few minutes

rm -rf /home/jan/Documents/AtomicGameEngine/Artifacts/AtomicEditor/
rm -rf /home/jan/Documents/AtomicGameEngine/Artifacts/AtomicNET/
rm -rf /home/jan/Documents/AtomicGameEngine/Artifacts/Build/Linux/
rm -rf /home/jan/Documents/AtomicGameEngine/Artifacts/Build/Source/Generated/
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'gtk+-3.0'
--   No package 'gtk+-3.0' found
CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:367 (message):
  A required package was not found
```

**Comment by CTrauma** [comment]
Have a look here
https://qa.atomicgameengine.com/90/how-to-build-install-on-linux?show=90#q90

you will need to install the system build dependencies

sudo apt-get install build-essential cmake nodejs libgtk-3-dev libasound2-dev libxrandr-dev libgl1-mesa-dev libglu1-mesa-dev

**Comment by jw3126** [comment]
That solved the problem for me, thanks! It might be useful to add this information to the wiki? (I don't know how to do that, is there a way to edit the wiki on github?)

**Comment by JoshEngebretson** [comment]
Have a look here:

https://github.com/AtomicGameEngine/AtomicGameEngine/wiki/Building-Atomic---The-Quick-and-Easy-Way#linux
