### ISSUE TITLE
Remove UI psd assets

### ISSUE THREAD

**Issue by JimMarlowe** [AtomicGameEngine/AtomicGameEngine#1292]
There are some psd files among the turbobadger default skin UI images, probably intended to manufacture different widget stylings. They are taking up 9+meg of deploy space.

**Comment by Type1J** [comment]
Can this be done through a .gitignore-like file?  I'm sure that TypeScript files don't need to be deployed either. Could files like .ts, .blender, .xsd, and .psd files (files that are usually converted or compiled into engine consumable files) be not deployed by a ignore.json file, which is also not deployed, but specifies which file to not deploy?

**Comment by JimMarlowe** [comment]
The intent of these files is the question, the user does not have a lot of visibility as to the inclusion or lack of need for these files in their deployable. Some of the psd files are development prototyping, which are not needed at all, the rest of the psd files are (possibly) intended as templates to make new skins sets. We have used a different methodology to make new skins, and do not require these files. If anyone would need them, they are still in the Turbobadger repo.
Having finer control over what gets deployed in a application is a different issue, but a worthy one.
