### ISSUE TITLE
[TypeScript] Add a new native wrapper for ScriptEvents

### ISSUE THREAD

**Issue by shaddockh** [AtomicGameEngine/AtomicGameEngine#1302]
All of the native events now have auto-generated wrappers.  Now there needs to be a wrapper to generate custom ScriptEvents.  The wrapper should adhere to the following signature:

```typescript
function ScriptEvent<T extends Atomic.EventMetaData>(eventType: string, callback: Atomic.EventCallback<T>): Atomic.EventMetaData {
    return {
        _callback: callback,
        _eventType: eventType
    };
}
```

Then an example of how to use it needs to be created in the Atomic Examples.

Usage would be:

```typescript
// inside a common module
interface MyscriptEvent extends Atomic.ScriptEvent {
    x: number;
    y: number;
}

function MyscriptEvent(callback: Atomic.EventCallback<MyscriptEvent>): Atomic.EventMetaData {
  return Atomic.ScriptEvent<MyscriptEvent>("MyScriptEvent", callback);
}

// inside various components
window.subscribeToEvent(MyscriptEvent(e => {
    //do stuff
}));
```

**Comment by shaddockh** [comment]
@JoshEngebretson when you get a chance can you look over TSH-ATOMIC-1302?  I think I'm missing something as my callback is not passing through for some reason.  Is there some trick to copy a JS function pointer to another object in duktape?

Test code is:

```
var ev = Atomic.ScriptEvent("foo", function() { console.log('inside callback'); });
console.log('event type: ' + ev._eventType);
console.log('before callback');
ev._callback(); // this executes, but doesn't call console.log like it should
console.log('after callback');
```

**Comment by JoshEngebretson** [comment]
Sorry, just saw this, noted to look soon :)

**Comment by JoshEngebretson** [comment]
I still owe some looking, did file a C# issue for scripted events and think TS/C# designs should be as we can muster: #1381

I am hoping we might be able to reduce the clutter of, somehow, does this need to be SO strictly typed, sorry if this seems like an out there question, I blame context switching :)

```TypeScript
function MyscriptEvent(callback: Atomic.EventCallback<MyscriptEvent>): Atomic.EventMetaData {
  return Atomic.ScriptEvent<MyscriptEvent>("MyScriptEvent", callback);
}
```

**Comment by shaddockh** [comment]
I think it can be a little bit more cleaned up and allow the TS inference to determine the types:
```typescript
function MyscriptEvent(callback: Atomic.EventCallback<MyscriptEvent>) {
  return Atomic.ScriptEvent("MyScriptEvent", callback);
}
```

But you are going to want to have the ```<MyscriptEvent>``` remain so that you get typechecking and intellisense on the callback when you use it later.  If you want a more generic one, you could always do something like the following for no parameter passing 

```typescript
function MyscriptEvent(callback: Atomic.EventCallback<null>) {
  return Atomic.ScriptEvent("MyScriptEvent", callback);
}
```
or
```typescript
function MyscriptEvent(callback: Atomic.EventCallback<any>) {
  return Atomic.ScriptEvent("MyScriptEvent", callback);
}
```
for no type checking.

**Comment by shaddockh** [comment]
@JoshEngebretson I'm still struggling with this.  The function looks like it is being attached to the metadata object and can be called, but it appears that it doesn't contain any logic.  I'm comparing how native events work, but it doesn't seem to work right.

My test case is
```javascript
var scene = Atomic.player.loadScene("Scenes/Scene.scene");

var evn = Atomic.WindowClosedEvent(function() { console.log("inside wce");});
console.log(evn._eventType);
evn._callback(); // logs "inside wce"

var ev = Atomic.ScriptEvent("foo", function() { console.log('inside callback'); });
console.log('event type: ' + ev._eventType);
console.log('calling callback');
ev._callback(); // should log "inside callback" but doesn't do anything (doesn't throw an error though)
console.log('after calling callback');
```

**Comment by JoshEngebretson** [comment]
Sorry, this fell down a rabbit hole 🐰 

Ok, is that paste something I can run against some version of Atomic, somewhere?  master?

😄

**Comment by shaddockh** [comment]
Yeah, this is is in the branch: TSH-ATOMIC-1302.  I just used the 2D starter template and pasted the above code into main.js

**Comment by JoshEngebretson** [comment]
Ok, I PR'd #1420 against branch which should fix things up, made some comments in the PR for any lurking watchers 👀  😄
