### ISSUE TITLE
[Editor] Unable to save a new directory as the default location for new projects.

### ISSUE THREAD

**Issue by AxDSan** [AtomicGameEngine/AtomicGameEngine#1324]
Hello Everyone, 

Well, every time I try to do a new project, and I change the default directory and then do a new project, it doesn't saves the previous location I have used, there is no "Settings" or "Preferences" menu in the editor, although there is a "Clear Preferences" option in the "Developers" menu.

Any help is deeply appreciated, and if there is an actual option to do what I'm looking for, Excuse me for my "newbieness" I'm just relatively new to this Atomic Game Engine thing!

Reference: https://github.com/AtomicGameEngine/AtomicGameEngine/blob/9ff7136b36f1acd25479400404b947d6446b208b/Script/AtomicEditor/ui/modal/CreateProject.ts#L61-L71 (Many thanks to github.com/rosshadden)

**Comment by shaddockh** [comment]
Probably the best way to handle this would be to remember the last directory used for a new project and store that into the ```prefs.js``` file.  Another option would be to have some kind of configurable directory in the prefs, but I think probably remembering the last save location would handle most cases.

**Comment by rosshadden** [comment]
You can assign to me if it lets you.  I'm working on adding an entry to the preferences file for this.

@shaddockh I agree that would be useful, and what I'm adding to make it supported in preferences should make your request easier to implement.  So I can do that as a follow-up.
