### ISSUE TITLE
[TypeScript] Instantiate component to retrieve Inspector Settings

### ISSUE THREAD

**Issue by shaddockh** [AtomicGameEngine/AtomicGameEngine#1332]
Currently the editor inspector retrieves the inspector settings from a component by doing a simple parse of the source code, looking for the inspector settings block.  Ideally, this should be replaced with having the inspector actually instantiate the object and then use the ```object.inspectorSettings``` value.

This would be more robust in that the field will always be available no matter how it's constructed (or transpiled to). 

There are a couple of gotchas to this method though
1) Components would need to be instantiated when inspected (but this may already be happening anyway)
2) the vanilla js way of defining inspector fields would need to change to expose the inspector fields somehow (since the js way doesn't define components as classes like ES6 and TS)

**Comment by JoshEngebretson** [comment]
I would really like to avoid instantiating user runtime script components inside the editor (they can call arbitrary API which may not be available in the editor or may depend on player runtime or other user subsystems being available ).  

The C# side inspects IL assembly for inspector fields, as not an option to instantiate managed components (and if we could, still same issues with component instantiation in editor).  Maybe we can get a TypeScript AST out of the soon to be available node binary included with the editor, or alternatively from the WebView?

I guess how fragile the inspector field source parsing is comes into play on this issue... and how many versions of transpiled output we want to support... which I think this is the only dependency on specific tsc compiler output, right?

**Comment by shaddockh** [comment]
The parsing of the js works for 99% of cases so it's not that big of a deal, just something to be aware of in case the transpiled output changes again.  Since there is no current way to sandbox these components inside the editor, I'll go ahead and close this.

**Comment by rosshadden** [comment]
Parsing an AST is a very good idea.  Otherwise, if we put inspector fields on the class-level, we wouldn't need to instantiate the classes to see them.

If we did support reading these fields from the code, it would allow us to use corresponding inspector widgets for the variable types, without requiring a default value.  Or maybe I just misunderstand what's currently happening.

**Comment by rosshadden** [comment]
I think this should be revisited once/if we distribute a node binary, like we keep talking about.

**Comment by JoshEngebretson** [comment]
✅  on including the node binary, I am filing the issue for the move of node/node_modules to the third party dependencies submodule later today.  From there, it can be factored into editor distributables.

**Comment by shaddockh** [comment]
Right now, the code is being parsed in a really basic way on the c++ side to extract those inspector fields.  It might be a good idea to bring in a proper JS parser so that we actually pull out the inspector fields from the AST w/o dealing with comment blocks, white space issues, etc.  It's working the way we're currently doing it, which appears to be fine for now.
