### ISSUE TITLE
[Wiki] Instructions for contributing to the wiki

### ISSUE THREAD

**Issue by christoffersch** [AtomicGameEngine/AtomicGameEngine#1336]
We need an article describing how to contribute to the wiki, if anyone should feel like it.

It definitely needs to contain:
- adding links
- adding images
- basic markdown formatting
- (header instructions?)

**Comment by JoshEngebretson** [comment]
Awesome, thanks! 🐫 

Go ahead and add Wiki articles to builds, they are definitely features and good to coordinate/see what is going.  If you don't get to an issue on a given build, don't feel bad... can assign to the next one :)

I'll add this to Atomic Build 3

**Comment by JoshEngebretson** [comment]
BTW, great job porting and improving the [How to set up a Debug Build](https://github.com/AtomicGameEngine/AtomicGameEngine/wiki/How-to-set-up-a-Debug-Development-Build) from the Q/A answer! Thanks! 

I'll be picking up the torch and working on it a bit more too :) 

A  key feature of markdown is that it doesn't have as much noise as HTML, if it seems like something is too verbose (or we're adding much HTML other than img tags, which are useful as markdown image handling is weak), probably a better way to discover and adopt :)

The Wiki best practices article can be pretty short and should really focus on the basics, with a link to the best GitHub markdown reference we can fine.  We don't want to rewrite markdown docs, do we? :)

**Comment by christoffersch** [comment]
Article done!
https://github.com/AtomicGameEngine/AtomicGameEngine/wiki/Contributing-to-the-Wiki

Feedback much welcome.
