### ISSUE TITLE
[Graphics] Prevent bone nodes from serializing

### ISSUE THREAD

**Issue by JohnnyWahib** [AtomicGameEngine/AtomicGameEngine#1348]
Need to add an "atomic-temporary" flag to bone nodes that get generated in the scenes so that they don't get saved.

**Comment by JoshEngebretson** [comment]
There is discussion here with more information, specifically on why temporary is problematic in this case: https://discourse.atomicgameengine.com/t/temporary-scene-bone-nodes/77

**Comment by JoshEngebretson** [comment]
Closed via #1359 (picked back up in #780)
