### ISSUE TITLE
Incorrect FBX import

### ISSUE THREAD

**Issue by nem0** [AtomicGameEngine/AtomicGameEngine#1429]
FBX file: [default_pose_char+wep.zip](https://github.com/AtomicGameEngine/AtomicGameEngine/files/740427/default_pose_char.wep.zip)

Atomic (see "flying" scope): 
![atomic](https://cloud.githubusercontent.com/assets/153526/22442607/4a6dc1f2-e73c-11e6-819e-02a9ee069b96.png)

Blender: 
![blender](https://cloud.githubusercontent.com/assets/153526/22442722/95bd051e-e73c-11e6-95f7-0902279b82c8.png)

**Comment by Alan-FGR** [comment]
Is the whole model skinned? In Atomic I only get a single AnimatedModel and a bunch of 'bones'...
Is the coordinates of the object "Wep_Sako85_Scope" the same as the ones in Blender (94.47, 193.59, 0)?
This model glitches Atomic considerably... the bounding box is totally off so culling doesn't work (if the bb goes outta screen model won't show even though it clearly should be visible). This is definitely something to check. First thing to determine is what exactly wrong, it could be the bones positions, the vertices, the weights, etc.. It could be a problem in the importer or the exporter. Have you tried reimporting the FBX in Blender? This is definitely a opportunity to fix bugs 😺.
![bbcull](https://cloud.githubusercontent.com/assets/8399299/22447802/6ff47064-e733-11e6-9b74-6a96dd8a68c2.png)

**Comment by nem0** [comment]
It's created in 3ds Max. The pose on the image is not the bind pose, but the first frame of animation (however no animation is played, it's just the way it is imported in Atomic). The bounding box seems to be created from the real bind pose:
![blender_bind](https://cloud.githubusercontent.com/assets/153526/22457150/83d1c4ca-e796-11e6-9b6a-318f408c45a6.png)
Unity and Blender imports this model fine, so the problem is not in the fbx itself. Most of the open source engines I tried however have problems with it.

**Comment by Alan-FGR** [comment]
Yeah, the bounding box really seems to be created from that pose. From the engines that worked, does any of them use Assimp? Assimp isn't very great with FBX that's why we have plans to use the Autodesk SDK for FBX files. Since you've said most of the open source engines aren't working and Assimp is the most popular importer for open source engines, I guess that could be related. However, I think you're using that model in Lumix with no problems, right? 🤔

**Comment by nem0** [comment]
Yeah, most of the stuff I tried uses Assimp. 

It causes problems even in Lumix (using Assimp), that's why I am trying different OSS checking if any of them manages to import it correctly, but not luck so far. BTW each one of them computes the pose differently. 

I am making an FBX Importer which uses Autodesk's SDK to check if it solves the problem. The problem with Autodesk's SDK is that it can not be distributed, but users have to install it and therefor I can't have a standalone version of the engine.

**Comment by nem0** [comment]
After some investigation it seems to be related to https://github.com/assimp/assimp/issues/1127

**Comment by mesilliac** [comment]
(this issue should now be fixed in assimp master)
