### ISSUE TITLE
Project needs to be opened in the editor to create cache directories before --project can be used

### ISSUE THREAD

**Issue by mattbenic** [AtomicGameEngine/AtomicGameEngine#144]
If a project file is opened using the --project argument on the editor executable, it fails if that project has not first been opened using the editor's Open Project menu option. It appears that required cache directories are not created in this case. This scenario can happen when one team member creates the project, and another opens if after cloning a repository (since the cache directories are ignored in source control).

**Comment by JoshEngebretson** [comment]
I am unable to replicate this on master, I tried on Windows and OSX including the permutations that the path can be provided in (with the .atomic file specified, with just the folder, and with the folder + a trailing slash)

The Cache folder should be created in the project loaded handler of the AssetDatabase:

https://github.com/AtomicGameEngine/AtomicGameEngine/blob/master/Source/ToolCore/Assets/AssetDatabase.cpp#L415

**Comment by JoshEngebretson** [comment]
This should not be an issue anymore, tested on Windows/OSX again this morning just to be sure
