### ISSUE TITLE
How to make a Javascript Editor plugin

### ISSUE THREAD

**Issue by JimMarlowe** [AtomicGameEngine/AtomicGameEngine#1449]
I would to know how to make a JS Editor plugin (TS, if it has to be).  I want to add a button in an Editor menu that executes a JS function, and then how to make the Editor use it.
Yes, there is an example "EditorPlugins" which does something, but there is no information on what it is or how to use it.

**Comment by Alan-FGR** [comment]
According to @darrylryan (we were discussing this on gitter), that's not possible. That being said I'm also interested in that but for C# 😺.

**Comment by shaddockh** [comment]
Editor plugins are currently supported, albeit somewhat limited.  I'll see if I can put together some notes on usage, but at the very least the following are possible:
- Scripts run in the same process as the editor
- Menu items can be added to the Developer->Plugins menu
- Menu items can be added to the right+click menu on files
- Menu items can be added to the right+click menu on the Hierarchy
- Plugins have access to the active scene
- Plugins have access to read/write project preferences
- Plugins can implement their own resource editors

These are just off the top of my head, but I can look at putting together some docs...at least enough to get someone over the hump.

**Comment by JimMarlowe** [comment]
TS alone is ok. Most interesting.

**Comment by shaddockh** [comment]
@JimMarlowe the beginnings of some docs are here: https://github.com/AtomicGameEngine/AtomicGameEngine/wiki/Editor-Extensions . This covers how to add a menu.  More docs need to be built, but this can get you started.

**Comment by JimMarlowe** [comment]
@shaddockh :camel:  A couple of notes... 
+ Real funny making the user change, add to, the original class definition in the wiki :laughing:  
+ Typescript is more readable than the Javascript that gets created, but you might want to say that you have to compile the plugin for it to become usable, for all the peeps that don't use TS (often).
+ Because the plugins are relative to a project, that makes it a little limiting. I found by experimentation, that I can have a global EditorData and soft link it into a Project, and get my plugins in all projects, perhaps the system could also do this?
![screenshot_2017_02_21_09_20_10](https://cloud.githubusercontent.com/assets/19511757/23176822/8ef93bec-f819-11e6-9142-592ac06a364f.png)

**Comment by shaddockh** [comment]
For having the user change the original class definition, I was trying to go for a step by step approach but maybe that's just overkill.  Also constructing an extension really needs to be more streamlined and simple.  I was thinking of having an Atomic.EditorExtension base class that could handle some of the boilerplate but I need to iterate on it a bit to see how it might work.

I do have notes in the code for eventually supporting a global extension directory but I wanted to see how project extensions worked first.  It shouldn't be difficult to pull from a directory in the same location as the user prefs in the future.

If you have any suggestions I've created #1400 and #1401 to brainstorm in.

**Comment by JimMarlowe** [comment]
The first point was **not** a negative, the procedure is fine the way it is. The structure is manageable, since the majority of what you want to do is inside the menuItemClicked function.

**Comment by JimMarlowe** [comment]
I'm considering this completed. With the https://github.com/AtomicGameEngine/AtomicGameEngine/wiki/Editor-Extensions page and the EditorPlugins example, this is enough to successfully apply what is available.
