### ISSUE TITLE
Windows 8.1 activation problems

### ISSUE THREAD

**Issue by brunosxs** [AtomicGameEngine/AtomicGameEngine#147]
I've narrowed it down by doing some tests and I think this is a windows 8.1 issue. I tested it in three different machines on the same network. 2 of them with windows 8.1. Those gave me this error.

I then tried to activate AGE in a third computer, my htpc/gaming pc that has windows 7_x64 and is the only machine that's wired to the network and surprise: It activated like a charm.

Lastly just to be sure, I tried activating in the two windows 8.1 machines again using the cables that connected the htpc and had no luck.

Both windows 8.1 are 64bit and were using the latest updates available. They are laptops with different hardware configurations.

I don't know how to program in c/c++ but I'd be willing to help with logs and things I can test. Just point me the direction.
![image](https://cloud.githubusercontent.com/assets/1557903/9101215/7b2900b0-3bba-11e5-9e40-225f8f0f65d5.png)

**Comment by JoshEngebretson** [comment]
Hello,  we've developed Atomic on Windows 8.1 64 bit and the activation issues to date have generally been with Web Proxies or firewalls.  The activation is a curl web request, so nothing fancy.  Do you have a web proxy or is Bitdefender or other firewall software blocking the connection?

**Comment by brunosxs** [comment]
No proxy, pretty standard connection through my router.

To be sure I even deactivated bitdefender's firewall(as seen on the image) and also windows firewall.

**Comment by JoshEngebretson** [comment]
If you're sure that nothing is interfering with the executable, does the behavior change at all when run as administrator?

**Comment by brunosxs** [comment]
No, it doesn't change.

I'll try some SSL restorations as I've seen in a support post in microsoft
community.

http://answers.microsoft.com/en-us/windows/forum/windows8_1-networking/ssl-error-after-upgrading-to-windows-81/b612e352-db41-4909-8376-e2d01204c923


Funny thing: It worked when I tried to run on VBox with win7 on it, with
the win8.1 machine working as host.

If nothing else works, I'll try a system restoration and a complete
factory-restore.

2015-08-06 1:13 GMT-03:00 JoshEngebretson <notifications@github.com>:

**Comment by brunosxs** [comment]
I don't know what was wrong in the first place, but after a complete factory restoration I was able to activate AGE on the laptop that caused this problem. I can only think about something wrong with the hosts file, maybe?

**Comment by JoshEngebretson** [comment]
Thanks for following up on this, glad it is now working.
