### ISSUE TITLE
Expose an API for determining mode player is being run in

### ISSUE THREAD

**Issue by mattbenic** [AtomicGameEngine/AtomicGameEngine#1481]
(I could have sworn I opened an issue about this previously, but I can't seem to track it down. I've also not found any obvious already exposed API for this, if I missed it please just point me in the right direction)

Add a field to AtomicPlayer::Player (and expose to C#) that indicates whether the player is running from the editor, from a debugger, or standalone.

**Comment by JoshEngebretson** [comment]
@mattbenic I recall an issue, from quite awhile ago, maybe it had to do with the "launched by editor" boolean?  #1489 punches this up a notch.  The ```PlayerApp``` can now report the mode it was launched in and ```AppBase``` can report whether a debugger is attached (on Windows). 

Here's some sample usage, I tested all the various modes, though please let me know if anything is behaving unexpectedly.  

```PLAYER_LAUNCH_STANDALONE``` is the standalone player
```PLAYER_LAUNCH_ATOMICEDITOR``` is running under the Atomic Editor's play mode
```PLAYER_LAUNCH_EXTERNALEDITOR``` is running from an external tool such as Visual Studio (or command line with --player option)

```csharp
// get the mode the player was launched in
var launchMode = PlayerApp.GetLaunchMode();

// print launch mode, either: 
// PLAYER_LAUNCH_STANDALONE, PLAYER_LAUNCH_ATOMICEDITOR, PLAYER_LAUNCH_EXTERNALEDITOR 
Log.Info("Launch Mode: " + Enum.GetName(typeof(PlayerLaunchMode), launchMode));

// check whether a debugger is attached
if (AppBase.GetDebuggerAttached())
{
    Log.Info("Debugger Is Attached");
}
```

**Comment by mattbenic** [comment]
I see PLAYER_LAUNCH_STANDALONE is reported when running from visual studio, but without --player. So basically debugging a standalone player. This is _exactly_ the behavior I was hoping for, but doesn't quite match what you're describing (might have expected PLAYER_LAUNCH_EXTERNALEDITOR here) so just mentioning it for your sake :)

**Comment by JoshEngebretson** [comment]
If you are running from VS without the  ```--project``` argument it will report as standalone, I mentioned ```--player``` for when running the editor off the command line, sorry didn't make that clear.  

https://github.com/AtomicGameEngine/AtomicGameEngine/blob/8b618aa65e0b431b5d705a3af10bc9bedec1b892/Source/AtomicNET/NETNative/Desktop/NETIPCPlayerApp.cpp#L56

You are running from Visual Studio without ```--project```?  This is added automatically by the project gen, so just making sure, glad it works for ya!
