### ISSUE TITLE
Can we make plugins with atomic game engine?

### ISSUE THREAD

**Issue by gdefraiteur** [AtomicGameEngine/AtomicGameEngine#1491]
Hello, i'm pretty interested in working with your game engine, but i wonder if it is possible to write scripted editor plugins, directly in C#, instead of having to rebuild the sources?

Would be great if it was possible.

**Comment by JoshEngebretson** [comment]
Hello, there is plugin support for TypeScript, which the editor itself is scripted in.  Moving the editor to be a managed application is not trivial and would be required for C# plugins.  The GitHub issue tracker isn't really a good place to ask questions, please see; https://discourse.atomicgameengine.com
