### ISSUE TITLE
[C#] UIView/UILayout ignore Left/Right layout

### ISSUE THREAD

**Issue by mattbenic** [AtomicGameEngine/AtomicGameEngine#1501]
When setting up a layout and using a LayoutPosition or Gravity that includes Left/Right settings, they are ignored. Eg the following results in controls being at the bottom center of the layout:

```
            UILayout layout = new UILayout()
            {
                LayoutPosition = UI_LAYOUT_POSITION.UI_LAYOUT_POSITION_RIGHT_BOTTOM,
                Rect = viewport.Rect
            };
```

**Comment by JoshEngebretson** [comment]
There are a number of factors here, I believe this depends on the axis of the layout.  TB (like many UI systems) can be difficult to wrap head around layout engine.  WYSIWYG UI editors are great, with ways of setting layout and checkboxes to see what they do.  Laying out in code can feel like trial and error.

This is also part of the reason I want to move to an immediate mode UI for editor UI, simplifies both layout and event/input handling.  TB is a great fit for nice looking project UI, not so much for simple, get it done, editor stuff.

We can get the test doing the expected thing: https://github.com/AtomicGameEngine/AtomicTests/tree/master/CSharpTests/MultiViewport

**Comment by mattbenic** [comment]
Ah ok, so it's not just a wrapped API issue?

**Comment by JoshEngebretson** [comment]
It could be a binding issue, though more likely a problem with setting up the layout.

**Comment by JoshEngebretson** [comment]
I updated the test with the missing layout and some comments:

https://github.com/AtomicGameEngine/AtomicTests/blob/master/CSharpTests/MultiViewport/Resources/Scripts/AtomicMain.cs#L37

There is a TB Layout cheatsheet available on the Wiki thanks to @JimMarlowe,  https://github.com/AtomicGameEngine/AtomicGameEngine/wiki/Turbobadger-Layout-Cheat-Sheet

I filed #1502 to rename C# enums so that ```UI_LAYOUT_POSITION.UI_LAYOUT_POSITION_RIGHT_BOTTOM``` becomes this ```UI_LAYOUT_POSITION.RIGHT_BOTTOM```

**Comment by mattbenic** [comment]
Awesome thanks, this helped a lot
