### ISSUE TITLE
Android deploy with gdbserver 

### ISSUE THREAD

**Issue by JimMarlowe** [AtomicGameEngine/AtomicGameEngine#1506]
On Android, in order to debug APKs on the device, gdbserver must be embedded in the APK. 
The official way of doing this is using the scripts in the NDK directory (ndk-build, ndk-gdb).  There are other ways this can be done (QtCreator, Eclipse) which do not use the official scripts. 
The gist of the problem is the gdbserver (and possibly gdb.setup) must be embedded in the lib directory of the apk.

**Comment by JimMarlowe** [comment]
:rabbit: interesting trip down the bunny trail, hacks relating to not being able to include gdbserver in apk/lib, the attempt to fool the apk standards/security is to rename gdbserver libgdbserver.so. This may work for android apps that manage loading their own shared libraries, but Atomic/Urho has this gem... https://github.com/AtomicGameEngine/AtomicGameEngine/blob/master/Data/AtomicEditor/Deployment/Android/src/org/libsdl/app/SDLActivity.java#L119 (and the next line) so any .so will be linked to the atomicplayer.

**Comment by JimMarlowe** [comment]
An option to get around the Atomic specific libgdbserver.so naming issue, is to name it gdbserver.so, but then the qtcreator helper scripts will need to be modified to reference the name change.

**Comment by JimMarlowe** [comment]
This is how I propose to enable this feature. Fix the file SDLActivity.java to NOT autoload any file as a library if it contains the all or part of the word "gdbserver" in the file name. This will allow QtCreator and any other IDEs to use libgdbserver.so without further modifications. 
In the Android Build settings dialog box, change the Release Path check button to a SelectDropdown menu with these options 
- Debug
- Debug Source with gdbserver
- Debug Source with libgdbserver.so
- Release

The Debug option would be the current debug option, it produces an APK with no signing.
The Debug Source with gdbserver creates a debug APK, and gets the gdbserver executable out of the NDK and puts it in the APK /lib/abi/ folder so it can be called by external programs.
The Debug Source with libgdbserver.so creates a debug APK, and gets the gdbserver executable out of the NDK and puts it in as APK /lib/abi/libgdbserver.so folder so it can be called by external programs, such as QtCreator.
The Release option is the current release option, the path must be filled out to a directory that contains the code signing passwords in order to make a release APK.

The current structure of the Atomic Android launcher program is not compatible with ndk-build and ndk-gdb.

**Comment by JoshEngebretson** [comment]
This sounds good from here, do you think it is a good idea to follow up with ndk-build/ndk-gdb compatibility?  I am not sure what the delta might be there... reason to support both current path and ndk-build if the later is supported?

**Comment by madsystem** [comment]
Here a blogpost I wrote about this: https://madsystem.github.io/2017/04/06/debugging_native_android_applications_with_gdb.html

**Comment by JimMarlowe** [comment]
@JoshEngebretson the current path is functioning, I'm inclined to leave it alone and not go for ndk-build compatibility. My reasoning is, while I'm fine with doing gdb by command line, using an IDE or QtCreator is far easier. And the current path is also old, and will have to change in order to use gradle, and needs the google play stuff, so once it has to change, then see if ndk-build is still a thing.

**Comment by JimMarlowe** [comment]
Ive updated the wiki with the latest features from #1506 https://github.com/AtomicGameEngine/AtomicGameEngine/wiki/Building-From-the-Editor

**Comment by JoshEngebretson** [comment]
@JimMarlowe Very nice!  Thanks for updating the wiki 👍 

Sounds good, one thing I would like to look into is integration with Android Studio.  It might be good to support deployment/project generation through it.  Power to the people, right on! 🌺
