### ISSUE TITLE
AtomicEditor can not display text based files

### ISSUE THREAD

**Issue by JimMarlowe** [AtomicGameEngine/AtomicGameEngine#1523]
At least on Linux, trying to view project text based file (js or ts) in the editor results in the tab being created, an 1 empty line being displayed.  In the editor log there is this error : 
[Mon Apr 17 10:52:18 2017] INFO: WebViewJS: Uncaught (in promise) TypeError: Cannot read property 'ProjectPreferences' of undefined (atomic:///home/jm/AGE/AtomicGameEngine/Artifacts/AtomicEditor/Resources/ToolData/CodeEditor/source/editorCore/editor/editorCommands.js:84)

**Comment by shaddockh** [comment]
That looks like it's trying to read the global variable set on the web view, but it doesn't exist.  That variable should be set when the project is being loaded at:
https://github.com/AtomicGameEngine/AtomicGameEngine/blob/master/Script/AtomicEditor/editor/Editor.ts#L233

Do you know if that line is being accessed prior to the text editor opening?

**Comment by JimMarlowe** [comment]
I had been only looking at existing projects when this was happening. Reading between lines, I created a new project, and it is able to load files. Then going back to my existing projects, they too can now load files again. You fixed it :camel: 
But there is some condition somewhere that causes this problem, now that mine is healed, Im of no help.

**Comment by shaddockh** [comment]
Yes, it looks like it.  But that shouldn't be causing the error you reported.  It appears that might be an old entry in there.  The code is setting the value to:

``` "codeEditor": { "theme": "??" },```

**Comment by JimMarlowe** [comment]
@shaddockh you were correct about my "CodeEditor" block, that must have been when I was doing the theme switching...  Now after dumping everything and rebuilding, I am able to reproduce the issue. What I'm finding is, If I start an existing project with "junk" in my projectname.atomic, I can't load text files UNLESS I load a project that contains "good" contents in the  projectname.atomic, then this fixes something in the editor process, and I can then load other existing projects and edit text. When I take the editor down, then it becomes unhealed, and it starts all over again. 
I've been putting comments in the projectname.atomic about the project, and if I "fix" the "bad" projectname.atomic, it starts working as expected. The system hasn't cared about them at all (they are often empty) until a few commits ago.

**Comment by JimMarlowe** [comment]
I could probably put my comments into well-form json :rofl: or just keep my comments in another file. Case closed.
