### ISSUE TITLE
./Build_AtomicEditor.sh  --with-web building errors

### ISSUE THREAD

**Issue by JimMarlowe** [AtomicGameEngine/AtomicGameEngine#1525]
There are two files that do not compile for --with-web, Input.cpp and FileSystem.cpp, specificity for emscripten,

**Comment by JoshEngebretson** [comment]
WebGL is currently the only platform without CI checks on PR's.  There is probably a light amount of work getting it building/running again with the recent updates.  There is also apparently some work in the Urho build for WASM support, would be interesting to look into...

**Comment by JimMarlowe** [comment]
in FileSystem.cpp FileSystem::GetProgramDir() has an ATOMIC block of code in it for support of #1209, #1217, and uses variables that are no longer in the class. If an OSX project can deployed successfully, the code can be removed.
in Input.cpp, the Cursor class is no longer being used, its commented out for all other platforms, not in emscripten functions. 

WASM support appears to manifest itself as a linker flag `-s WASM=1` to emcc, it can be a WebGL build option.

Shoot. I cleared the errors and deployed a project to WebGL, it faults at 
missing function: _ZN6Atomic25RegisterNavigationLibraryEPNS_7ContextE  AtomicPlayer.js:1:3478

**Comment by JoshEngebretson** [comment]
Closed via #1526 👍
