### ISSUE TITLE
D3d11 deferred rendering broken

### ISSUE THREAD

**Issue by Nyt0x** [AtomicGameEngine/AtomicGameEngine#1545]
So far it seem to point toward something broken when using d3d11 in deferred with perpixel lights. (Maybe there's more things broken)

Could be related to recent changes on the way defines are handled for shader d3d11 variations.

To repro that isuue easily just run a sample scene (Water sample, rotating chest sample) in deferred (you might have to either force the editor or the player to run in deferred using Engine.json for example)

**Comment by Nyt0x** [comment]
Taking a capture with renderdoc it seems that only the viewport render target is bound in deffered the albedo/normal/depth are not during the scenepass.

**Comment by Nyt0x** [comment]
As a quick test I just disable creating any texture using msaa, directly in Texture2D::Create by commenting out this: https://github.com/AtomicGameEngine/AtomicGameEngine/blob/master/Source/Atomic/Graphics/Direct3D11/D3D11Texture2D.cpp#L384 to force no multisampling

No more issue with deferred rendering. Output RT are bound correctly.

Not sure yet why it doesn't work.. I don't remember any d3d limitation for binding multiple RT with msaa except the huge amount of memory the g-buffer will take in the end) but maybe I'm wrong!

**Comment by JoshEngebretson** [comment]
Good sleuthing, this doesn't happen on Urho master correct?

**Comment by Nyt0x** [comment]
Did not test Urho master, it's been a while I did not touch it (since I switch onto AGE :D ). If I find the time I will.
However, my bet would be that the additional RT for deferred that are defined in the renderpath do not take the msaa value the viewport RT is define with, hence why d3d does not bind them (and why I get the d3d error telling me the RT are of different sizes).

I'm not sure how the main RT (viewport) gets it's msaa attribute (probably from engine.json if defined, or any default value) dunno if this should be a flag in the renderpath commands to let the parser know the output render target should be the same msaa level as the main RT. Or maybe just re-use the sizedivisor argument.

**Comment by JoshEngebretson** [comment]
Thanks for the R&D, this is a blocker to switching to D3D11 as default, do you have some time to look into a fix, no big hurry.  

One of the things I want to get by switching to D3D11, is shared GPU resources across processed... this is possible under D3D9Ex, though that is gnarly and really we should be on D3D11 for drivers and performance improvements now anyway... D3D9 will be deprecated, that API had an amazing run!
