### ISSUE TITLE
[C#] Static "get" methods are wrapped as non-static properties

### ISSUE THREAD

**Issue by mattbenic** [AtomicGameEngine/AtomicGameEngine#1573]
While the methods themselves are correctly wrapped as static, the shorthand properties for them are non-static. As an example, in AppBase.h:

        static bool GetDebuggerAttached();

Becomes (in CSModuleAtomicApp.cs):

      public bool DebuggerAttached
      {
         get
         {
            return GetDebuggerAttached();
         }
      }

      public static bool GetDebuggerAttached ()
      {
         return csb_AtomicApp_AppBase_GetDebuggerAttached_4925();
      }

**Comment by JoshEngebretson** [comment]
Good catch, this should be an easy one to pick off this morning 🔫

**Comment by JoshEngebretson** [comment]
Fixed https://github.com/AtomicGameEngine/AtomicGameEngine/commit/e0ea1912533d04bddb7b08742b6b873a9d3e7a4e, shouldn't be too bad to cherry pick in ;)
