### ISSUE TITLE
slow operation with new platformer on xcode build

### ISSUE THREAD

**Issue by lewislepton** [AtomicGameEngine/AtomicGameEngine#158]
howdy,

this is just to show the new platformer from the github repo of examples performs at a very slow rate. seems fine in the public release. but just to say about really. here is a gif recording it

![slowplatformernew](https://cloud.githubusercontent.com/assets/11299322/9173104/e312eb6a-3f6f-11e5-938d-060237057b53.gif)

**Comment by JoshEngebretson** [comment]
Thanks for the report, this is a debug build.  Please switch to release so the compiler optimizes the code, or change the number of ray casts the sun is doing by selecting it in the editor and dropping from 1024 to something like 256
