### ISSUE TITLE
[Editor] Draggin and Droppen is b0rken

### ISSUE THREAD

**Issue by JimMarlowe** [AtomicGameEngine/AtomicGameEngine#1609]
In the Editor, dragging and dropping has ceased to function.  By using a binary build search, the breaking commit seems to be ``2cb4ac0 3D UI Feature``  The failure mechanism is the UIDragDrop::HandleMouseDown() is now occurring **before** the HierarchyFrame.handleWidgetEvent() 

The HierarchyFrame.handleWidgetEvent() assigns the drag object to the heirlist.
UIDragDrop::HandleMouseDown() looks up the hoverwidget, and searches the parents for the drag object, now too soon.

**Comment by JoshEngebretson** [comment]
Thanks for the report and helping track this down.  I'll have a look this morning.

**Comment by JoshEngebretson** [comment]
#1609 should address the issue which was introduced when refactoring for multiple "root" UIViews.
