### ISSUE TITLE
Visual studio already installed but still asking anyway

### ISSUE THREAD

**Issue by nesrak1** [AtomicGameEngine/AtomicGameEngine#1621]
I have Visual Studio 2015 installed along with Xamarin and after building the editor, trying to open the content examples I got this:
![atomiceditor_2017-08-09_12-47-58](https://user-images.githubusercontent.com/12544505/29135819-0147dbec-7d01-11e7-8217-4749d990016d.png)
Thinking it was just something wrong with the source, I installed build3 and tried all of the csharp projects and creating my own but they all showed the same message. I updated Xamarin, restarted computer, same message. I've had atomic with vs2015 work on a different computer, so I don't think I need to install vs2017.

**Comment by JoshEngebretson** [comment]
The detection code is here: https://github.com/AtomicGameEngine/AtomicGameEngine/blob/master/Source/ToolCore/NETTools/NETProjectSystem.cpp#L519

You can place a breakpoint and see where things are going sideways.

**Comment by nesrak1** [comment]
I changed the environment variable and added a \ to the end and it seems to have worked.

**Comment by JoshEngebretson** [comment]
Hey, that's great, would you might expanding on this a bit?  It would be good to fix it for others and this is the first time it has been reported.

**Comment by nesrak1** [comment]
![image](https://user-images.githubusercontent.com/12544505/29140509-53a00ee6-7d10-11e7-95b0-e68ceb7f63bd.png)+R, type `sysdm.cpl`. Advanced tab, Environment Variables. Find VS140COMNTOOLS and click Edit. Add a \ after Tools. Click OK three times and restart.
