### ISSUE TITLE
[UI] Scroller doesn't work by code

### ISSUE THREAD

**Issue by darrylryan** [AtomicGameEngine/AtomicGameEngine#1626]
The scroll container only seems to work if using a tb.txt to do the layout and controls don't show up if you add them by C#.

**Comment by JimMarlowe** [comment]
@darrylryan could you provide the code (a snippet?) you were using to create the scroll container?

**Comment by darrylryan** [comment]
`        UIWindow inventory = new UIWindow();
        inventory.LayoutParams = new UILayoutParams
        {
            Width = 370,
            Height = 400
        };

        UILayout insideWindowLayout = new UILayout();
        insideWindowLayout.SetLayoutConfig("XPCPC");
        insideWindowLayout.LayoutDistributionPosition = UI_LAYOUT_DISTRIBUTION_POSITION.UI_LAYOUT_DISTRIBUTION_POSITION_LEFT_TOP;
        insideWindowLayout.LayoutParams = new UILayoutParams { Width = 370, Height = 400 };
        insideWindowLayout.Axis = UI_AXIS.UI_AXIS_Y;


        UIScrollContainer scroller = new UIScrollContainer();
        scroller.Gravity = UI_GRAVITY.UI_GRAVITY_ALL;
        scroller.ScrollMode = UI_SCROLL_MODE.UI_SCROLL_MODE_Y_AUTO;
        insideWindowLayout.AddChild(scroller);

        UILayout insideScroller = new UILayout();
        insideScroller.SetLayoutConfig("XPCPC");
        insideScroller.Axis = UI_AXIS.UI_AXIS_Y;
        insideScroller.LayoutSize = UI_LAYOUT_SIZE.UI_LAYOUT_SIZE_AVAILABLE;
        insideScroller.LayoutDistribution = UI_LAYOUT_DISTRIBUTION.UI_LAYOUT_DISTRIBUTION_AVAILABLE;
        insideScroller.LayoutDistributionPosition = UI_LAYOUT_DISTRIBUTION_POSITION.UI_LAYOUT_DISTRIBUTION_POSITION_LEFT_TOP;
        scroller.AddChild(insideScroller);

        UIImageWidget uislots = new UIImageWidget();
        uislots.Image = "UI/slots.png";
        uislots.LayoutParams = new UILayoutParams { Width = 323, Height = 457 };
        insideScroller.AddChild(uislots);

        inventory.AddChild(insideWindowLayout);
        inventory.ResizeToFitContent();
        UIView.AddChild(inventory);`


@JimMarlowe

**Comment by JimMarlowe** [comment]
I found the root cause of the issue, which is the UIScrollContainer has a component widget that you add children to, instead of the main widget. This is a common behavior with TB for composite widgets, though is poorly (as in not at all) documented :disappointed: 
The code below appear to be a good match for a layout file version. The code was also optimized to remove layout sizing that wasn't needed and some layout modes for layouts with a single child. 

```
UIWindow inventory = new UIWindow();
inventory.SetAxis (UI_AXIS.UI_AXIS_X);  // just like the doctor ordered
// this LayoutParams removed - doesnt do anything, the window gets its size from the content in ResizeToFitContent

UILayout insideWindowLayout = new UILayout();
insideWindowLayout.SetLayoutConfig("YACAC");  // shorthand for layout values, use all available space
insideWindowLayout.LayoutParams = new UILayoutParams { Width = 370, Height = 400 };

UIScrollContainer scroller = new UIScrollContainer();
scroller.Gravity = UI_GRAVITY.UI_GRAVITY_ALL;
scroller.ScrollMode = UI_SCROLL_MODE.UI_SCROLL_MODE_Y_AUTO;
insideWindowLayout.AddChild(scroller);
UIWidget scrollroot = scroller.GetContentRoot();  // this is the fix for nothing showing up in the UIScrollContainer

UILayout insideScroller = new UILayout();
insideScroller.SetLayoutConfig ("YACAC");
scrollroot.AddChild(insideScroller);  // change here, scrollroot instead of scroller

UIImageWidget uislots = new UIImageWidget();
uislots.Image = "UI/slots.png";
uislots.LayoutParams = new UILayoutParams { Width = 323, Height = 457 };
insideScroller.AddChild(uislots);

inventory.AddChild(insideWindowLayout);
inventory.ResizeToFitContent();
UIView.AddChild(inventory);

```

**Comment by darrylryan** [comment]
@JimMarlowe You are a genius! THANKYOU 💃 🕺 

I wonder what the point in being able to add children to the main widget is though? Maybe our wrapper should redirect the addchild to the content widget since adding stuff to the composite widget seems neither functional nor useful.

**Comment by JimMarlowe** [comment]
I agree that the AddChild on TB/UIScrollContainer is non sequitor, fixing this certainly falls into the usability department. I'd have liked to fix TBScrollContainer in TB land, but AddChild is not virtual there. In Atomic land, AddChild is virtual, so I can fix UIScrollContainer and add a note about this feature.  The work-around code above will continue to work after the fix is made.
