### ISSUE TITLE
[AtomicNET] CreateComponent returns a new (allocated) bogus component.

### ISSUE THREAD

**Issue by Alan-FGR** [AtomicGameEngine/AtomicGameEngine#1632]
Consider the following code based on an empty C# project:
```c#
Scene s = AtomicNET.GetSubsystem<Player>().LoadScene("Scenes/Scene.scene");
DebugRenderer a = s.CreateComponent<DebugRenderer>();
DebugRenderer b = s.GetComponent<DebugRenderer>();
Debug.WriteLine($"ret obj: {a.ID}");
Debug.WriteLine($"get obj: {b.ID}");
```
It's obvious that a and b should be the same object since there are no other DebugRenderers, but they aren't. CreateComponent is creating and returning a different component than the one that's being actually added to the scene, so two DebugRenderers are created there. This could represent a memory leak since the object returned is indeed valid and has a proper unmanaged object bound to it.

**Comment by JoshEngebretson** [comment]
This is not a bug, the scene XML has a DebugRenderer.  You are creating a new DebugRenderer and the get call returns the first on the node.

https://github.com/AtomicGameEngine/AtomicGameEngine/blob/master/Data/AtomicEditor/ProjectTemplates/EmptyProject/CSharp/Resources/Scenes/Scene.scene#L16

**Comment by Alan-FGR** [comment]
Lol, you're absolutely right... it was my mistake, sorry. I'm pretty sure I've checked the scene in the editor for DebugRenderers, but I guess I haven't selected the scene in the hierarchy or something... whatever was the case: boy was it dumb! 😆

**Comment by JoshEngebretson** [comment]
A C# version of GetOrCreateComponent would be handy when in doubt, it would go around here: 

https://github.com/AtomicGameEngine/AtomicGameEngine/blob/982da971fdd27652eb682883b99e4f4c9313cf7d/Script/AtomicNET/AtomicNET/Scene/Node.cs#L148
