### ISSUE TITLE
[Building] How to build without the Submodules, specifically CEF and the Examples?

### ISSUE THREAD

**Issue by Alan-FGR** [AtomicGameEngine/AtomicGameEngine#1633]
I've asked this numerous times on Gitter, but never was able to find a solution and always surrendered to the tyranny of the pesky submodules 🤣... but it's really getting annoying. After cloning non-recursively, if you run the shell/batch scripts they start downloading the massive binaries... if you try to cmake it same thing happens, and I don't think people should be doing that directly because any customization fails without running the  javascript magic anyway 😄... steps on how to build just Atomic without CEF (and by consequence the editor) and the Examples would be greatly appreciated... it doesn't have to be fancy, just some very rough steps on how to achieve such a feat, and I'll be happy to add them to the wiki with proper formatting and in a friendly presentation.

**Comment by rokups** [comment]
If you clone my [optional submodules PR branch](https://github.com/rokups/AtomicGameEngine/tree/feature/optional-submodules) you can run cmake like this:

    cmake -DATOMIC_CPLUSPLUS_EXAMPLES=0 -DATOMIC_WEBVIEW=0 /path/to/cloned/repo

That will not clone submodules and build everything except examples and anything that depends on cef webview (like editor).

**Comment by mattbenic** [comment]
@rokups did your build changes get PRd in?

@CTrauma adding you to this since you're also working on the build system.

**Comment by rokups** [comment]
@mattbenic yes, [they were merged](https://github.com/AtomicGameEngine/AtomicGameEngine/commit/2152ba1df4679515204456ac70d8795adee565eb).

**Comment by mattbenic** [comment]
Ok so can we close this?

**Comment by Alan-FGR** [comment]
@rokups tested it so I'm closing @mattbenic

**Comment by mattbenic** [comment]
Ok, so could you please add the above detail to the wiki page(s) on building, then we can close this.

**Comment by rokups** [comment]
Wiki has build instructions only using scripts. I have no idea how they work. Do they accept CMake variables?

**Comment by mattbenic** [comment]
I don't think so. There are specific arguments that add/remove CMake variables, so it would be possible to add an argument that would make this change, if it's important enough. I do think it's one worth adding if someone wants to grab it.

**Comment by rokups** [comment]
That would be maintaining js part of build system that should be replaced with pure cmake. I do not think its worth it.

**Comment by mattbenic** [comment]
Fair enough. So close and "wontfix" this?

**Comment by rokups** [comment]
It already is fixed. All one has to do is build repo without cef and examples, meaning pass `-DATOMIC_CPLUSPLUS_EXAMPLES=0 -DATOMIC_WEBVIEW=0`.

**Comment by mattbenic** [comment]
Ah right, sorry I missed @Alan-FGR's close above
