### ISSUE TITLE
[CMake/Profiler] Qt libraries are not copied to the profiler output folder

### ISSUE THREAD

**Issue by Alan-FGR** [AtomicGameEngine/AtomicGameEngine#1635]
I just cmaked Atomic here with the profiler and the resulting VS2017 project isn't configured to copy the dlls to the profiler output folder, so you can't run the binary directly after building it, you have to either copy or configure that manually. @rokups ;)

**Comment by Alan-FGR** [comment]
Just found out that more stuff is broken (icons, etc.), profiler works but something's wrong... closing this until further investigation

**Comment by rokups** [comment]
Build system is supposed to [invoke all dependency copying](https://github.com/AtomicGameEngine/AtomicGameEngine/blob/84b82ef5cec4dfeabdc7f3d2983a5684748dafce/Build/CMake/Modules/AtomicCommon.cmake#L236) to `Artifacts/Build/Profiler/` when built on windows. Icons would be broken when qt svg plugin is missing, but dll copying should take care of that.

**Comment by Alan-FGR** [comment]
@rokups yep, copying the Qt5Svgd.dll there makes it work properly (apparently). However, it won't copy the dlls to the output directory upon building. I didn't do anything different, just cloned, cmaked it pointing the Qt stuff to the dlls in my system, opened the VS2017 project and built it. Feel free to confirm, but it doesn't work outta the box for me :P
