### ISSUE TITLE
JavaScript Editor Autocomplete is currently disabled, look into options possibly Ace 

### ISSUE THREAD

**Issue by lewislepton** [AtomicGameEngine/AtomicGameEngine#164]
you did say there would have maybe been a problem with this build, so think this it is ;)

**Comment by JoshEngebretson** [comment]
Auto complete has been disabled until it can be properly addressed as it was problematic

**Comment by lewislepton** [comment]
ah fair enough

**Comment by benwolf** [comment]
No longer valid, using Monaco now.
