### ISSUE TITLE
F#

### ISSUE THREAD

**Issue by ShalokShalom** [AtomicGameEngine/AtomicGameEngine#1646]
Since C# is supported, is F# also possible?

**Comment by NathanWarden** [comment]
Unless I'm mistaken, it won't be out of the box. However, they have a new binding API which makes essentially every multi-threaded language possible to be used with Godot, but only C# will be officially supported.

For instance, someone has already made a python 3 version of Godot:
https://godotengine.org/article/beta-release-python-support

**Comment by ShalokShalom** [comment]
How is Godot related to Atomic?

I ask because both, C# and F# compile into CIL, so i thought the API use that one.

**Comment by NathanWarden** [comment]
Oops, haha, most of my notifications come for that and didn't notice I was commenting on Atomic :)

**Comment by ShalokShalom** [comment]
:smile:

**Comment by ShalokShalom** [comment]
How is it about the API in Godot? 

CIL or C# directly?

**Comment by NathanWarden** [comment]
Adding it's still a work in progress as there isn't even an alpha build with C# support yet, but I'm almost 100% certain it'll be CIL.

**Comment by NathanWarden** [comment]
To be more clear, I did my own build of Godot a few weeks back and had to make builds of my C# project for it to execute anything, so definitely CIL.

Does F# work with C# as long as it's CIL? I've never actually written any F# but have been curious about it.

**Comment by ShalokShalom** [comment]
F# compiles into CIL, like C# does.

**Comment by ShalokShalom** [comment]
Its actually working, checked with the devs.
