### ISSUE TITLE
Atomic ID?

### ISSUE THREAD

**Issue by ghost** [AtomicGameEngine/AtomicGameEngine#1654]
I thought this is free software after all.
So, why is it necessary to force a user to sign up for an Atomic ID for just being able to work with the editor?
This should be optional.

**Comment by JimMarlowe** [comment]
Only the binary Atomic distributions require registration. If you build the system from source, there is no registration involved.

**Comment by V1p3** [comment]
Thank you.

I wonder why this requirement is present in the binary distribution then.

**Comment by JimMarlowe** [comment]
I recall it had to do with the licenses/certifications that had to be done on the binaries in order to make them install properly, or at least without warnings.

**Comment by JoshEngebretson** [comment]
The provided binaries are quite out of date and it is best to build from source now.  On Windows, the EV Code signing on the binary installer was quite expensive at $449 for one year.  Without this code signing, IE/Chrome/Firefox wouldn't keep the downloaded file around and/or raise scary warnings about installing the Atomic Editor w/ platform player binaries.  The certificate is expiring soon and best to update the site so Windows, Mac, Linux point to from source build instructions.
