### ISSUE TITLE
Error related to Node.js when building from source (Arch Linux)

### ISSUE THREAD

**Issue by telmotrooper** [AtomicGameEngine/AtomicGameEngine#1658]
Hello, guys. I've been trying to build the engine from source on Arch Linux with no success.
I think I got all the dependencies installed (since I just downloaded the ones required by that one outdated AUR package), which I believe are: alsa-lib, glu, gtk3, libgl, cmake, git and nodejs.

But the thing is, when I try to build by running Build_AtomicEditor.sh I get:
`which: no nodejs in (/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/local/cross/bin)`
And when it's around 95% the compilation fails.

It seems to be related to Node.js, since it shows a JavaScript error. My Node.js executable is `/usr/bin/node`, but I couldn't find a way to set that path in the build script. Can anyone help me?

**Comment by telmotrooper** [comment]
Okay, so I realised I could just create a symbolic link to workaround the issue and I did it:
`sudo ln -s /bin/node /bin/nodejs`
Now I don't get that `which` error but I still can't compile. The error is at 94%.

I'm gonna paste it here:

```
[Sat Oct 14 20:44:33 2017] INFO: Generating C# Bindings
Script/TypeScript/duktape.d.ts(11,18): error TS2300: Duplicate identifier 'require'.
../../node_modules/@types/node/index.d.ts(118,13): error TS2300: Duplicate identifier 'require'.
jake aborted.
Error: Process exited with error.
    at api.fail (/home/telmo/Desktop/AtomicGameEngine/Build/node_modules/jake/lib/api.js:336:18)
    at Exec.<anonymous> (/home/telmo/Desktop/AtomicGameEngine/Build/node_modules/jake/lib/utils/index.js:124:9)
(See full trace by running task with --trace)
make[3]: *** [Source/AtomicTool/CMakeFiles/AtomicToolCheckScripts.dir/build.make:59: Source/AtomicTool/CMakeFiles/AtomicToolCheckScripts] Error 2
make[2]: *** [CMakeFiles/Makefile2:2821: Source/AtomicTool/CMakeFiles/AtomicToolCheckScripts.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:2646: Source/AtomicNET/NETNative/CMakeFiles/AtomicNETNative.dir/rule] Error 2
make: *** [Makefile:599: AtomicNETNative] Error 2
/home/telmo/Desktop/AtomicGameEngine/Build/node_modules/jake/lib/api.js:340
        throw errObj;
        ^

Error: Process exited with error.
    at api.fail (/home/telmo/Desktop/AtomicGameEngine/Build/node_modules/jake/lib/api.js:336:18)
    at Exec.<anonymous> (/home/telmo/Desktop/AtomicGameEngine/Build/node_modules/jake/lib/utils/index.js:124:9)
    at emitTwo (events.js:125:13)
    at Exec.emit (events.js:213:7)
    at ChildProcess.<anonymous> (/home/telmo/Desktop/AtomicGameEngine/Build/node_modules/jake/lib/utils/index.js:227:20)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

I'd be grateful if someone could help me.

**Comment by rokups** [comment]
Hey,
You probably are missing `referenceassemblies-pcl` package. Try installing it.

**Comment by telmotrooper** [comment]
@rokups Just installed and tried again, same error. :/

**Comment by vantienvincent** [comment]
I got the exact error on Mac 10.11 and Mac 10.12. (same messages)

**Comment by jellythedoge** [comment]
i get a similar or same error

**Comment by mattbenic** [comment]
I'm not familiar with the linux build, but the Windows version includes its own node executable to use to build. @rokups is this not the case for linux?

**Comment by rokups** [comment]
I think i saw executable for linux in repository too, but build system appears to look for executable installed in the system.

**Comment by mattbenic** [comment]
It might be possible to change it fairly simply to use the one in the repo then? Is this something you could look into (I'm on Windows) or should I cast it out on gitter?

**Comment by madscientist42** [comment]
1) Why only "medium"?  It's not compiling, gang.  Most professionals call that a, "showstopper".  Doesn't matter if it's not "your" OS.  This is a smidge offputting, really.  

2) Why is Atomic using it's "own" Node.js?  Not saying you shouldn't- but you're overriding the system default behaviors and not getting it right.  What does this class of issue do to the end-users getting the games built upon this framework?  How do you know this doesn't break other things?  

3) It's almost a year now...and it seems nobody's given a tinker's damn on this.  Build broken is a major issue and at the least the devs should work with the reporter/people seeing the problem to see what they can do rather than letting them haplessly flail around.  Most people don't grok buildsystems, to be honest with you- moreover...there's potential issues when you've got something THIS complicated.  The time here from report to now is offputting.  The fact that you've got what is essentially a fragile build system is even MORE offputting.

In the end, you're supposed to want people to use your framework- this sort of fail, not building, and the devs, basically, not caring because they only "do" Windows is bad.  Why should I choose Atomic for my next FPS, etc.?  Oh, wait...

**Comment by telmotrooper** [comment]
@madscientist42 Honestly when I couldn't get this to work I went for [Godot Engine](https://github.com/godotengine/godot) and I have not regretted it.

**Comment by waterfirezero1** [comment]
I changed to Godot also after failed installation

**Comment by mattbenic** [comment]
The original developer of the engine has moved on, and there is no longer a community actively developing it. I would suggest moving on to another engine.

**Comment by madscientist42** [comment]
It's slow on evaluation.  This is with an MSI ApachePro that chews up
things like DeusEx and Shadow of Mordor and spits out the seeds.  I agree
with the sentiment about considering elsewhere.  It's like I said...one
year?

**Comment by madscientist42** [comment]
So, it's no longer being developed?  If there's suggestions by collabs to leave...WHY are you not flagging this in the README.md

Such a waste, such a shame- it had potential and with 26 collabs, you'd think they'd have kept up with it.

**Comment by Alan-FGR** [comment]
Anybody is free to fund further development. Until then people have bills to pay and mouths to feed.
@mattbenic I agree we should have that info very clearly stated in the README.md

**Comment by mattbenic** [comment]
Agreed. Change to readme made
