### ISSUE TITLE
OpenAssetImporter.cpp mistyped variable name in a condition.

### ISSUE THREAD

**Issue by mikailcolak** [AtomicGameEngine/AtomicGameEngine#1665]
I may found a problem in "~~/AtomicGameEngine/Source/ToolCore/Import/OpenAssetImporter.cpp";
Lline: 1010,

I think it should be
`if (channel->mNumScalingKeys > 0)`
rather than
`if (channel->mScalingKey > 0)`

i wasn't able to built before changing the code as I mentioned above.

OS: macOs High Sierra

**Comment by mattbenic** [comment]
Nice catch :) Please PR that change. We're currently working on getting CI up and running again, as soon as that's done we'll be able to test and merge your PR

**Comment by mikailcolak** [comment]
I have created a new pull request about this bug.

Have a nice coding.

**Comment by mattbenic** [comment]
Thanks :)

**Comment by mikailcolak** [comment]
👍  :)
