### ISSUE TITLE
NPM atomic-cli get free key website is not working

### ISSUE THREAD

**Issue by Rishanthakumar** [AtomicGameEngine/AtomicGameEngine#1676]
When i activate atomic using the below command,
`atomic-cli activate`
This is what i get:
![screen shot 2017-12-15 at 3 08 49 pm](https://user-images.githubusercontent.com/13392302/34036020-ed9de204-e1a9-11e7-9ae0-61f81d132f1d.png)

**Comment by mattbenic** [comment]
A key is no longer needed. If you build the latest version from source you'll be able to use it freely.
