### ISSUE TITLE
Multiplayer Game

### ISSUE THREAD

**Issue by mikrokode** [AtomicGameEngine/AtomicGameEngine#1689]
Hi Friend,

Can you give me some ideas how to develop a Multiplayer Game using Atomic Game Engine? Or can you post an simple example of 3D Multiplayer Game in the example?

**Comment by mattbenic** [comment]
There is a multiplayer example in the AtomicEcamples repository: https://github.com/AtomicGameEngine/AtomicExamples

I'm not sure when last it was maintained.
