### ISSUE TITLE
JSComponent in inspector should display component title

### ISSUE THREAD

**Issue by shaddockh** [AtomicGameEngine/AtomicGameEngine#177]
Instead of the drawer in the inspector being titled "JSComponent", it seems like it should display either the full path or just the bare filename of the component file it references.  Maybe: "Enemy (js)" or "JSComponent - Enemy". If you get multiple JSComponents attached to a node, you don't know which is which when the drawers are closed.

**Comment by JoshEngebretson** [comment]
Ok, will be live once https://github.com/AtomicGameEngine/AtomicGameEngine/pull/187 lands

<img width="326" alt="screen shot 2015-08-12 at 12 50 42 pm" src="https://cloud.githubusercontent.com/assets/376203/9235000/02204fc0-40f1-11e5-9719-a1c8ea45edfb.png">

**Comment by shaddockh** [comment]
It appears that this fix is no longer working.  Re-opening.
