### ISSUE TITLE
The search bar doesn't seem to do anything

### ISSUE THREAD

**Issue by PauloVilela** [AtomicGameEngine/AtomicGameEngine#195]

**Comment by raheelx** [comment]
Hi @JoshEngebretson, I started working on this. I'm just doing some final testing and I should be able to send it through to you by tomorrow

**Comment by JoshEngebretson** [comment]
Hey @raheelx, that's great.  Looking forward to your implementation.  TurboBadger has some basic filtering for lists, not sure if that stuff is helpful to you.  I do know there are a couple inefficiencies with it.  THANKS!

**Comment by raheelx** [comment]
Okay I did create a search algorithm in the typescript but I'll have a look at the TurboBadger filtering when I get back to the office :) @JoshEngebretson

**Comment by JoshEngebretson** [comment]
Closing via #734, thanks to @raheelx
