### ISSUE TITLE
Cant build using Visual Studio 2013 , Windows 8.1 64 bits.

### ISSUE THREAD

**Issue by Murii** [AtomicGameEngine/AtomicGameEngine#2]
http://pastebin.com/n7jYgfbg

**Comment by JoshEngebretson** [comment]
Hello,

We're still getting setup here, though it looks like you need to generate the Javascript bindings.  Build the JSBind executable first, then run it passing the absolute path to the local root repo folder as an argument.

Please note, you will need a product key to run the editor and there are additional setup requirements which will be addressed in the next couple weeks.

**Comment by Murii** [comment]
So the engine is not ready to be used?

**Comment by JoshEngebretson** [comment]
Not quite yet, we're working to get early access builds available within a couple weeks.  Stay tuned! :)

**Comment by JoshEngebretson** [comment]
Please try building using these instructions: https://github.com/AtomicGameEngine/AtomicGameEngine/wiki/Building-the-Atomic-Editor-using-Visual-Studio-2013

**Comment by JoshEngebretson** [comment]
Closing, please report any build problems with the new setup to: http://atomicgameengine.com/forum/#/discussion/23/building-the-atomic-editor-from-source
