### ISSUE TITLE
Close Player Output window when player quits

### ISSUE THREAD

**Issue by LaraEngebretson** [AtomicGameEngine/AtomicGameEngine#215]
After running a project in the Player, a window opens with player output. This window has to be closed every time.

Issue originally reported here: #159

**Comment by rsredsq** [comment]
I'm not sure if it should be moved to the console, because in the release build console doesn't exists, so all errors and debug information goes into that window. Maybe there's should be added a button to  open it window manually, and checkbox if it should be closed as soon as Player closed

**Comment by JoshEngebretson** [comment]
This is a usability issue which should be addressed, adding to Build 2, some design required

**Comment by JoshEngebretson** [comment]
Add a checkbox that controls whether to close at stop (default is on) and a pref to make setting persistent
Add a note to output UI about logs available in the main frame menu (Editor/Player)
Eventually, this needs to go out to a log subwindow or something)

**Comment by JimMarlowe** [comment]
Where would you want this checkbox? in a menu (which one)?

**Comment by JoshEngebretson** [comment]
The checkbox could go in the player output window, which would make it obvious and handy... the player output window is most definitely a temporary solution and this is a good bandaid :)

**Comment by JimMarlowe** [comment]
How is this for the layout? Everything is flexible, since it's in a .tb.txt file.
![playeroutputlayout](https://cloud.githubusercontent.com/assets/19511757/20643808/dd1bef86-b3d6-11e6-82b0-482858c936d6.png)

**Comment by JoshEngebretson** [comment]
That looks great, we could probably bump the close button in size a bit, in both directions, and a point or 2 bigger font?  What do you think?  I am also thinking it should auto close if you hit play again, one of the weird things is that you get Player Output windows stacked up if you hit play a few times without closing them.

**Comment by JimMarlowe** [comment]
Yes, I'll remove an old player output log when a new one is started.
![playeroutputlayout1](https://cloud.githubusercontent.com/assets/19511757/20643914/2579fc8e-b3da-11e6-9bdc-aae53666fa76.png)

**Comment by JoshEngebretson** [comment]
Looking good 👍

**Comment by JoshEngebretson** [comment]
Closed via #1207, thanks @JimMarlowe
