### ISSUE TITLE
Support key layouts on non-QWERTY keyboards

### ISSUE THREAD

**Issue by LaraEngebretson** [AtomicGameEngine/AtomicGameEngine#217]
i.e. Camera/scene movement using WASD doesn't work well on non-QWERTY keyboards. 

Possible fixes: change to arrow keys and/or allow users to map keys

Issue originally reported here: #159

**Comment by rosshadden** [comment]
:+1:

**Comment by Type1J** [comment]
Use scan code instead of character value?

**Comment by Alan-FGR** [comment]
What scan codes have to do with this? They're not related to the physical key position in any way, the easy solution here is just to allow key customization.
