### ISSUE TITLE
Light2D Example crashes windows

### ISSUE THREAD

**Issue by JoshEngebretson** [AtomicGameEngine/AtomicGameEngine#227]
AtomicEditor.exe!heap_alloc_dbg_internal(const unsigned int size, const int block_use, const char * const file_name, const int line_number)Строка 359    C++
     AtomicEditor.exe!heap_alloc_dbg(const unsigned int size, const int block_use, const char * const file_name, const int line_number)Строка 450    C++
     AtomicEditor.exe!_malloc_dbg(unsigned int size, int block_use, const char * file_name, int line_number)Строка 491    C++
     [Внешний код]    
     AtomicEditor.exe!Atomic::VectorBase::AllocateBuffer(unsigned int size)Строка 34    C++
     AtomicEditor.exe!Atomic::Vector<Atomic::Vertex2D>::Resize(unsigned int newSize, const Atomic::Vertex2D * src)Строка 439    C++
     AtomicEditor.exe!Atomic::Vector<Atomic::Vertex2D>::Push(const Atomic::Vector<Atomic::Vertex2D> & vector)Строка 176    C++
     AtomicEditor.exe!Atomic::Vector<Atomic::Vertex2D>::operator+=(const Atomic::Vector<Atomic::Vertex2D> & rhs)Строка 91    C++
     AtomicEditor.exe!Atomic::Light2D::AddVertices(Atomic::Vector<Atomic::Vertex2D> & vertices)Строка 110    C++
     AtomicEditor.exe!Atomic::Light2DGroup::UpdateSourceBatches()Строка 648    C++
     AtomicEditor.exe!Atomic::Drawable2D::GetSourceBatches()Строка 100    C++
     AtomicEditor.exe!Atomic::Renderer2D::UpdateViewBatchInfo(Atomic::ViewBatchInfo2D & viewBatchInfo, Atomic::Camera * camera)Строка 444    C++
     AtomicEditor.exe!Atomic::Renderer2D::HandleBeginViewUpdate(Atomic::StringHash eventType, Atomic::HashMap<Atomic::StringHash,Atomic::Variant> & eventData)Строка 394    C++
     AtomicEditor.exe!Atomic::EventHandlerImpl<Atomic::Renderer2D>::Invoke(Atomic::HashMap<Atomic::StringHash,Atomic::Variant> & eventData)Строка 282    C++
     AtomicEditor.exe!Atomic::Object::OnEvent(Atomic::Object * sender, Atomic::StringHash eventType, Atomic::HashMap<Atomic::StringHash,Atomic::Variant> & eventData)Строка 81    C++
     AtomicEditor.exe!Atomic::Object::SendEvent(Atomic::StringHash eventType, Atomic::HashMap<Atomic::StringHash,Atomic::Variant> & eventData)Строка 289    C++
     AtomicEditor.exe!Atomic::View::Update(const Atomic::FrameInfo & frame)Строка 520    C++
     AtomicEditor.exe!Atomic::Renderer::Update(float timeStep)Строка 632    C++
     AtomicEditor.exe!Atomic::Renderer::HandleRenderUpdate(Atomic::StringHash eventType, Atomic::HashMap<Atomic::StringHash,Atomic::Variant> & eventData)Строка 1747    C++
     AtomicEditor.exe!Atomic::EventHandlerImpl<Atomic::Renderer>::Invoke(Atomic::HashMap<Atomic::StringHash,Atomic::Variant> & eventData)Строка 282    C++
     AtomicEditor.exe!Atomic::Object::OnEvent(Atomic::Object * sender, Atomic::StringHash eventType, Atomic::HashMap<Atomic::StringHash,Atomic::Variant> & eventData)Строка 81    C++
     AtomicEditor.exe!Atomic::Object::SendEvent(Atomic::StringHash eventType, Atomic::HashMap<Atomic::StringHash,Atomic::Variant> & eventData)Строка 289    C++
     AtomicEditor.exe!Atomic::Engine::Update()Строка 663    C++
     AtomicEditor.exe!Atomic::Engine::RunFrame()Строка 460    C++
     AtomicEditor.exe!Atomic::Application::Run()Строка 87    C++
     AtomicEditor.exe!RunPlayerApplication()Строка 29    C++
     AtomicEditor.exe!main(int argc, char * * argv)Строка 118    C++

**Comment by LaraEngebretson** [comment]
Fixed in #228.
