### ISSUE TITLE
NPM installable Atomic CLI

### ISSUE THREAD

**Issue by JoshEngebretson** [AtomicGameEngine/AtomicGameEngine#26]
It should be possible to create atomic projects, compile, and run them on device via a NPM installable Atomic CLI interface

**Comment by Type1J** [comment]
Can the command be shortened to just "atomic" instead of "atomic-cli" in the first working version?

**Comment by JoshEngebretson** [comment]
I went with atomic-cli as it would be less likely to conflict with other command line tooling.  

The NPM package needs some attention.  It is also my first stab at a NPM package and it seems to take a lot of time to untar the binaries especially on windows, so maybe needs a better system there.  I just liked that we were able to host the binaries with versioning, without having package limits applied.

**Comment by rosshadden** [comment]
I'm not really sure how to use the cli.  It seems to have remnants of the old activation workflow, as it has `activate` and `deactivate`.  I ran `atomic-cli activate` and got the following:

```
Please confirm EULA agreement (Y)es, (N)o, or (V)iew (Y) y
Please enter Product Key or (G)et free key:  g
Opening Atomic Store in default browser window
```
The url opened was an error page.

More importantly, nothing except `help` and `version` seem to work.  I get errors like this when trying `edit` and `deactivate`, respectively:

```
/home/ross/local/lib/node_modules/atomic-cli/lib/atomiceditor.js:19
  var child = spawn(platform_cli.ATOMICEDITOR_APP, flags, opts);
                                ^

TypeError: Cannot read property 'ATOMICEDITOR_APP' of undefined
```

```
/home/ross/local/lib/node_modules/atomic-cli/lib/atomictool.js:110
    flags.unshift(platform_cli.ATOMICEDITOR_DATADIR);
                              ^

TypeError: Cannot read property 'ATOMICEDITOR_DATADIR' of undefined
```

Also just a side question... why isn't the cli a separate repo?  The organization of it is really confusing, and I still can't find the source for it after about an hour of looking.
