### ISSUE TITLE
Event data exists only inside of callback

### ISSUE THREAD

**Issue by rsredsq** [AtomicGameEngine/AtomicGameEngine#274]
If we apply our event data to another variable inside of an our component, so it's became lost.
Here's exmplanation in code:
```JavaScript
"atomic component";

exports.component = function(self) {
  self.start = function() {
    //subscribe to event that will produce a bug
    self.subscribeToEvent("Test", function(event) {
      //that's the line when we lose our event data
      self.testEvent = event;
      //it's fine because we access data directly
      console.log(event.test);
    });
    //send event with a data
    self.sendEvent("Test", {test: "It's a bug!"});
    //it's where we lost our event data, the event is exists, but everything that should contains (e.g. {test:" It's a bug!") is lost.
    //so we are accessing an undefined variable
    console.log(self.testEvent.test);
  }
}

```

**Comment by shaddockh** [comment]
I'm not sure if that event is running synchronously or not, but have you tried attempting to access that event data in a subsequent update cycle?  Or using the new setTimeout function to schedule accessing it later?

ie: 
```
setTimeout(function() {
   console.log(self.testEvent.test);
}, 1000);
```

**Comment by shaddockh** [comment]
nevermind, just tested it and that fails too.

**Comment by rsredsq** [comment]
I don't want/need use setTimeout function. Events emitted synchroniusly with atomic loop(as I know, check atomic sources) So, it's defenitly a bug in atomic event system, probably in the layer, which glues native and js code.

**Comment by JoshEngebretson** [comment]
The event object's properties are only valid during the event, there are 2 reasons for this:

1)  Duktape currently holds a reference for for all locals (including args) when a function contains a local closure:
https://github.com/AtomicGameEngine/AtomicGameEngine/blob/master/Source/AtomicJS/Javascript/JSEventHelper.cpp#L50

So, at the end of the send event the variant map is explicitly cleared.

2)  The event system must be high performance, so this allows an opportunity to reuse event objects

This needs to be documented, if you need to store event data, store the actual event properties locally and not the event object itself.

**Comment by rsredsq** [comment]
Ok, I think that I could clone an event object and then work with the copied one.

**Comment by rsredsq** [comment]
I will close that issue, because It's not a bug, It's a feature for high performance. That thing need to be documented
