### ISSUE TITLE
Evaluate procsky replacement

### ISSUE THREAD

**Issue by JoshEngebretson** [AtomicGameEngine/AtomicGameEngine#281]
https://github.com/carnalis/ProcSky

If this works on ES2, WebGL, and HLSL port isn't time consuming, replace current procsky

**Comment by JoshEngebretson** [comment]
This is now under a permissive license and should be rolled in

**Comment by Alan-FGR** [comment]
@mattbenic Once we have BGFX in there are at least 3 options we can choose from with varying levels of features and complexity. Including official snippet.
