### ISSUE TITLE
Expose TB WIDGET_STATE_DISABLED to script

### ISSUE THREAD

**Issue by shaddockh** [AtomicGameEngine/AtomicGameEngine#284]
This enum is necessary for UIWidget.setState(state, bool) to make sense.  Workaround is to hard code 1 instead.  Should be Atomic.UI_WIDGET_DISABLED or something similar.

**Comment by JoshEngebretson** [comment]
Good catch, bumping in priority

**Comment by JoshEngebretson** [comment]
Closed via https://github.com/AtomicGameEngine/AtomicGameEngine/pull/295
