### ISSUE TITLE
SendEvent - cannot pass complex data 

### ISSUE THREAD

**Issue by shaddockh** [AtomicGameEngine/AtomicGameEngine#286]
In sendEvent / subscribeToEvent it should be possible to pass complex data in the data packet.

It appears that sending basic data such as strings, ints, bools works, but sending arrays, object literals, and function callbacks doesn't pass through.

```
        eventTarget.sendEvent('complexData', {
            str: 'string',
            bool: true,
            arr: [1,2,3,4,5],
            obj: {
                name: 'obj'
            }
        });
```

I've put together a sample project that illustrates this at:
https://github.com/shaddockh/AtomicPlayground/tree/NEW-EDITOR/event_test

**Comment by JoshEngebretson** [comment]
The engine Object's event system is primarily intended to communicate with the native engine in an efficient manner.  Internally, that object literal is represented as a VariantMap, which is a hash table of Variants:

https://github.com/AtomicGameEngine/AtomicGameEngine/blob/master/Source/Atomic/Core/Variant.h#L179

It would be powerful to be able to include arrays, objects, functions in the event data primarily for interaction with other ECMAScript code.  However, this is quite complex.  One example of the complexity is in call above, we would have to keep the arr and obj properties from being GC'd somehow during the lifetime of the event.  They are converted to a VariantMap for use by the native side.

This is something to noodle on.

**Comment by shaddockh** [comment]
Sounds good.  I mainly wanted to document the behavior and provide a code example.

**Comment by JoshEngebretson** [comment]
I am going to close this, maybe could into a hints or cookbook in the wiki?

**Comment by shaddockh** [comment]
It appears that if you define an object that descends from Atomic.ScriptObject and try to pass that, the data comes through so I believe that could be a good workaround.
