### ISSUE TITLE
Enable 3D API on Web Build

### ISSUE THREAD

**Issue by JoshEngebretson** [AtomicGameEngine/AtomicGameEngine#292]
The current WebPlayer deployment is 2D only, add a 3D option (maybe need both for now until have discrete 2D/3D projects?)  Also, update the current version of Emscripten

**Comment by Type1J** [comment]
I just got a new Mac (the old one stopped working). I installed Emscripten from Homebrew. I ran the following commands (from the root of the repo) to get a successful build of the bitcode:

    cd ..                                                                              
    mkdir AtomicGameEngine-em
    cd AtomicGameEngine-em
    cmake ../AtomicGameEngine -DEMSCRIPTEN=1 -DATOMIC_BUILD_2D=1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../AtomicGameEngine/Build/CMake/Toolchains/emscripten.toolchain.cmake
    make -j4

So far, everything is fine. I then try to generate the .html and .js files with the following command:

    cd ./Source/AtomicPlayer/Application && mv ./AtomicPlayer ./AtomicPlayer.bc && emcc -O3 -s USE_PTHREADS=0 -s ASM_JS=1 -s VERBOSE=0 -s USE_SDL=2 -s TOTAL_MEMORY=134217728 -s AGGRESSIVE_VARIABLE_ELIMINATION=1 -s NO_EXIT_RUNTIME=1 ./AtomicPlayer.bc -o  ./AtomicPlayer.html

I think that that's what I'm supposed to do, but I keep getting the following error:

    Traceback (most recent call last):
      File "/usr/local/Cellar/emscripten/1.35.9/libexec/emcc", line 9, in <module>
        emcc.run()
      File "/usr/local/Cellar/emscripten/1.35.9/libexec/emcc.py", line 1333, in run
        final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
      File "/usr/local/Cellar/emscripten/1.35.9/libexec/tools/shared.py", line 1594, in emscripten
        call_emscripten(cmdline)
      File "/usr/local/Cellar/emscripten/1.35.9/libexec/emscripten.py", line 1315, in _main
        temp_files.run_and_clean(lambda: main(
      File "/usr/local/Cellar/emscripten/1.35.9/libexec/tools/tempfiles.py", line 64, in run_and_clean
        return func()
      File "/usr/local/Cellar/emscripten/1.35.9/libexec/emscripten.py", line 1321, in <lambda>
        DEBUG_CACHE=DEBUG_CACHE,
      File "/usr/local/Cellar/emscripten/1.35.9/libexec/emscripten.py", line 1219, in main
        temp_files=temp_files, DEBUG=DEBUG, DEBUG_CACHE=DEBUG_CACHE)
      File "/usr/local/Cellar/emscripten/1.35.9/libexec/emscripten.py", line 237, in emscript
        staticbump = metadata['staticBump']
    KeyError: 'staticBump'
    FAIL: Running the generated program failed!

Is this due to me doing something wrong, or is this, as you mentioned, a problem with Atomic being compiled with the current version of Emscripten?

**Comment by Type1J** [comment]
Nevermind, I don't think that brew set things up correctly. It gives me the same error for any .bc to .html/.js conversion

**Comment by Type1J** [comment]
Now that it's setup properly, I also don't get errors until the .bc to html conversion:

    emcc: warning: cannot represent a NaN literal '0x7fd9ff2c27c0' with custom bit pattern in NaN-canonicalizing JS engines (e.g. Firefox and Safari) without erasing bits!
    emcc: warning: cannot represent a NaN literal '0x7fd9ff2c27c0' with custom bit pattern in NaN-canonicalizing JS engines (e.g. Firefox and Safari) without erasing bits!
    emcc: warning: cannot represent a NaN literal '0x7fd9ff2c27c0' with custom bit pattern in NaN-canonicalizing JS engines (e.g. Firefox and Safari) without erasing bits!
    emcc: warning: cannot represent a NaN literal '0x7fd9ff2c27c0' with custom bit pattern in NaN-canonicalizing JS engines (e.g. Firefox and Safari) without erasing bits!
    emcc: warning: cannot represent a NaN literal '0x7fd9ff2c27c0' with custom bit pattern in NaN-canonicalizing JS engines (e.g. Firefox and Safari) without erasing bits!
    emcc: warning: cannot represent a NaN literal '0x7fd9ff2c27c0' with custom bit pattern in NaN-canonicalizing JS engines (e.g. Firefox and Safari) without erasing bits!
    warning: unresolved symbol: posix_spawn
    warning: unresolved symbol: posix_spawn_file_actions_init
    warning: unresolved symbol: _ZN6Atomic23jsb_package_atomic_initEPNS_4JSVME
    warning: unresolved symbol: posix_spawn_file_actions_destroy
    warning: unresolved symbol: _ZN6Atomic29jsb_package_atomicplayer_initEPNS_4JSVME
    warning: unresolved symbol: posix_spawn_file_actions_adddup2

I made the following changes to emscripten.toolchain.cmake to get it to work:

    diff --git a/Build/CMake/Toolchains/emscripten.toolchain.cmake b/Build/CMake/Toolchains/emscripten.toolchain.cmake
    index 5094d36..1b44592 100644
    --- a/Build/CMake/Toolchains/emscripten.toolchain.cmake
    +++ b/Build/CMake/Toolchains/emscripten.toolchain.cmake
    @@ -35,7 +35,12 @@ set (CMAKE_SYSTEM_NAME Linux)
     set (CMAKE_SYSTEM_VERSION 1)
    
     # specify the cross compiler
    +if (NOT EMSCRIPTEN_ROOT_PATH AND DEFINED ENV{EMSCRIPTEN})
    +    # Newer versions of Emscripten
    +    file (TO_CMAKE_PATH $ENV{EMSCRIPTEN} EMSCRIPTEN_ROOT_PATH)
    +endif ()
     if (NOT EMSCRIPTEN_ROOT_PATH AND DEFINED ENV{EMSCRIPTEN_ROOT_PATH})
    +    # Older versions of Emscripten
         file (TO_CMAKE_PATH $ENV{EMSCRIPTEN_ROOT_PATH} EMSCRIPTEN_ROOT_PATH)
     endif ()
     if (NOT EXISTS ${EMSCRIPTEN_ROOT_PATH}/emcc)

The newer SDKs require you to `source <path to script>/emsdk_env.sh` in your .profile or .bashrc to setup the SDK path, which makes an environment var called "EMSCRIPTEN" that the CMake toolchain file expects to be called "EMSCRIPTEN_ROOT_PATH". Applying the above patch fixes that part, and makes it so that we can get all the way to the .bc to .html part of the build.

I haven't looked into the pthreads references or missing Atomic symbols, yet.

**Comment by JoshEngebretson** [comment]
Hey @Type1J, I am seeing that Emscripten 1.35.9 is from  Nov 12, 2015, 1.35.23 is the newest 1.35.x release I am seeing... and there is a 1.36.0 release a couple weeks ago.

I have generally used the "incoming" branch from the GitHub repo when working with emscripten as it has historically been the "best" branch to do work with... though, this may be different now as emscripten stabilizes.  

The CI box needs to be updated (using 1.34.x), I did test the 2D web player this weekend from the latest binary release and it is running.

I am thinking of combining the 2D/3D code for a single player now, it doesn't save a ton of size when you factor in compression... also better distribution methods than a huge pile of JS are hopefully around the corner, *cough* Web Assembly *cough* :)

I'll see if I can duplicate these issues when I am looking at this, hopefully this week.

**Comment by JoshEngebretson** [comment]
I have a unified 2D/3D WebPlayer build using Emscripten 1.36.1 here, working on getting local web builds setup.  In the meantime: http://docs.atomicgameengine.com/WebPlayer/Roboman3D/

:)

**Comment by JoshEngebretson** [comment]
#688 introduces local development builds for the WebPlayer as well as enabling 2D and 3D support.

In order to get a WebPlayer build, first build a development version of the editor, for example:

1) ./CMake_XCode.sh
2) Open the generated XCode project and build, then make sure you can run from XCode
3) From the repo root, with a valid Emscripten environment setup: 
```
./Build/Mac/node/node ./Build/node_modules/jake/bin/cli.js -f ./Build/Scripts/Bootstrap.js build:web_player
```

This will build the AtomicPlayer JS and memory files, the copy them to ./Data/AtomicEditor/Deployment/Web

These files will be used when doing web player deployments from the local dev build of the editor.

**Comment by Type1J** [comment]
Wow. It works great! I tried on my iPhone (6 Plus iOS 9.2.1), and I wasn't expecting it to work, but it rendered the boxes!

Sure, it was about 5 fps, the floor texture was missing, and the player wasn't visible, but it ran in a -mobile- browser!

In Chrome and FireFox, it runs like native! I'd like to run a 3D benchmark. Is there a stock Atomic 3D benchmark?

Excellent work, Josh!

**Comment by JoshEngebretson** [comment]
Thanks :+1: 

There isn't currently a benchmark, however could enable profile view in the browser to compare to native speeds.

It would be better to test mobile browser with some 2D (note the platformer does a fair number of raycasts for shadows), and BunnyMark is a JSComponent per bunny so definitely doesn't test draw speeds),  or 3D that doesn't use realtime shadows + Bullet physics.
