### ISSUE TITLE
Add C++ example which doesn't require any Javascript

### ISSUE THREAD

**Issue by JoshEngebretson** [AtomicGameEngine/AtomicGameEngine#30]
It is possible to use Atomic as a C++ codebase and not use any Javascript, need an example showing this

**Comment by CTrauma** [comment]
+1 for this with c++11 features

**Comment by mopkrayz** [comment]
this should be a top priority to try to get c++ coders
you need 2 simple examples, 1 for 2d and 1 for 3d
without seeing c++ examples, its hard to buy the product

**Comment by Type1J** [comment]
I would agree. However, I had experience with Urho3D before coming to Atomic, and because Atomic is based on that engine, I know what Atomic can do.

Could the Urho3D examples be used as a starting point? I know that the UI code is different, but I think it's common code across the examples.

**Comment by JoshEngebretson** [comment]
Pure C++ feature examples are in the Atomic Example repo
