### ISSUE TITLE
Sky box doesn't work on android target

### ISSUE THREAD

**Issue by rsredsq** [AtomicGameEngine/AtomicGameEngine#310]

**Comment by JoshEngebretson** [comment]
Is this solely on Android?  Works on Desktop?

**Comment by rsredsq** [comment]
On desktop(windows) it works fine, on android there's no sky box, just a black box. 
![screenshot_2015-09-20-01-16-39](https://cloud.githubusercontent.com/assets/5163918/9978408/6342a598-5f35-11e5-840e-26cf6c98ac4f.png)

**Comment by Alan-FGR** [comment]
Just a guess - unsupported texture format/size/etc
