### ISSUE TITLE
Shadow artifacts on android target

### ISSUE THREAD

**Issue by rsredsq** [AtomicGameEngine/AtomicGameEngine#311]
Here's a screenshot from [ToonTown](https://github.com/AtomicGameEngine/AtomicExamples/tree/master/ToonTown) example.
Look at the roof
![screenshot_2015-09-20-21-50-18](https://cloud.githubusercontent.com/assets/5163918/9982427/ecbcce66-5fe4-11e5-9e22-879feaf60a41.png)

**Comment by LaraEngebretson** [comment]
This is occurring on iOS also, mostly during the daytime, and is especially noticeable on Roboman.

**Comment by Type1J** [comment]
There are a few other artifacts that happen on Android and iOS. The boat example doesn't reflect properly on iOS for example (I haven't tried it on Android, but it might happen there as well). There might be something going on with the render target (FBO) setup, but I'm just speculating.

**Comment by Alan-FGR** [comment]
This is most certainly a shadow biasing issue.
