### ISSUE TITLE
Windows editor crashes on nonexistent Android API refresh

### ISSUE THREAD

**Issue by MrMormon** [AtomicGameEngine/AtomicGameEngine#313]
Runtime context: Windows 10, community editor activated with free product key, Android Studio is not installed

Steps to reproduce: Create new 3D project (may work with any template or openable project), go to Build -> Build Settings -> Android -> (Android API) Refresh button

Result: editor crashes with WIndows dialog popup (program *.exe has stopped working - clicking Cancel exits)

Expected behavior: popup dialog/console message "I can't find any Android development tools with your setup, please accept my condolences.", or nothing

**Comment by standtall007** [comment]
It is because you need to specify the Android SDK path first :) like: "C:\Android\sdk" but you can click the Choose button to specify the location a little easier :) Hope this helps.

**Comment by MrMormon** [comment]
Android Studio is not installed, and since it's the community edition, I chose 3D over Android support. But it shouldn't crash.

**Comment by standtall007** [comment]
if you have installed the 3D add-on instead of Android, why are you then trying to choose Android? doesn't make sense :P

**Comment by MrMormon** [comment]
I was just curious what it would say? I dunno. :)

**Comment by standtall007** [comment]
oh okay :D

**Comment by JoshEngebretson** [comment]
Thanks for the report, we do need to address any case where the editor crashes.

**Comment by standtall007** [comment]
I didn't know for a fact it was a bug :P
but i can perfectly understand you Josh it wasn't my intentions to be to cruel i was just so tired when i wrote to Mr.Mormon and i apoligize to you Mr.Mormon for writing that way to you i am really sorry :)

**Comment by JoshEngebretson** [comment]
No worries, it is good to get all the details :)

**Comment by MrMormon** [comment]
That's fine, standtall007, I didn't interpret your comments as hostile.

**Comment by standtall007** [comment]
thanks to both of you :)

**Comment by MrMormon** [comment]
Um, hugs? :P

**Comment by standtall007** [comment]
Hey i'm no teletubby XD
