### ISSUE TITLE
Add more options for camera movement in scene view

### ISSUE THREAD

**Issue by LaraEngebretson** [AtomicGameEngine/AtomicGameEngine#314]
* orbit
* zoom
* translate up/down
* center camera on selection

**Comment by mattbenic** [comment]
Related request from artists:
*E/Q shortcuts to move camera down (E) and up (Q) in Y, as in editing packages and Unity.
*Shortcut to focus and zoom on an asset (F)
*Shortcuts for alternate camera views (FPS/Orbit)
*Support (and shortcuts) for Top, Bottom, Front, Back, Left, Right ortho views

**Comment by JoshEngebretson** [comment]
As of #431 

Q/E: Translate camera up/down
F: Frame Selection
Alt + Left Mouse - Orbit (once selection framed)
Alt + Middle Mouse - Move camera towards point ("Zoom")
X : Toggle World/Local gizmo axis mode

Split the *Support (and shortcuts) for Top, Bottom, Front, Back, Left, Right ortho views to separate ticket
