### ISSUE TITLE
Add a hover box to descriptions getting truncated in the Inspector panel

### ISSUE THREAD

**Issue by LaraEngebretson** [AtomicGameEngine/AtomicGameEngine#326]
If the text is too long it gets cut off. This prevents users from seeing the whole name/description of a setting. 

![textcutoff](https://cloud.githubusercontent.com/assets/722928/10177351/9282c5a6-66ae-11e5-8f80-348893de376f.png)

Originally reported in #159

**Comment by JoshEngebretson** [comment]
This probably requires tooltips which TurboBadger does not currently have, I wonder if we could manage these in the UI module without many/any TB modifications
