### ISSUE TITLE
Fix Quit button in Space Game example

### ISSUE THREAD

**Issue by LaraEngebretson** [AtomicGameEngine/AtomicGameEngine#339]
The Quit button does not work the same across all platforms. It works properly on desktop and Android, but is unresponsive on iOS.

**Comment by rsredsq** [comment]
https://github.com/AtomicGameEngine/AtomicGameEngine/blob/master/Source/Atomic/Engine/Engine.cpp#L554
Here's the cause of it. So, I think it's better to remove that button

**Comment by LaraEngebretson** [comment]
I will move this issue back over to the examples repo.
