### ISSUE TITLE
Physically Based Rendering Support

### ISSUE THREAD

**Issue by HeadClot** [AtomicGameEngine/AtomicGameEngine#34]
This is a feature request that I would like to see implemented into the atomic game engine.

I have linked an overview below for Artists as well as one for programmers. This should give you a general overview for what needs to be done and why it is beneficial to the engine.

PBR for Artists
https://www.youtube.com/watch?v=LNwMJeWFr0U

PBR for Programmers
http://blog.selfshadow.com/publications/s2013-shading-course/#course_content

Further reading - 
http://jmonkeyengine.org/299803/physically-based-rendering-part-one/
http://jmonkeyengine.org/300495/physically-based-rendering-part-two/
http://jmonkeyengine.org/301308/physically-based-rendering-part-3/

**Comment by benwolf** [comment]
Maybe this can be closed since Urho 1.6 is merged?

**Comment by JoshEngebretson** [comment]
Yup, thanks :)
