### ISSUE TITLE
UI Possible Crash

### ISSUE THREAD

**Issue by Type1J** [AtomicGameEngine/AtomicGameEngine#343]
I don't know if this is a bug or if I'm doing something wrong, but it's probably the latter.

I wanted to create a simple "Start Menu" as suggested by someone in the forum. I based the code off of the particles button example, I ran into a few problems:

 1. I cannot get the button to go into the bottom left corner.
 2. I get a crash when clicking the button. Sometimes it takes more than once before the crash happens, but it never seems to bring up the menu.

Here's the code. If it's correct, then there's a bug in the player's UI code. If it's not, then please let me know what I did wrong.

    'atomic component';
    
    //define font description style
    var fd = new Atomic.UIFontDescription();
    fd.id = "Vera";
    fd.size = 22;
    
    function createButton(self, text, event, layout) {
        //create UIButton element
        var button = new Atomic.UIButton();
        //set its text and font description style
        button.text = text;
        button.fontDescription = fd;
        //laying on the right side
        button.gravity = Atomic.UI_GRAVITY_LEFT | Atomic.UI_GRAVITY_BOTTOM;
    
        //create menu
        var menu = new Atomic.UIMenuWindow(button, "popup_menu");
    
        //create menu items
        var menuSource = new Atomic.UISelectItemSource();
        menuSource.addItem(new Atomic.UISelectItem("Blah", "blah"));
        menuSource.addItem(new Atomic.UISelectItem("An item", "anItem"));
        menuSource.addItem(new Atomic.UISelectItem("Another item", "anotherItem"));
        menuSource.addItem(new Atomic.UISelectItem("-"));
        menuSource.addItem(new Atomic.UISelectItem("An item after a break", "anItemAfterABreak"));
    
        //this event will be called when buttons is clicked
        button.onClick = function() {
    
            self.sendEvent(event);
            menu.show(menuSource, -1, -1);
            print("Showing menu");
    
        }
    
    
        //add button
        layout.addChild(button);
    
    }
    //UI component
    exports.component = function(self) {
    
        // root view
        self.uiView = new Atomic.UIView();
        // Create a layout, otherwise child widgets won't know how to size themselves
        // and would manually need to be sized
        var layout = new Atomic.UILayout();
        layout.rect = self.uiView.rect;
    
        layout.axis = Atomic.UI_AXIS_Y;
    
        layout.layoutPosition = Atomic.UI_LAYOUT_POSITION_GRAVITY;
        //add our layout
        self.uiView.addChild(layout);
        //create buttons
        createButton(self, "Start", "StartEvent", layout);
    
    }

**Comment by Type1J** [comment]
The crash is in
    bool TBMenuWindow::Show(TBSelectItemSource *source, const TBPopupAlignment &alignment, int initial_value)

The value of "this" is 0 (NULL), which is what caused the crash because m_select_list is referenced on the first line.

**Comment by Type1J** [comment]
This works now that I move the menu creation into the onClick(), but the crash still shouldn't happen, I think. The widget_ member should be checked. Here's the working version.

    'atomic component';
    
    //define font description style
    var fd = new Atomic.UIFontDescription();
    fd.id = "Vera";
    fd.size = 22;
    
    function createButton(self, text, event, layout) {
        //create UIButton element
        var button = new Atomic.UIButton();
        //set its text and font description style
        button.text = text;
        button.fontDescription = fd;
        //laying on the right side
        button.gravity = Atomic.UI_GRAVITY_LEFT | Atomic.UI_GRAVITY_BOTTOM;
    
        //create menu items
        var menuSource = new Atomic.UIMenuItemSource();
        menuSource.addItem(new Atomic.UIMenuItem("Blah", "blah"));
        menuSource.addItem(new Atomic.UIMenuItem("An item", "anItem"));
        menuSource.addItem(new Atomic.UIMenuItem("Another item", "anotherItem"));
        menuSource.addItem(new Atomic.UIMenuItem("-"));
        menuSource.addItem(new Atomic.UIMenuItem("An item after a break", "anItemAfterABreak"));
    
        //this event will be called when buttons is clicked
        button.onClick = function() {
    
            //create menu
            var menu = new Atomic.UIMenuWindow(button, "popup_menu");
        
            self.sendEvent(event);
            menu.show(menuSource, -1, -1);
            print("Showing menu");
    
        }
    
        //add button
        layout.addChild(button);
    
    }
    //UI component
    exports.component = function(self) {
    
        // root view
        self.uiView = new Atomic.UIView();
        // Create a layout, otherwise child widgets won't know how to size themselves
        // and would manually need to be sized
        var layout = new Atomic.UILayout();
        layout.rect = self.uiView.rect;
    
        layout.axis = Atomic.UI_AXIS_Y;
    
        layout.layoutPosition = Atomic.UI_LAYOUT_POSITION_GRAVITY;
        //add our layout
        self.uiView.addChild(layout);
        //create buttons
        createButton(self, "Start", "StartEvent", layout);
    
    }

Their may need to be a check in

    void UIMenuWindow::Show(UISelectItemSource* source, int x, int y)

to make sure that widget_ is not a NULL pointer before it calls Show() on it.

**Comment by Type1J** [comment]
I'd still like to know how to get that button in the bottom left corner, if anybody knows. (I'm repeating that here, so it doesn't get lost in the details above).

**Comment by JoshEngebretson** [comment]
Thanks for the report, I'll have to look into why the code position matters here.

Here's a snippet for getting the button in the lower left using the position/distribution controls, which depend on which axis the layout is using:

```javascript
    // Create a layout, otherwise child widgets won't know how to size themselves
    // and would manually need to be sized
    var layout = new Atomic.UILayout();
    layout.rect = self.uiView.rect;

    // we're laying out on the X axis so "position" controls top and bottom alignment
    layout.layoutPosition = Atomic.UI_LAYOUT_POSITION_RIGHT_BOTTOM;
    // while "distribution" handles the Y axis
    layout.layoutDistributionPosition = Atomic.UI_LAYOUT_DISTRIBUTION_POSITION_LEFT_TOP;    
    
    //add our layout    
    self.uiView.addChild(layout);
```

**Comment by Type1J** [comment]
Thanks! We'll keep this issue open until Show() get's a check and warning log message instead of a crash when it's used "incorrectly" as I did in the first listing.

Would you like me to make a pull request for it, or would you like to look into it? I'm not sure where the check and warning log message should actually be. It could be made earlier than where I'm suggesting, I think, even though where I'm suggesting should still prevent the crash.

**Comment by Type1J** [comment]
Also, the "break" (the "-" item) doesn't seem to be working the way that I thought that it would. It doesn't seem to show up at all. What should I do to add break lines in menus?

**Comment by JoshEngebretson** [comment]
Ok, the mystery of the missing "break" in a popup was a bit tricky to track down...

It turns out that the separator widget is specifying a skin which is used in the editor, but not in the player.  So, the separator doesn't show up.  I filed an issue:

https://github.com/AtomicGameEngine/AtomicGameEngine/issues/347

**Comment by Type1J** [comment]
Thanks! I was pretty sure that that was the way to add a break, but I was doubting myself after that not working. It's good to know that it just wasn't in the skin.
