### ISSUE TITLE
Player processes are not shut down when playing from editor

### ISSUE THREAD

**Issue by mattbenic** [AtomicGameEngine/AtomicGameEngine#349]
On Windows 7, a freshly built editor from commit 48ed8c5.
+Open Task Manager, observe there is a single AtomicEditor.exe instance running. 
+Open a project with a simple main.js that does not load any resources or scenes. 
+Press play and wait for the player window to open.
+Closing the player and console windows
+Observe in Task Manager that there is an additional AtomicEditor.exe process consuming 5-7MB,

Repeating the test, new processes will be spawned and leaked for each run.

**Comment by JoshEngebretson** [comment]
I believe this is fixed in the C# branch, it has to do with an IPC thread not ending so hanging the process.  I will verify.

**Comment by JoshEngebretson** [comment]
This should now be fixed on master
