### ISSUE TITLE
Axis gizmo remains visible when deleting a node in editor

### ISSUE THREAD

**Issue by mattbenic** [AtomicGameEngine/AtomicGameEngine#351]
In the editor, in a 3D scene:
+Create a new node
+Select the node so that the axis gizmo is at it's location
+Delete the node
+Note that the gizmo remains at the deleted node's position until something else is selected

**Comment by JoshEngebretson** [comment]
Closed via https://github.com/AtomicGameEngine/AtomicGameEngine/pull/367
