### ISSUE TITLE
node.getJSComponent needs an option to not recurse

### ISSUE THREAD

**Issue by shaddockh** [AtomicGameEngine/AtomicGameEngine#352]
Currently, node.getJSComponent will traverse child nodes for the provided component if the parent that it's called on does not contain that component.  The function needs to provide an optional recurse parameter to disallow this.  Ideally, the signature should match node.getComponent(name, recurse?)

**Comment by JoshEngebretson** [comment]
Closed via https://github.com/AtomicGameEngine/AtomicGameEngine/pull/368
