### ISSUE TITLE
Still uses Urho3D's software culling

### ISSUE THREAD

**Issue by MrMormon** [AtomicGameEngine/AtomicGameEngine#362]

**Comment by JoshEngebretson** [comment]
I am not entirely sure what this issue is regarding?

**Comment by MrMormon** [comment]
https://www.reddit.com/r/gamedev/comments/3mhuh0/atomic_game_engine_cjstypescripthaxe/cvh2r3t

**Comment by JoshEngebretson** [comment]
We have no plans to implement hardware based occlusion culling for now
