### ISSUE TITLE
Can't rename prefabs in Editor

### ISSUE THREAD

**Issue by mattbenic** [AtomicGameEngine/AtomicGameEngine#363]
It's not possible to rename prefabs in the editor, I'd suggest one (or all) of the following approaches:
1) When selecting a prefab, have the inspector show all details for- and components on it, as with an object in the scene editor. Allow it to be renamed in the inspector panel as with objects in the scene.
2) Add a right click context option to rename the prefab
3) When clicking on an already selected prefab, change it's name label into a textbox and allow it to be renamed that way

**Comment by mattbenic** [comment]
It seems prefabs also can't be moved by dragging them onto folders, this would be useful.

**Comment by JoshEngebretson** [comment]
I added support for renaming and moving prefabs (and other assets) in https://github.com/AtomicGameEngine/AtomicGameEngine/pull/366

There is a bare bones inspector view for Prefabs which can be used to rename.  It is also possible to right click and select rename on the context menu.  Dragging a prefab to another folder will place it in that folder.
