### ISSUE TITLE
Add shortcuts, unit locking and global/local transform for transform editing

### ISSUE THREAD

**Issue by mattbenic** [AtomicGameEngine/AtomicGameEngine#373]
Artist requests:
*Add shortcuts for toggling Translate/Rotate/Scaling modes (usually W/E/R)
*Ability to lock translation to multiples of a set of values or customizable value
*Ability to togle between global and local transform modification

**Comment by JoshEngebretson** [comment]
#400 adds support for:

* Shortcuts for toggling Translate/Rotate/Scaling modes (usually W/E/R)
* Ability to togle between global and local transform modification

I filed #398 for the ability to lock translation to multiples of a set of values or customizable value
