### ISSUE TITLE
Reimport/update models when they change on disk

### ISSUE THREAD

**Issue by mattbenic** [AtomicGameEngine/AtomicGameEngine#380]
Artist request:
*fbx's don't seem to update in viewport after changes

**Comment by JoshEngebretson** [comment]
Need to verify this is still the case and address, adding to Build 1

**Comment by JoshEngebretson** [comment]
@mattbenic  I just tested and fbx/blend models are both reimporting and updating in loaded scene when updated on disk.  Can this be verified as still an issue, from over a year ago, so quite possibly worked on since...

**Comment by JoshEngebretson** [comment]
I can move this to Build 2 if still an unknown or there are additional issues with the reload/reimport

**Comment by christoffersch** [comment]
On my build, Atomic automatically reimports models if changes are made to disk

**Comment by PauloVilela** [comment]
This issues seems to be fixed on our end so i think we can close this.

**Comment by JoshEngebretson** [comment]
Great, thanks, closing
