### ISSUE TITLE
Atomic Editor Windows installer uses NSIS which doesn't handle elevating to admin level for a folder which requires it

### ISSUE THREAD

**Issue by JoshEngebretson** [AtomicGameEngine/AtomicGameEngine#390]
If you run without admin, you can't write to C:\Program Files, etc

**Comment by standtall007** [comment]
there is this NSIS plugins : http://nsis.sourceforge.net/UAC_plug-in i don't know if you have tested it yet but if you have how was the turn-out?

**Comment by JoshEngebretson** [comment]
The installer no longer launches the editor, which is a common solution due to difficulties under Windows 7-10
