### ISSUE TITLE
In VS 2015 Access Violation on Present (D3D9)

### ISSUE THREAD

**Issue by Type1J** [AtomicGameEngine/AtomicGameEngine#447]
In D3D9Graphics.cpp on line 827:

            impl_->device_->Present(0, 0, 0, 0);

This line throws an access violation exception. If "break on access violation exceptions" are turned off in VS settings, then everything seems to work correctly.

**Comment by JoshEngebretson** [comment]
This is the first this has been reported, try updating your GPU drivers?  What is the access violation (impl_ and impl_->device_ are valid?)

**Comment by Type1J** [comment]
Yes, they are both valid. Also, if I continue without the "break on access violation" checked, everything seems to work correctly. I'll update the drivers and try again,

**Comment by Type1J** [comment]
@JoshEngebretson: There never should have been a question mark in your suggestion above. :-)

I'm sure that you'll be pleased to know that updating my GPU drivers fixed the problem. I had installed a few updates to Windows 8.1 recently because VS2015 wouldn't install without them. As a result, D3D9 apps worked, but if you attached a debugger, device->Present() threw, and caught (you never saw it) an access violation exception. Updating my GPU drivers stopped that from occurring.

I never tried a D3D11 or higher app, but I'd assume that someone might run into the same sort of problem after a series of updates. It's definitely something that should go in the Wiki at some point, so that a possible solution is available quickly to those who find themselves with this problem.

Fortunately, since you'd have to attach a debugger to see it, I don't think that anyone would run into this problem in a released game.
