### ISSUE TITLE
Closing files sometimes closes the project

### ISSUE THREAD

**Issue by LaraEngebretson** [AtomicGameEngine/AtomicGameEngine#455]
* It happens after making changes in the inspector
* The file doesn't show any unsaved changes
* Once it happens it affects all files in all projects until the editor is restarted

**Comment by JoshEngebretson** [comment]
@rsredsq Could this be related to the modified check when closing resource editors?

**Comment by rsredsq** [comment]
@LaraEngebretson could you please give more information? I can't really reproduce it

**Comment by LaraEngebretson** [comment]
I haven't pinpointed the exact steps to replicate this. I have noticed it happen on multiple occasions though and it's always after I have been making a lot of changes in the Inspector panel.

**Comment by LaraEngebretson** [comment]
I was able to replicate this behavior by doing the following: 

* Open ParticleEmitter3D example
* Open the Scene file
* Close the project
* Open Character Animation 3D example
* Open the Scene file
* Select Robo_01 in the Hierarchy
* Expand the AnimationController component
* Select Animation Resource (click ... next to Animation 0)
* Hit Cancel
* Close the scene file

**Comment by blueFireGames** [comment]
It also happens if no changes are made to the project.

Jason
