### ISSUE TITLE
Create a WebView component using the Chromium Embedded Framework

### ISSUE THREAD

**Issue by JoshEngebretson** [AtomicGameEngine/AtomicGameEngine#469]

**Comment by Type1J** [comment]
Since CEF is so platform specific (Windows, OSX, and Linux Desktop only) can there be a way to disable this one?

**Comment by JoshEngebretson** [comment]
Yes, it will be an optional build component.  There also needs to be a fallback to OS webview on Android/iOS

**Comment by Type1J** [comment]
Perhaps a good prototype for the API could be made with Emscripten and an iframe?

**Comment by JoshEngebretson** [comment]
Blast from the past! We've had this awhile 🐫 🚀
