### ISSUE TITLE
Provide a way to jump to objects referenced in the inspector 

### ISSUE THREAD

**Issue by mattbenic** [AtomicGameEngine/AtomicGameEngine#497]
For example when a static model is selected, clicking on the name of the applied material- or on a button next to the name of the material- exposes and highlights the material in the project hierarchy.

**Comment by JohnnyWahib** [comment]
Currently busy with this task specifically for the material inspector. I have added small buttons next to each of the texture buttons that fire off an event that the ProjectFrame.ts subscribes to, sending through the path of the asset selected, and highlighting the relative path in the project frame. I'm assuming we are going to use this for other items in the different inspectors (material,models etc) so we would probably need to implement a similar case for each eventually. Does this method seem alright or is there a better way to go about this that I've completely missed?

**Comment by raheelx** [comment]
Hi @JoshEngebretson :)

@JohnnyWahib and I have been working on this Material Referencer issue. So far we've got it to highlight the item in the Project Frame when it's clicked in the Material Inspector. The last issue we have with this is that the Project Frame needs to automatically scroll to and open the correct folder with the highlighted item. Do you by any chance have an example where you've done something similar to guide us?

**Comment by LaraEngebretson** [comment]
Closed by #664
