### ISSUE TITLE
Dialog to save unsaved changes for a scene shows twice

### ISSUE THREAD

**Issue by Sleaker** [AtomicGameEngine/AtomicGameEngine#512]
1. Open a scene in the editor (I'm using the base 3d example.)
2. make a change.
3. click the X to close the scene window.
4. 2 Save dialogs will pop to save the scene.

Expected: Only 1 dialog should prompt the user to save the scene.

**Comment by blueFireGames** [comment]
This also happens when modifying scripts and components as well.

Jason
