### ISSUE TITLE
Container nodes cannot be moved with editor widgets

### ISSUE THREAD

**Issue by mattbenic** [AtomicGameEngine/AtomicGameEngine#519]
In the scene editor, when a container node (a node with no components used to contain/group other objects) is selected the transform widgets are not displayed. It's often useful to be able to move/rotate/scale objects as a group. They can be manipulated like this by multi-selecting, but container nodes should also be usable for this.

**Comment by LaraEngebretson** [comment]
I think what's happening is the new node is being placed at 0,0,0 which given the position of child nodes will offset the gizmo, potentially well out of view. Node creation probably needs to be smarter :)

**Comment by JoshEngebretson** [comment]
Nodes without components do have gizmo's, when single selected I don't believe the children are taken into account for  the gizmo location.  I did just crate an empty node and did have a gizmo though

**Comment by JoshEngebretson** [comment]
It is also possible this was a deleted node, using the delete key works, however if you use right click context menu the node is still in the listview and wouldn't show a gizmo, addressing in #526

**Comment by JoshEngebretson** [comment]
I've added a ticket to create new nodes using the camera's current location instead of at the origin #568.  Between that and #526 this should be address, can reopen if not...
