### ISSUE TITLE
Support editing android sdk/ant paths manually in the Build Settings dialog

### ISSUE THREAD

**Issue by JoshEngebretson** [AtomicGameEngine/AtomicGameEngine#536]
Currently, the choose button must be used for settings to change, we should hook up the edit complete event to save the build settings if manually entered or pasted, as some paths can't be chosen, such as:  '/usr/local/Cellar/android-sdk'

https://github.com/AtomicGameEngine/AtomicGameEngine/blob/master/Script/AtomicEditor/ui/modal/build/platforms/AndroidSettingsWidget.ts#L65

**Comment by LaraEngebretson** [comment]
Closed by #893
