### ISSUE TITLE
Development Snapshot notification issues

### ISSUE THREAD

**Issue by LaraEngebretson** [AtomicGameEngine/AtomicGameEngine#554]
For every activation you return during a session, another confirmation window opens.

i.e. If I have reset activations 3 times, I have to click through this dialog 3 times.

![developmentsnapshotdialog](https://cloud.githubusercontent.com/assets/722928/12067249/83c6c58a-afab-11e5-9df9-dc3fb0092f5c.png)

**Comment by JoshEngebretson** [comment]
This should also be displayed only for dev snapshots and not on main site download

**Comment by JoshEngebretson** [comment]
I disabled the notification window in the upcoming PR for #575 until it can be addressed
