### ISSUE TITLE
Compiling on Linux

### ISSUE THREAD

**Issue by JoshuaBehrens** [AtomicGameEngine/AtomicGameEngine#56]
I currently try to compile the source on linux (Mint 17/Ubuntu 14.10) and I am documenting what is needed to compile on linux.

As far I have done following changes(and in this order) to succesfully build:
* *libCpuId* ```typedef redefinition with different types ('long' vs 'long long')```
I removed their definition(libcpuid_types.h) of int64_t as sys/types.h already has this type. 
* *TurboBadger* ```use of undeclared identifier 'nullptr'```
Definitely a missing -std=c++11. Added in the generated flags.make
* *Atomic/Graphics/* ```'d3d9.h' file not found```
I do not know why it was choosen to work on DirectX so I added a -DATOMIC_OPENGL in the corresponding flags.make.
* *Atomic/Environment/ProcSky.cpp* ```unknown type name 'uint8_t'```
I added the commented lines
```
#if defined(_MSC_VER)
#include "stdint.h"
// #else
// #include <stdint.h>
#endif
```
* *Several kNet header* ```error: unknown type name 'sockaddr_in'```
Add some points the ```#if defined(KNET_UNIX)``` seemed not the be taken although in the flags.make it is defined. So I changed to no condition.
* *JSBind/cplusplus* ```no template named 'unordered_map' in namespace 'std'; did you mean 'std::tr1::unordered_map'?``` and ```'auto' type specifier is a C++11 extension```
Added a missing -std=c++11 to the flags.make

But now I stuck at the following point: Linking CXX executable JSBind
It lacks on several linkings against the following libraries: 
* GL
* GLEW
* DL
* pthread
* rt

I tried to add these as CXX_FLAGS but it did not change anything. Same undefined reference errors on gl_\*, glew_\*, sem_\*, pthread_\*, dl_\*

Can anyone help me to fix these linkings?

FYI: I am not used to configure cmake makefiles so I do not know whether I change things at the right point. C(++) compiler is clang(++).

**Comment by Murii** [comment]
Linux would be cool!

**Comment by JoshEngebretson** [comment]
Ok, I got the Atomic Editor running on Ubuntu

You need these packages:
```
build-essential 
libx11-dev 
libxrandr-dev 
libasound2-dev 
libgl1-mesa-dev 
libglu1-mesa-dev 
libgtk-3-dev 
libcurl4-openssl-dev
```
First clone the example repo
```
git clone https://github.com/AtomicGameEngine/AtomicExamples
```
then clone the engine and compile it
```
git clone https://github.com/AtomicGameEngine/AtomicGameEngine
mkdir AtomicGameEngine-build
cd AtomicGameEngine-build
cmake ../AtomicGameEngine -DCMAKE_BUILD_TYPE=Release -DATOMIC_BUILD_2D=0 -DLINUX=1
make -j4
cd Source/AtomicEditor
./AtomicEditor
```
This should run the editor, now do a project open and navigate to the example you want to open.

![Atomic Linux](http://docs.atomicgameengine.com/forum_images/AtomicEditor_Linux.png)

**Comment by Murii** [comment]
I got these errors: 
In file included from /home/vlad/AtomicGameEngine/Build/Source/Generated/LINUX/Javascript/Modules/JSModuleAtomic3D.cpp:12:0:
/home/vlad/AtomicGameEngine/Source/Atomic/Atomic3D/Terrain.h:116:5: error: ‘SharedArrayPtr’ does not name a type
     SharedArrayPtr<float> GetHeightData() const { return heightData_; }
     ^
/home/vlad/AtomicGameEngine/Source/Atomic/Atomic3D/Terrain.h:184:5: error: ‘SharedArrayPtr’ does not name a type
     SharedArrayPtr<float> heightData_;
     ^
/home/vlad/AtomicGameEngine/Source/Atomic/Atomic3D/Terrain.h:186:5: error: ‘SharedArrayPtr’ does not name a type
     SharedArrayPtr<float> sourceHeightData_;
     ^
make[2]: *** [Source/AtomicJS/CMakeFiles/AtomicJS.dir/__/__/Build/Source/Generated/LINUX/Javascript/Modules/JSModuleAtomic3D.cpp.o] Error 1
make[1]: *** [Source/AtomicJS/CMakeFiles/AtomicJS.dir/all] Error 2
make: *** [all] Error 2

**Comment by JoshuaBehrens** [comment]
I made it with this quite easy to 100% BUT in the end I have a reference error (sorry this is in German "Nicht definierter Verweis auf" => "undefined reference"):

```
[100%] Building CXX object Source/AtomicEditor/CMakeFiles/AtomicEditor.dir/Source/Player/UIPlayer.cpp.o
Linking CXX executable AtomicEditor
CMakeFiles/AtomicEditor.dir/Source/Editors/ModelResourceEditor.cpp.o: In Funktion `AtomicEditor::ModelResourceEditor::OnEvent(tb::TBWidgetEvent const&)':
ModelResourceEditor.cpp:(.text+0x3e0): Nicht definierter Verweis auf `Atomic::AnimationController::PlayExclusive(Atomic::String const&, unsigned char, bool, float)'
ModelResourceEditor.cpp:(.text+0x5de): Nicht definierter Verweis auf `Atomic::AnimationController::PlayExclusive(Atomic::String const&, unsigned char, bool, float)'
ModelResourceEditor.cpp:(.text+0x83f): Nicht definierter Verweis auf `Atomic::AnimationController::PlayExclusive(Atomic::String const&, unsigned char, bool, float)'
ModelResourceEditor.cpp:(.text+0xa36): Nicht definierter Verweis auf `Atomic::AnimationController::PlayExclusive(Atomic::String const&, unsigned char, bool, float)'
ModelResourceEditor.cpp:(.text+0xc22): Nicht definierter Verweis auf `Atomic::AnimationController::PlayExclusive(Atomic::String const&, unsigned char, bool, float)'
CMakeFiles/AtomicEditor.dir/Source/Editors/ModelResourceEditor.cpp.o:ModelResourceEditor.cpp:(.text+0xe12): Weitere nicht definierte Verweise auf `Atomic::AnimationController::PlayExclusive(Atomic::String const&, unsigned char, bool, float)' folgen
CMakeFiles/AtomicEditor.dir/Source/Editors/ModelResourceEditor.cpp.o: In Funktion `AtomicEditor::ModelResourceEditor::ModelResourceEditor(Atomic::Context*, Atomic::String const&, tb::TBTabContainer*)':
ModelResourceEditor.cpp:(.text+0x21b8): Nicht definierter Verweis auf `Atomic::AnimatedModel::SetModel(Atomic::Model*, bool)'
ModelResourceEditor.cpp:(.text+0x23ed): Nicht definierter Verweis auf `Atomic::StaticModel::SetMaterial(Atomic::Material*)'
ModelResourceEditor.cpp:(.text+0x2665): Nicht definierter Verweis auf `Atomic::AnimationController::PlayExclusive(Atomic::String const&, unsigned char, bool, float)'
CMakeFiles/AtomicEditor.dir/Source/Editors/SceneEditor3D/Gizmo3D.cpp.o: In Funktion `AtomicEditor::Gizmo3D::Gizmo3D(Atomic::Context*)':
Gizmo3D.cpp:(.text+0x62e): Nicht definierter Verweis auf `Atomic::StaticModel::SetModel(Atomic::Model*)'
CMakeFiles/AtomicEditor.dir/Source/Editors/SceneEditor3D/Gizmo3D.cpp.o: In Funktion `AtomicEditor::Gizmo3D::Use()':
Gizmo3D.cpp:(.text+0x2f68): Nicht definierter Verweis auf `Atomic::StaticModel::SetMaterial(unsigned int, Atomic::Material*)'
Gizmo3D.cpp:(.text+0x3058): Nicht definierter Verweis auf `Atomic::StaticModel::SetMaterial(unsigned int, Atomic::Material*)'
Gizmo3D.cpp:(.text+0x3207): Nicht definierter Verweis auf `Atomic::StaticModel::SetMaterial(unsigned int, Atomic::Material*)'
CMakeFiles/AtomicEditor.dir/Source/Editors/SceneEditor3D/Gizmo3D.cpp.o: In Funktion `AtomicEditor::Gizmo3D::Position()':
Gizmo3D.cpp:(.text+0x3ed7): Nicht definierter Verweis auf `Atomic::StaticModel::SetModel(Atomic::Model*)'
Gizmo3D.cpp:(.text+0x412d): Nicht definierter Verweis auf `Atomic::StaticModel::SetModel(Atomic::Model*)'
Gizmo3D.cpp:(.text+0x436d): Nicht definierter Verweis auf `Atomic::StaticModel::SetModel(Atomic::Model*)'
CMakeFiles/AtomicEditor.dir/Source/AEApplication.cpp.o: In Funktion `AtomicEditor::AEApplication::Start()':
AEApplication.cpp:(.text+0x80): Nicht definierter Verweis auf `Atomic::RegisterEnvironmentLibrary(Atomic::Context*)'
CMakeFiles/AtomicEditor.dir/Source/Import/AEJSONSceneProcess.cpp.o: In Funktion `AtomicEditor::JSONSceneProcess::ProcessComponent(Atomic::Node*, AtomicEditor::JSONBoxCollider const*)':
AEJSONSceneProcess.cpp:(.text+0x26de): Nicht definierter Verweis auf `Atomic::CollisionShape::SetBox(Atomic::Vector3 const&, Atomic::Vector3 const&, Atomic::Quaternion const&)'
CMakeFiles/AtomicEditor.dir/Source/Import/AEJSONSceneProcess.cpp.o: In Funktion `AtomicEditor::JSONSceneProcess::ProcessComponent(Atomic::Node*, AtomicEditor::JSONMeshCollider const*)':
AEJSONSceneProcess.cpp:(.text+0x27ae): Nicht definierter Verweis auf `Atomic::CollisionShape::SetTriangleMesh(Atomic::Model*, unsigned int, Atomic::Vector3 const&, Atomic::Vector3 const&, Atomic::Quaternion const&)'
CMakeFiles/AtomicEditor.dir/Source/Import/AEJSONSceneProcess.cpp.o: In Funktion `AtomicEditor::JSONSceneProcess::ProcessComponent(Atomic::Node*, AtomicEditor::JSONRigidBody const*)':
AEJSONSceneProcess.cpp:(.text+0x28f6): Nicht definierter Verweis auf `Atomic::RigidBody::SetMass(float)'
CMakeFiles/AtomicEditor.dir/Source/Import/AEJSONSceneProcess.cpp.o: In Funktion `AtomicEditor::JSONSceneProcess::ProcessComponent(Atomic::Node*, AtomicEditor::JSONTerrain const*)':
AEJSONSceneProcess.cpp:(.text+0x2f80): Nicht definierter Verweis auf `Atomic::Terrain::SetHeightMap(Atomic::Image*)'
AEJSONSceneProcess.cpp:(.text+0x2f8b): Nicht definierter Verweis auf `Atomic::Terrain::SetMaterial(Atomic::Material*)'
AEJSONSceneProcess.cpp:(.text+0x2f98): Nicht definierter Verweis auf `Atomic::Terrain::SetSmoothing(bool)'
AEJSONSceneProcess.cpp:(.text+0x2fdd): Nicht definierter Verweis auf `Atomic::Terrain::SetSpacing(Atomic::Vector3 const&)'
AEJSONSceneProcess.cpp:(.text+0x30be): Nicht definierter Verweis auf `Atomic::RigidBody::SetCollisionLayer(unsigned int)'
AEJSONSceneProcess.cpp:(.text+0x30ce): Nicht definierter Verweis auf `Atomic::RigidBody::SetFriction(float)'
AEJSONSceneProcess.cpp:(.text+0x3108): Nicht definierter Verweis auf `Atomic::CollisionShape::SetTerrain(unsigned int)'
CMakeFiles/AtomicEditor.dir/Source/Import/AEJSONSceneProcess.cpp.o: In Funktion `AtomicEditor::JSONSceneProcess::ProcessComponent(Atomic::Node*, AtomicEditor::JSONMeshRenderer const*)':
AEJSONSceneProcess.cpp:(.text+0x47bd): Nicht definierter Verweis auf `Atomic::StaticModel::SetModel(Atomic::Model*)'
AEJSONSceneProcess.cpp:(.text+0x47ee): Nicht definierter Verweis auf `Atomic::StaticModel::SetMaterial(unsigned int, Atomic::Material*)'
CMakeFiles/AtomicEditor.dir/Source/Import/AEJSONSceneProcess.cpp.o: In Funktion `AtomicEditor::JSONSceneProcess::ProcessComponent(Atomic::Node*, AtomicEditor::JSONSkinnedMeshRenderer const*)':
AEJSONSceneProcess.cpp:(.text+0x4a8b): Nicht definierter Verweis auf `Atomic::AnimatedModel::SetModel(Atomic::Model*, bool)'
AEJSONSceneProcess.cpp:(.text+0x4abe): Nicht definierter Verweis auf `Atomic::StaticModel::SetMaterial(unsigned int, Atomic::Material*)'
CMakeFiles/AtomicEditor.dir/Source/Import/AEJSONSceneProcess.cpp.o: In Funktion `AtomicEditor::JSONSceneProcess::ProcessModels()':
AEJSONSceneProcess.cpp:(.text+0x4c14): Nicht definierter Verweis auf `Atomic::Model::Model(Atomic::Context*)'
AEJSONSceneProcess.cpp:(.text+0x5df7): Nicht definierter Verweis auf `Atomic::Model::SetNumGeometries(unsigned int)'
AEJSONSceneProcess.cpp:(.text+0x5f52): Nicht definierter Verweis auf `Atomic::Model::SetVertexBuffers(Atomic::Vector<Atomic::SharedPtr<Atomic::VertexBuffer> > const&, Atomic::PODVector<unsigned int> const&, Atomic::PODVector<unsigned int> const&)'
AEJSONSceneProcess.cpp:(.text+0x5f6c): Nicht definierter Verweis auf `Atomic::Model::SetIndexBuffers(Atomic::Vector<Atomic::SharedPtr<Atomic::IndexBuffer> > const&)'
AEJSONSceneProcess.cpp:(.text+0x6063): Nicht definierter Verweis auf `Atomic::Model::SetGeometryCenter(unsigned int, Atomic::Vector3 const&)'
AEJSONSceneProcess.cpp:(.text+0x6087): Nicht definierter Verweis auf `Atomic::Model::SetNumGeometryLodLevels(unsigned int, unsigned int)'
AEJSONSceneProcess.cpp:(.text+0x60a1): Nicht definierter Verweis auf `Atomic::Model::SetGeometry(unsigned int, unsigned int, Atomic::Geometry*)'
AEJSONSceneProcess.cpp:(.text+0x6292): Nicht definierter Verweis auf `Atomic::Model::SetBoundingBox(Atomic::BoundingBox const&)'
AEJSONSceneProcess.cpp:(.text+0x62af): Nicht definierter Verweis auf `Atomic::Skeleton::Skeleton()'
AEJSONSceneProcess.cpp:(.text+0x6d13): Nicht definierter Verweis auf `Atomic::Skeleton::SetRootBoneIndex(unsigned int)'
AEJSONSceneProcess.cpp:(.text+0x6d25): Nicht definierter Verweis auf `Atomic::Model::SetSkeleton(Atomic::Skeleton const&)'
AEJSONSceneProcess.cpp:(.text+0x6d32): Nicht definierter Verweis auf `Atomic::Skeleton::~Skeleton()'
AEJSONSceneProcess.cpp:(.text+0x7196): Nicht definierter Verweis auf `Atomic::Model::SetBoundingBox(Atomic::BoundingBox const&)'
AEJSONSceneProcess.cpp:(.text+0x7401): Nicht definierter Verweis auf `Atomic::Skeleton::~Skeleton()'
CMakeFiles/AtomicEditor.dir/Source/Import/AEJSONSceneProcess.cpp.o: In Funktion `AtomicEditor::JSONSceneProcess::ProcessComponent(Atomic::Node*, AtomicEditor::JSONAnimation const*)':
AEJSONSceneProcess.cpp:(.text+0x803b): Nicht definierter Verweis auf `Atomic::Animation::Animation(Atomic::Context*)'
AEJSONSceneProcess.cpp:(.text+0x8055): Nicht definierter Verweis auf `Atomic::Animation::SetAnimationName(Atomic::String const&)'
AEJSONSceneProcess.cpp:(.text+0x80a3): Nicht definierter Verweis auf `Atomic::Animation::SetLength(float)'
AEJSONSceneProcess.cpp:(.text+0x8a19): Nicht definierter Verweis auf `Atomic::Animation::SetTracks(Atomic::Vector<Atomic::AnimationTrack> const&)'
CMakeFiles/AtomicEditor.dir/Source/Import/AEJSONSceneProcess.cpp.o: In Funktion `AtomicEditor::JSONSceneProcess::ProcessNode(AtomicEditor::JSONNode const*, Atomic::Node*)':
AEJSONSceneProcess.cpp:(.text+0x92d0): Nicht definierter Verweis auf `Atomic::RigidBody::SetCollisionLayer(unsigned int)'
collect2: error: ld returned 1 exit status
make[2]: *** [Source/AtomicEditor/AtomicEditor] Fehler 1
make[1]: *** [Source/AtomicEditor/CMakeFiles/AtomicEditor.dir/all] Fehler 2
make: *** [all] Fehler 2
```

**Comment by JoshEngebretson** [comment]
@Murii I am not sure why you would be getting that compiler error

@JoshuaBehrens If you were compiling in a previous folder, I would suggest making a clean build folder.  If it fails to link with a clean build folder, try running the cmake command above again, if that works please let me know

**Comment by spacepluk** [comment]
@Murii Are you using clang? I couldn't build it with gcc.

**Comment by JoshEngebretson** [comment]
@spacepluk Hm, I built it with gcc 4.8.2, BTW were you able to launch the editor.  It would be great to have the sanity check :yum: 

```
-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.2
```

**Comment by spacepluk** [comment]
I used this on Arch Linux:

    gcc version 4.9.2 20150304 (prerelease) (GCC) 

I got some weird linking errors and couldn't finish the build.  I can try again later and send you the whole log if you're interested.

I didn't have any problems with clang 3.6.0, very cool BTW :)

**Comment by JoshuaBehrens** [comment]
Re-running cmake and and make made it work in the end. Btw in the first try I used clang, now it worked with gcc. Now I have a running activated AtomicEditor :) (emulating the 64bit one with wine did not let me active, just saying)

About the switches for cmake: It looks like I just can do 3D now, am I right? What about 2D?

**Comment by JoshuaBehrens** [comment]
Nvm I just testet everything. Testing a 3D project ends up weird, no physics, weird rotated world (also in the editor). But I guess this is some sort of protection for the 3D licensing stuff. All in all there two bugs I found: I have the windows Icon on the lower left:
![image](https://cloud.githubusercontent.com/assets/1133593/6998363/76176ccc-dbe0-11e4-95bb-057c1171a722.png)
And if I open a project the filedialog does not close and does not respond. When I want to open an other project it is usable again until I opened a project.

All in all it is working under linux.

**Comment by JoshEngebretson** [comment]
@JoshuaBehrens The windows logo means that Windows is the active platform.  You can switch platform to test specific game functionality in the editor player window (within platform limitations).  There isn't currently a Linux platform is this is pretty new.  The 3D issues wouldn't be due to any licensing.  These sound like GL issues, what video card do you have and what distro/version are you running?  We're probably going to have to stick with Ubuntu LTS for the "official" version.

The Linux build will need some work for building players to work.  I also noticed that keyboard text copy/paste wasn't working.  Right click and selecting paste from context menu did (for instance in the product key activation window).  We'll need to file these as issues.

**Comment by JoshuaBehrens** [comment]
I just restart the editor somehow it works now. No weird rotation, working physics. Everything fine in toontown. AFAIK is Mint 17 based on 14.04 (mine upgraded to 14.10). I will now create on any bugs I find new issues.

Still a compiling question: Is there in any way a ```make install```?

**Comment by CTrauma** [comment]
Was just trying to build on Ubuntu Vivid ( 15.04 ) and had problems with IPCUnix.cpp, looks like possibly some BSD/OSX specific stuff that might need an #ifdef for SO_NOSIGPIPE and libproc?

**Comment by JoshEngebretson** [comment]
The current development stuff isn't compiling on Linux, I defaulted the script_widgets branch so that anyone looking at repo sees there is activity :)

**Comment by CTrauma** [comment]
ok.. thanks for the info..

**Comment by TemlainDiv** [comment]
Hello, I did compile under Archlinux following JoshEngebretson's post and it works fine.
But trying to launch it throw :
ERROR: Could not find resource AtomicEditor/out/(Unknown Filename).js.map
(Unknown Filename) - Failed loading module: main.js - Line: -1

**Comment by axredneck** [comment]
> git clone https://github.com/AtomicGameEngine/AtomicGameEngine
maybe "git clone **--recursive** https://github.com/AtomicGameEngine/AtomicGameEngine"
am i wrong?
