### ISSUE TITLE
Web Request examples crash on exit

### ISSUE THREAD

**Issue by LaraEngebretson** [AtomicGameEngine/AtomicGameEngine#564]
The following examples crash when closing the player (Windows & OSX):

* WebRequestSimpleExample
* WebRequestHeadersExample

![webrequestcrash](https://cloud.githubusercontent.com/assets/722928/12152447/9e29179e-b469-11e5-8a2e-f9c1ab0c9ab9.png)

**Comment by JoshEngebretson** [comment]
Ok, looking into this so can include in dev snapshot
