### ISSUE TITLE
Prevent exclusive fullscreen mode when running the editor

### ISSUE THREAD

**Issue by LaraEngebretson** [AtomicGameEngine/AtomicGameEngine#576]
Steps to replicate:

* Open a project
* Alt-Enter to go fullscreen
* Press Play

![fullscreencrash](https://cloud.githubusercontent.com/assets/722928/12176134/cb1dc662-b51a-11e5-84ff-a2bbf7b53cd5.PNG)

**Comment by JoshEngebretson** [comment]
I do not believe exclusive fullscreen mode should be supported by the editor (though possibly should be supported by play mode), it will not play nicely with multiple top level windows, makes tabbing between applications difficult, etc.

As a follow up, we may want to support borderless fullscreen mode for editor (and almost certainly the editor's player mode)

**Comment by LaraEngebretson** [comment]
Closed by #703
