### ISSUE TITLE
Mac-Shortcuts under linux

### ISSUE THREAD

**Issue by JoshuaBehrens** [AtomicGameEngine/AtomicGameEngine#59]
![image](https://cloud.githubusercontent.com/assets/1133593/7002580/503324ca-dc4d-11e4-8e54-a46c23aa18e6.png)

These are my system stats: https://gist.github.com/JoshuaBehrens/8eaf6e0deba63194d0bd

**Comment by rsredsq** [comment]
After #128 it has platform check

**Comment by JoshEngebretson** [comment]
Thanks, closing!
