### ISSUE TITLE
Editor hangs when trying to open a project on OSX

### ISSUE THREAD

**Issue by Type1J** [AtomicGameEngine/AtomicGameEngine#590]
The editor will hang after the user selects a project to open from the native file dialog box (opened by the "Open" option from the "File" menu).

If the editor is then closed (or killed), and then relaunched, then the project can be correctly loaded from the "Recent Projects" list.

**Comment by JoshEngebretson** [comment]
This is a new one, though old'ish versions of OSX (10.8 or so) did have a problem.  What version of OSX is this and what XCode/SDK?  I will see if I can reproduce shortly

**Comment by Type1J** [comment]
OSX El Capitan 10.11.2
Xcode 7.2

This also happens when you use the "Open Project" button just above the "Recent Projects" list.

Atomic Editor git 2a3bbc33cbf794ca8acb6ee9aedc520e5695a327 (the latest at the time of writing)
I used the "CMake_XCode.sh" script to make the project, then built it in Xcode.

**Comment by JoshEngebretson** [comment]
This has tested out fine running 10.11.2 on a 2014 MBPro and 2011 iMac, and 10.10.5 on a 2011 MBAir

Do you know what GPU is in this box?  I am thinking it may have something to do with GL context switch and native file dialog.  

We did look into this earlier last year, though could only reproduce on I believe OSX 10.8 on circa 2009 MBPro (which when updated to 10.11 the problem went away).

This may or may not be related: 

https://github.com/mlabbe/nativefiledialog/issues/7

**Comment by Type1J** [comment]
The machine that has that problem has lowest GPU that you could get: Intel HD Graphics 3000 512 MB. It's a MacMini that I use for file sharing at home, and TimeMachine backup points. The Mac that I should be using for development (with an nVidia GPU) had its hard drive crash. I'm going to fix it soon.

I tried to open a project with the editor in full screen mode, and after pressing "Open" in the native file dialog, it seemed to stay where it was (when it should have disappeared), but flicker. I'm totally guessing, but I think that one of the frame buffers got the dialog's contents, and on a buffer flip, which was apparently still happening, it flipped between the polluted and unpolluted color buffers.

**Comment by JoshEngebretson** [comment]
That is interesting, the 2011 MBAir has a HD3000, though is running 10.10, now the tough decision, upgrade to 10.11 to see if can replicate, or leave on 10.10 for compatibility testing... :8ball:

**Comment by Type1J** [comment]
I'd get an external hard drive, and boot 10.11 from it. Hold down Option (Alt) when you boot (before the Apple chime), and you'll get a selection between the 2.

You can have both :smile:

**Comment by bitonator** [comment]
Same thing happening here...El Capitan on a Mac Mini late 2009 with NVIDIA GeForce 9400 256 MB

Looking at the AtomicEditor logs...the project is loading, but the UI isn't updating. I'm able to quit atomic without a Force Quit too. 

Thankfully, recent projects list gets updated, so I can open the project via that, after reopening Atomic

**Comment by JoshEngebretson** [comment]
I have never experienced this issue, think it may have something to do with GL context and GPU driver.  This was committed to the native file dialog repo recently, I think it may fix it.  Could you try it please? 

https://github.com/mlabbe/nativefiledialog/commit/6527087b1e6a37b7ea228bf79ec0f319c731b4aa

The relevant issue: https://github.com/mlabbe/nativefiledialog/issues/7

**Comment by JoshEngebretson** [comment]
A potential fix for this is on master via #1025
