### ISSUE TITLE
Zero length files cause player builds to quit

### ISSUE THREAD

**Issue by JoshEngebretson** [AtomicGameEngine/AtomicGameEngine#594]
Having zero length files such as .gitkeep in the project currently cause the player build to quit.  This needs to be confirmed and then whatever is causing the build to stop fixed, either by including the zero length file in the build (preferred) or if that causes significant issues, skipping the files.

**Comment by mattbenic** [comment]
Confirmed that including zero length files has no effect on building the player, or on the player running normally. Fixed in commit:
https://github.com/LumaDigital/AtomicGameEngine/commit/0184ea29a664773ed61f12fe8375f4a850329e8b
