### ISSUE TITLE
[Editor] Add support for list/array attributes and nested object attributes on components

### ISSUE THREAD

**Issue by mattbenic** [AtomicGameEngine/AtomicGameEngine#606]
Ability to have the inspector automatically display nested objects and lists of objects.  This is to allow us to expose more complex settings to the editor without using external json files.
Components should ideally be able to have attributes that are arrays or lists of a given type. Ideally support lists/arrays of nested types.

**Comment by JoshEngebretson** [comment]
I'm working on this one now, does touch a few things 😉   I'll make sure there's a C# example component with a serialized array/vector too

**Comment by mattbenic** [comment]
w00t!

**Comment by JoshEngebretson** [comment]
Ok, this is *mostly* done, was quite a bit of plumbing (and debugging)... I still need to hookup resource and node array types, also want to make it possible to specify a fixed size array in the inspector which will be preallocated (I filed #1395 and plan on addressing these asap)

The PR is landed and here: #1396 

It touched a lot of stuff, so please let me know if anything seems wonky.  I created a test for testing, checking this:

https://github.com/AtomicGameEngine/AtomicTests/tree/master/CSharpTests/InspectorVector

I'll have a stab at #1395 in the AM and see if can get at least resource arrays and maybe fixed size in, node arrays are something that needs looking into (gets into referencing nodes, shouldn't be terrible)

```csharp
[Inspector]
bool[] MyBoolArray;

[Inspector]
int[] MyIntArray;

[Inspector]
float[] MyFloatArray;

[Inspector]
string[] MyStringArray;

[Inspector]
Color[] MyColorArray;

[Inspector]
Vector2[] MyVector2Array;

[Inspector]
Vector3[] MyVector3Array;
```

Yields:

![vectorinspector](https://cloud.githubusercontent.com/assets/376203/22131998/1e3a9df4-de6c-11e6-8953-6fa9aeedbaca.png)

**Comment by JoshEngebretson** [comment]
I got both resource and fixed length arrays working this morning in #1397, going to take some debugging as almost certainly corner cases and interaction with things like multiple selection/prefab interaction, etc. 🎸

Example fields:

```csharp
[Inspector(ArraySize = 2)]
Model[] MyModelArray;

[Inspector(ArraySize = 2)]
Material[] MyMaterialArray;
```

Example usage:

```csharp
staticModel.Model = MyModelArray[0];
staticModel.Material = MyMaterialArray[0];
```

Example in inspector, note that that fixed arrays can't have their size modified and are preallocated to default values:

![fixedresourcearray](https://cloud.githubusercontent.com/assets/376203/22162859/3d5d6c40-df05-11e6-873f-dfab3d18f9a1.png)

**Comment by mattbenic** [comment]
Looking awesome :) We're nailing things down to capture promotional video of our new stuff, which will hopefully be done tomorrow or the next day. We definitely won't be trying to integrate anything risky until after that, but as soon as I can after being in masterI'll start pulling it in :)

**Comment by mattbenic** [comment]
And of course the first array I tried was dynamic length string arrays, and that broke :P

Other dynamic length arrays work, but string arrays aren't getting I've PR'd a change to the test repo that illustrates it.

**Comment by JoshEngebretson** [comment]
Hm, I tried dynamic length string arrays and wasn't able to replicate an issue, I've also updated the test with some values I set to make sure: https://github.com/AtomicGameEngine/AtomicTests/commit/0adbc66b0e87291905d946fe66ab74b6fa67e3f6

![dynamicstringarray](https://cloud.githubusercontent.com/assets/376203/22267037/0c29ba2c-e237-11e6-9385-2f4fb344da6a.png)

Any thoughts on how to replicate the issue?

**Comment by mattbenic** [comment]
This thing was 100% reproducible yesterday, both in the test app and in our project. Now I can't get it in the test project, I'll try it in our project again shortly. I tried with both the vanilla editor and our fork. Bizarre.

**Comment by JoshEngebretson** [comment]
No worries, could be a bug, could be something stale that was wedged in there, lemme know if you have any problems... and how the bullet testing goes, a lot of stuff, should be close! :)

**Comment by mattbenic** [comment]
Ok. We're on other stuff right now, so likely won't get to it today

**Comment by JoshEngebretson** [comment]
One thing that can bite you is if there are native code changes, and the native binary doesn't get refreshed in the project.  When adding/removing methods, the ordinals for the method overloads will change, and then the native method won't be found, this is good as you will immediately know your native binary is out of date.  

When working on native stuff (or updating) best to make sure the native dll being used is the right one, I think this can be streamlined, there is logic in there for generated solutions, we can look at the external solution case too.

This *might* be the case here, worth mentioning at least...

**Comment by mattbenic** [comment]
Yeah that's bitten us in the past. When swapping between editor repositories or branches, or when rebuilding the editor, we delete the AtomicNET directory in the project and regenerate.
