### ISSUE TITLE
"Reveal in Finder" should be something different depending on the platform

### ISSUE THREAD

**Issue by Type1J** [AtomicGameEngine/AtomicGameEngine#607]
Context menus on files in the editor have a menu item called "Reveal in Finder", which uses Finder on Mac, Explorer on Windows, and something else (Nautilus, GNOME Files, Dolphin, Thunar, etc.) on Linux (I haven't checked if it works on Linux).

I think a generic "Reveal in File Manager" could be used for Linux if a name can't be retrieved somehow (like if `xdg-mime query default inode/directory` doesn't work because xdg-utils isn't installed), but Windows certainly needs "Explorer" instead of "Finder".

**Comment by JoshEngebretson** [comment]
This treads into "localization" which is better done sooner than later...

**Comment by LaraEngebretson** [comment]
Closed by #651
