### ISSUE TITLE
TypeScript syntax highlighting

### ISSUE THREAD

**Issue by Type1J** [AtomicGameEngine/AtomicGameEngine#615]
Support for .ts files being colored as .js files are.

This issue is not blocked, but it's probably a low priority until after https://github.com/AtomicGameEngine/AtomicGameEngine/pull/614 is merged.

**Comment by JoshEngebretson** [comment]
The plan is to have the JS and TS editors use Ace via the new UIWebView: https://ace.c9.io/build/kitchen-sink.html

This support syntax highlighting out of the box, try the TS document.

**Comment by Type1J** [comment]
It looks nice.

**Comment by JoshEngebretson** [comment]
We now have TS syntax highlighting via the Ace code editor
