### ISSUE TITLE
Merge latest git version of DukTape for RegEx

### ISSUE THREAD

**Issue by Type1J** [AtomicGameEngine/AtomicGameEngine#616]
This should probably be a 2 part issue:

1. Verify that the latest git Version of DukTape can use The TypeScript compiler unmodified.

2. As the title suggests, merge DukTape.

Soft blocks https://github.com/AtomicGameEngine/AtomicGameEngine/pull/614

**Comment by JoshEngebretson** [comment]
I just pulled in Duktape 1.4 in #566, so updating to master should be pretty painless.  I'll see about doing this later today as probably easiest to test out the TS compiler in @shaddockh's #614 PR

**Comment by JoshEngebretson** [comment]
This is going through CI now as #617 , will do additional testing before landing on master as using the new Duktape configuration stuff (We use some performance sensitive configuration settings)

**Comment by JoshEngebretson** [comment]
Close via #617
