### ISSUE TITLE
Add editor loading bar for time expensive tasks

### ISSUE THREAD

**Issue by rsredsq** [AtomicGameEngine/AtomicGameEngine#621]
Editor need a loading bar which will indicate the process of the current task, because editor can be frozen because of importing model(for example), in debug mode we can see a log messages in console, but in realese, user may think that editor has just frozen.

**Comment by JoshEngebretson** [comment]
This is similar to #533 , maybe we need to identify these, one problem is that model import for example isn't threaded so will block UI.  I have been thinking model import should be a run as a subprocess, this would keep the editor process clean and make it easy to add progress spinners, etc

**Comment by rsredsq** [comment]
@JoshEngebretson sorry, I didn't find #533 was looking be keyword `loading bar`.
Yes, subprocess sounds great, it also will be helpful to add it in AtomicTool so it can be launched from command line for whatever reason

**Comment by rsredsq** [comment]
I'll close it due to it's a duplicate of #533
