### ISSUE TITLE
WebView: Fix font rendering artifacts in code editor on Windows

### ISSUE THREAD

**Issue by LaraEngebretson** [AtomicGameEngine/AtomicGameEngine#634]
This is running on an HD3000 GPU/DX9

![crunchytext](https://cloud.githubusercontent.com/assets/722928/12697792/c4ddb9fa-c740-11e5-9ecf-a355a72933f4.PNG)

**Comment by JoshEngebretson** [comment]
Fixed, D3D9 0.5 position offset issue
