### ISSUE TITLE
[Mac] Code editor is losing keystrokes when typing quickly

### ISSUE THREAD

**Issue by JoshEngebretson** [AtomicGameEngine/AtomicGameEngine#647]
This has been reported on OSX.  It is likely also an issue on Windows.  Need to track down exactly where keystrokes are being lost.

**Comment by Wobling** [comment]
Some quick testing on Windows didn't show this, just for confirmation.
I have experienced it on OSX However.

**Comment by shaddockh** [comment]
This seems to be fixed, just need @JoshEngebretson to verify and close.

**Comment by JoshEngebretson** [comment]
This has indeed been fixed in #739, @Wobling we need to update the binary download with this fix, once some current editor work stabilizes.  In the meantime, if you build from source the issue should be resolved
