### ISSUE TITLE
Removing Selected Materials/Textures

### ISSUE THREAD

**Issue by JustNukeIt** [AtomicGameEngine/AtomicGameEngine#660]
We cannot remove/delete asset after we assign one. (unless we opened it i a text editor)

Example: If we create a Normal Diffuse Material, then put a Texture in the diffuse field and a Texture into the normal. We cannot empty the normal field even when we change the Material to a simple Diffuse,

Having a X/Cross next to a texture or Materials or anything that allow us to choose a specific asset within our content to remove it

**Comment by raheelx** [comment]
on it :+1:

**Comment by LaraEngebretson** [comment]
Closed via PR #664

**Comment by raheelx** [comment]
Bug Found Here: Doesn't remove the texture from the xml file. I'll look into this asap.
