### ISSUE TITLE
Investigate TypeScript API doc generation with TypeDoc

### ISSUE THREAD

**Issue by JoshEngebretson** [AtomicGameEngine/AtomicGameEngine#668]
Once initial TS API doc generation is hooked up, can integrate with build so available in Atomic Editor binary distro.  The Atomic API is large enough this should be a "multi-page" project, if TypeDoc supports it.  If not, will probably need an alternative.

The minimal theme seems nice: http://typedoc.io/themes/minimal

**Comment by shaddockh** [comment]
It appears that Typedoc may have an option split documentation across multiple pages and allows search across them. http://typedoc.io/api/index.html is the api documentation for typedoc itself and it appears to be generated to multiple pages.  Looking at the configuration options, I'm not seeing anything that jumps out as a specific option to do this though so it will take some experimentation.

**Comment by shaddockh** [comment]
based upon this: http://typedoc.io/guides/themes.html
The default theme is multi-page.  The minimalist theme, however, is single page.

**Comment by JoshEngebretson** [comment]
I've been working on getting TypeDoc running against the Scripts folder, the version installed off npm uses tsc 1.6.2 which is problematic, it looks like TypeDoc master was updated to 1.7 a few months ago.  We may need to look into a more active fork: https://github.com/sebastian-lenz/typedoc/network
