### ISSUE TITLE
On OSX "AtomicEditor Helper" needs a different target name.

### ISSUE THREAD

**Issue by Type1J** [AtomicGameEngine/AtomicGameEngine#678]
While working on #625, I found that "AtomicEditor Helper" has a space in it, and that causes newer versions of CMake to give a warning. The target name should have no special characters because it's a CMake symbol (variable name). The output file name can still be "AtomicEditor Helper" with something like:

    set_target_properties(${CEF_HELPER_TARGET} PROPERTIES MACOSX_BUNDLE_BUNDLE_NAME “AtomicEditor Helper”)

Right now, "CEF_HELPER_TARGET" is used in a few other places as the bundle name, but this var should probably be split into "CEF_HELPER_BUNDLE_NAME" and "CEF_HELPER_TARGET". Otherwise, we get this:

    $ cmake -G "Xcode" ../AtomicGameEngine
    -- The C compiler identification is AppleClang 7.0.2.7000181
    -- The CXX compiler identification is AppleClang 7.0.2.7000181
    -- Check for working C compiler using: Xcode
    -- Check for working C compiler using: Xcode -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - failed
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler using: Xcode
    -- Check for working CXX compiler using: Xcode -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - failed
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- curl version=[7.40.0]
    -- Enabled features: SSL IPv6 unix-sockets libz
    -- Enabled protocols: HTTP HTTPS
    CMake Warning (dev) at Source/AtomicEditor/CMakeLists.txt:80 (add_executable):
      Policy CMP0037 is not set: Target names should not be reserved and should
      match a validity pattern.  Run "cmake --help-policy CMP0037" for policy
      details.  Use the cmake_policy command to set the policy and suppress this
      warning.
    
      The target name "AtomicEditor Helper" is reserved or not valid for certain
      CMake features, such as generator expressions, and may result in undefined
      behavior.
    This warning is for project developers.  Use -Wno-dev to suppress it.

    -- Configuring done
    -- Generating done

**Comment by JoshEngebretson** [comment]
Addressed this issue for now by using OLD policy on CMP0037 when under OSX with WebView enabled, as there are a number of CEF3 related scripts which need to be updated/changed

Closed via #685
