### ISSUE TITLE
Camera Movement in Viewport

### ISSUE THREAD

**Issue by JustNukeIt** [AtomicGameEngine/AtomicGameEngine#701]
Up and Down are reverse, Up should be E and Down should be Q.

**Comment by eugenegous** [comment]
Inverted camera vertical movement in our fork...
... commit 55b040b7e770aab52499a790c43e3544984c1125

**Comment by benwolf** [comment]
This can be closed Q goes down and E goes up in current version.

**Comment by JoshEngebretson** [comment]
Great, thanks for issue combing
