### ISSUE TITLE
fail to build on linux

### ISSUE THREAD

**Issue by glenfordwilliams** [AtomicGameEngine/AtomicGameEngine#709]
trying to build on arch linux fails 

```[ 97%] Building CXX object Source/ToolCore/CMakeFiles/ToolCore.dir/JSBind/cplusplus/ObjectiveCAtKeywords.cpp.o                                                                    
[ 97%] Building CXX object Source/ToolCore/CMakeFiles/ToolCore.dir/JSBind/cplusplus/CoreTypes.cpp.o                                                                               
[ 97%] Building CXX object Source/ToolCore/CMakeFiles/ToolCore.dir/JSBind/cplusplus/Lexer.cpp.o                                                                                   
[ 97%] Building CXX object Source/ToolCore/CMakeFiles/ToolCore.dir/JSBind/cplusplus/Symbol.cpp.o                                                                                  
[ 97%] Building CXX object Source/ToolCore/CMakeFiles/ToolCore.dir/JSBind/cplusplus/Scope.cpp.o                                                                                   
[ 97%] Building CXX object Source/ToolCore/CMakeFiles/ToolCore.dir/JSBind/cplusplus/ASTVisit.cpp.o                                                                                
[ 97%] Building CXX object Source/ToolCore/CMakeFiles/ToolCore.dir/JSBind/cplusplus/ASTPatternBuilder.cpp.o                                                                       
[ 97%] Building CXX object Source/ToolCore/CMakeFiles/ToolCore.dir/JSBind/cplusplus/Token.cpp.o                                                                                   
[ 97%] Building CXX object Source/ToolCore/CMakeFiles/ToolCore.dir/JSBind/cplusplus/Parser.cpp.o                                                                                  
[ 97%] Building CXX object Source/ToolCore/CMakeFiles/ToolCore.dir/JSBind/cplusplus/Bind.cpp.o                                                                                    
[ 97%] Building CXX object Source/ToolCore/CMakeFiles/ToolCore.dir/JSBind/cplusplus/TypeVisitor.cpp.o                                                                             
[ 97%] Building CXX object Source/ToolCore/CMakeFiles/ToolCore.dir/JSBind/CSharp/CSClassWriter.cpp.o                                                                              
[ 97%] Building CXX object Source/ToolCore/CMakeFiles/ToolCore.dir/JSBind/CSharp/CSFunctionWriter.cpp.o                                                                           
[ 97%] Building CXX object Source/ToolCore/CMakeFiles/ToolCore.dir/JSBind/CSharp/CSPackageWriter.cpp.o                                                                            
[ 97%] Building CXX object Source/ToolCore/CMakeFiles/ToolCore.dir/JSBind/CSharp/CSModuleWriter.cpp.o                                                                             
[ 97%] Building CXX object Source/ToolCore/CMakeFiles/ToolCore.dir/JSBind/CSharp/CSTypeHelper.cpp.o                                                                               
[ 97%] Building CXX object Source/ToolCore/CMakeFiles/ToolCore.dir/JSBind/JSBNameVisitor.cpp.o                                                                                    
[ 97%] Building CXX object Source/ToolCore/CMakeFiles/ToolCore.dir/JSBind/JSBFunctionWriter.cpp.o                                                                                 
[ 97%] Building CXX object Source/ToolCore/CMakeFiles/ToolCore.dir/JSBind/JSBTypeScript.cpp.o                                                                                     
[ 97%] Building CXX object Source/ToolCore/CMakeFiles/ToolCore.dir/NETTools/NETToolSystem.cpp.o                                                                                   
[ 97%] Building CXX object Source/ToolCore/CMakeFiles/ToolCore.dir/NETTools/NETProjectGen.cpp.o                                                                                   
[ 97%] Building CXX object Source/AtomicNET/NETRun/CMakeFiles/NETRun.dir/NETRunApp.cpp.o
[ 97%] Building CXX object Source/Tools/PackageTool/CMakeFiles/PackageTool.dir/PackageTool.cpp.o                                                                                  
[ 97%] Linking CXX executable NETRun
[ 97%] Linking CXX executable PackageTool
[ 97%] Built target PackageTool
[ 97%] Linking CXX static library libToolCore.a
[ 97%] Built target ToolCore
Scanning dependencies of target AtomicTool
[ 97%] Building CXX object Source/AtomicTool/CMakeFiles/AtomicTool.dir/AtomicTool.cpp.o
[ 98%] Linking CXX executable AtomicTool
../../AtomicJS/libAtomicJS.a(JSAtomic.cpp.o): In function `Atomic::jsapi_init_atomic(Atomic::JSVM*)':
JSAtomic.cpp:(.text+0xa2c): undefined reference to `Atomic::jsb_package_atomic_init(Atomic::JSVM*)'
../../AtomicPlayerJS/libAtomicPlayerJS.a(AtomicPlayerJS.cpp.o): In function `AtomicPlayer::jsapi_init_atomicplayer(Atomic::JSVM*)':
AtomicPlayerJS.cpp:(.text+0x24): undefined reference to `Atomic::jsb_package_atomicplayer_init(Atomic::JSVM*)'
collect2: error: ld returned 1 exit status
Source/AtomicPlayer/Application/CMakeFiles/AtomicPlayer.dir/build.make:125: recipe for target 'Source/AtomicPlayer/Application/AtomicPlayer' failed
make[2]: *** [Source/AtomicPlayer/Application/AtomicPlayer] Error 1
CMakeFiles/Makefile2:2061: recipe for target 'Source/AtomicPlayer/Application/CMakeFiles/AtomicPlayer.dir/all' failed
make[1]: *** [Source/AtomicPlayer/Application/CMakeFiles/AtomicPlayer.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 98%] Built target NETRun
[ 98%] Built target AtomicTool
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by Goddard** [comment]
+1

**Comment by ysblokje** [comment]
+1

Here's the culprit:
```
Source/AtomicJS/Javascript/JSAtomic.cpp:extern void jsb_package_atomic_init(JSVM* vm);
Source/AtomicJS/Javascript/JSAtomic.cpp:    jsb_package_atomic_init(vm);
```

**Comment by JoshEngebretson** [comment]
Hey guys!

Are you building with the ./Build_AtomicEditor.sh in the root folder, if not, you may need to run cmake a second time to pick up some of the generated script binding files

Please note that there may be issues on Linux currently with the CEF3 integration, we do have CI for the Linux build which is passing, and this is what the editor looks like running on Ubuntu :)

![atomiclinux](https://cloud.githubusercontent.com/assets/376203/13847919/d14b7844-ec0c-11e5-9d01-adb6eb423017.png)

**Comment by TiZ-EX1** [comment]
Is it possible to get pre-built binaries through CI?

**Comment by glenfordwilliams** [comment]
@JoshEngebretson  thanks that helped. first i tried building using creator and that was failing  then i switched to running cmake on the commandline and that failes as well

**Comment by CTrauma** [comment]
I think this has to do with this bug in chromium embedded https://bitbucket.org/chromiumembedded/cef/issues/1198 and if you copy the AtomicGameEngine/Submodules/CEF/Linux/Resources/icudtl.dat file to AtomicGameEngine/Artifacts/AtomicEditor it should solve the problem. Problem something the linux build script should do after linking AtomicEditor.

**Comment by guzzard** [comment]
I get the same error as in the first post when trying to build using QtCreator. Running CMake twice doesn't seem to help in my case?

**Comment by Type1J** [comment]
For anybody following this issue, @CTrauma has a fix for this problem in master. Please pull, and let us know your results.

**Comment by CTrauma** [comment]
FYI the fix should allow you to launch the editor, but I am still seeing some wonkyness with the editor in general because of issues with CEF and IPC calls to the player, so YMMV until those get ironed out, but I was able to load and run the basic 3d example on Ubuntu 15.10.

**Comment by Type1J** [comment]
Is anybody still not able to run the editor?

**Comment by CTrauma** [comment]
Just to confirm, did a clean build from latest sources on linux and was able to launch the editor without any issues..

**Comment by slapin** [comment]
I still getting this no matter how much I try:

../../AtomicJS/libAtomicJS.a(JSAtomic.cpp.o): In function `Atomic::jsapi_init_atomic(Atomic::JSVM*)':
JSAtomic.cpp:(.text+0xa2c): undefined reference to `Atomic::jsb_package_atomic_init(Atomic::JSVM*)'
../../AtomicPlayerJS/libAtomicPlayerJS.a(AtomicPlayerJS.cpp.o): In function `AtomicPlayer::jsapi_init_atomicplayer(Atomic::JSVM*)':
AtomicPlayerJS.cpp:(.text+0x24): undefined reference to `Atomic::jsb_package_atomicplayer_init(Atomic::JSVM*)'
collect2: error: ld returned 1 exit status
Source/AtomicPlayer/Application/CMakeFiles/AtomicPlayer.dir/build.make:126: recipe for target 'Source/AtomicPlayer/Application/AtomicPlayer' failed
make[2]: *** [Source/AtomicPlayer/Application/AtomicPlayer] Error 1
CMakeFiles/Makefile2:2120: recipe for target 'Source/AtomicPlayer/Application/CMakeFiles/AtomicPlayer.dir/all' failed
make[1]: *** [Source/AtomicPlayer/Application/CMakeFiles/AtomicPlayer.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

I did git clean -d -f -x in build dir
then do 
cmake . 
twice

Any ideas?

**Comment by guzzard** [comment]
Since https://github.com/AtomicGameEngine/AtomicGameEngine/pull/865 was merged I'm able to build with Qt Creator.

First make sure you have a fresh/synced clone of the github repo.

In Qt Creator
1. Build -> Run CMake
2. In Build Steps, select only "GenerateScriptBindings" as the target, and then build the project.
3. Build -> Run CMake again
4. In Build Steps, select "all" as the target, and then build the project.

Now the build should finish without errors.

**Comment by JoshEngebretson** [comment]
The build has been improved quite a bit since this was filed, please see https://qa.atomicgameengine.com/28/how-to-build-from-source-in-debug

Also, CMake_Linux.sh in the root generates a makefile which should build everything in one step.
