### ISSUE TITLE
[Linux] Gray overlay prevents me from interacting with the window

### ISSUE THREAD

**Issue by PaulBGD** [AtomicGameEngine/AtomicGameEngine#716]
After compiling it myself and running it, I get this gray overlay:
![Image](https://i.imgur.com/PDfI7pc.png)
I cannot interact with the window at all.

Here's my log: http://pastebin.com/arekEaPb

**Comment by PaulBGD** [comment]
Oh, here's my debug.log from the artifact's directory: http://pastebin.com/qFxenTPu

**Comment by libgradev** [comment]
Window manager hiding the licence agreement window perchance?

If WM=Awesome then; mod4+f

**Comment by TiZ-EX1** [comment]
Why is there a license agreement window anymore?

**Comment by PaulBGD** [comment]
I went ahead and cloned/rebuilt the project. The same thing occurs.

**Comment by PaulBGD** [comment]
Hey, is this solved?

**Comment by JoshEngebretson** [comment]
@PaulBGD There have been many updates since including a major SDL upgrade and the issue has never been replicated.  Please reopen if you are still seeing an issue.
