### ISSUE TITLE
Problems to build an Android Application

### ISSUE THREAD

**Issue by diemeslen0** [AtomicGameEngine/AtomicGameEngine#719]
When I download the first time the Atomic Engine, I opened an example 2D and tried to build for Android devices.

The error that happen was:

can't open my Android-Build/res/values/strings.xml 

The solution was:

1 - Enter in the /Applications/AtomicEditor.app/Contents/Resources/ToolData/Deployment/Android/res/values

2 - Create a xml file called strings.xml with the content above:

`<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="app_name">Atomic</string>
</resources>
`

Be happy.

I did all that in my MacOs, but if you have the same problem using Linux or Windows, I think it can help you too.

if for any reason your application doesn't have one of that directories, you can create it.

**Comment by Wobling** [comment]
Can confirm this fixed my android build issues.
I was getting build failed and no output on the build console.

**Comment by diemeslen0** [comment]
Hi Wobling,

Did you create the directories and files that was missing?

if not, please, do it and try to build again.

[]'s

**Comment by JoshEngebretson** [comment]
I'll get this fix on master today, thanks guys
