### ISSUE TITLE
[Win32]Player Behaves different on Debug and Release

### ISSUE THREAD

**Issue by popcade** [AtomicGameEngine/AtomicGameEngine#733]
From the post:
http://atomicgameengine.com/forum/#/discussion/212/my-method-to-build-win32-version-and-new-issue-with-win32-player

The Editor/Player exe can be successfully built, in Debug build things works well, however, if change the build mode to Release, when running Physics Platformer, the coin didn't disappear, they works like a crate or something, bounces when touch player without disappearing.

This issue should be able to produce by build from a existing project, if not, I can upload my executable.

**Comment by JoshEngebretson** [comment]
Hello, I was able to replicate this issue and will look into it.

**Comment by JoshEngebretson** [comment]
This should no longer be an issue, closing
