### ISSUE TITLE
Be able to configure ACE code windows with preferences file

### ISSUE THREAD

**Issue by shaddockh** [AtomicGameEngine/AtomicGameEngine#751]
There should be a way to configure the Ace editors via a user preferences.  This can initially be hand-modified in the file, but ideally it should be exposed through the editor ui.  This should be elements such as font size, theme, keybindings, etc.  Basically most of the settings that can be modified via the built in ACE configuration panel accessed via "CTRL/CMD + Comma"

**Comment by benwolf** [comment]
No longer valid for ACE, using Monaco now. Maybe rename for Monaco user prefs?

**Comment by shaddockh** [comment]
This can be closed.  The following explains how to configure the settings.  

https://qa.atomicgameengine.com/55/how-do-i-change-display-settings-for-the-code-editor

If new settings need to be exposed, a new issue should be opened.
