### ISSUE TITLE
Support external c/c++ code modules

### ISSUE THREAD

**Issue by mattbenic** [AtomicGameEngine/AtomicGameEngine#77]
Currently the only way to integrate new C/C++ code into a project using AtomicGameEngine is by adding it to a custom engine build. It would be very helpful to have support for dynamically included libraries.

From the current engine source, it appears the appropriate way to do this would be to modify JSVM::js_module_search to load .dll (/.so/whatever per deployment platform) libraries and register their exposed methods to the duk_context. 

Some challenges here:
*While there is extensive discussion of a simple "standard" dynamic library loader for duktape [here](https://github.com/svaarala/duktape/issues/52) it doesn't seem to be available yet. Would likely need to be implemented from scratch.
*library loading and exposing would need implementation per platform
*would not be able to support this in iOS, perhaps a different approach would be in order-maybe introducing a requirement for static lib versions that could then be linked against when building the player?
*Current editor distribution does not include any headers for such libraries to include. Could the build process be modified to include headers for such plugin libraries to be able to make use of Atomic objects

**Comment by JoshEngebretson** [comment]
"Current editor distribution does not include any headers for such libraries to include. Could the build process be modified to include headers for such plugin libraries to be able to make use of Atomic objects"

Just a really quick note on this, the Editor will launch a Atomic Player process moving forward when playing from editor.  We use IPC mechanisms to communicate with the player subprocess.  This means building custom features native side will be easier as won't have to be factored into the Editor binary and the editor process will be kept clean (no need to try and figure out how to dynamically unload your dll's, etc, which can be a real pain on some platforms.

If some native code can be factored into Atomic's Object model (there are many examples of wrapping third party API's in the engine sources), this is a real boon as JSBind will automatically generate wrappers and control native lifetime, etc.

We definitely need to be able to load native dll's interface with exposed C functions (FFI), it would also be good to be able to load up duktape modules with the correct duk_context* signatures.  The later implies that you are building these dll's from source.

**Comment by mattbenic** [comment]
"no need to try and figure out how to dynamically unload your dll's, etc, which can be a real pain on some platforms"
Been there O_O This is a pain point for us in Unity at the moment.

**Comment by mattbenic** [comment]
I've been reading up on this (I haven't had to do multiplatform/external dev friendly dynamic library loading before) and it looks like there are two different rabbitholes to jump down here: 

The one alternative is trying to get an existing solution working with atomic, something like dynobj (http://dynobj.sourceforge.net/) or xpcom (https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM). Given how far along your Module model is, I don't think these are the way to go, I only mention them because your approach so far seems to be to use existing libs where possible (which is great).

The other option is to ignore those, and dive into a custom built approach, with your existing Modules model and the duktape c module convention as a starting point. That's where I'm leaning at the moment, but just wanted to run it by you before starting on something that could end up being a fundamental part of the way Atomic is used :) 

Assuming you're ok with that, and don't have any concerns, I'll start coding on this tomorrow. If you want to have a chat about it before then, drop me a mail.
