### ISSUE TITLE
*.atomic not being populated for Atom.io

### ISSUE THREAD

**Issue by eugenegous** [AtomicGameEngine/AtomicGameEngine#78]
Tried integrating atom.io with Atomic Game Engine. Noticed an Issue when using the Atomic Game Engine Package

ERROR: Could not parse JSON data from *.atomic

The *.atomic project file doesn't get populated with:
{
   "version": 1,
   "project": {
      "version": "1.0.0"
   },
   "platforms": [
      "mac", "windows"
   ]
}
as in the example projects.

**Comment by JoshEngebretson** [comment]
Interesting, did you get the plugin to work?  The Atom.io plugin is pre-alpha and requires the atomic-cli NPM package, were you able to get the NPM package installed and activated?

https://www.npmjs.com/package/atomic-cli

If you're having problems, I would suggest using Sublime, Atom.io, VSCode and just add the project directory, then run from the Editor.  The CLI is definitely a WIP

- Josh

**Comment by JoshEngebretson** [comment]
Please have a look at this wiki page, it goes into setting up VSCode to run atomic projects from source (no building the project, etc).  The Atom.io package will be updated too, however this is pretty slick if you are on Windows :)

https://github.com/AtomicGameEngine/AtomicGameEngine/wiki/AtomicEditor-running-as-Player-and-VSCode

- Josh

**Comment by eugenegous** [comment]
Thanks Josh. Got it working before I added my observation above.

Just wanted to point out that it doesn't seem like *.atomic gets populated (on my side at least) with the JSON snippet I mentioned in the first post. - I had to manually add it.

Otherwise everything seems to be working fine in Atom.io - Looking very good considering it is pre-alpha :)

Good luck and thanks for all your effort.
