### ISSUE TITLE
Combined d.ts file is not working on windows builds

### ISSUE THREAD

**Issue by shaddockh** [AtomicGameEngine/AtomicGameEngine#783]

**Comment by shaddockh** [comment]
On windows builds, the current implementation of generating the d.ts file is breaking the build.  A fix is being tried and while it's not breaking the build anymore, it is only creating a 0 length file.

**Comment by JoshEngebretson** [comment]
Ok, I sent you a team invitation with write access to the Atomic and examples repositories so you can now land some PR's and stuff, if you're so inclined :zap:

**Comment by shaddockh** [comment]
That could be useful, thanks!  I'll be running the PRs by you first though.
