### ISSUE TITLE
Windows build reports missing files

### ISSUE THREAD

**Issue by mattbenic** [AtomicGameEngine/AtomicGameEngine#789]
Current windows build outputs the following:

jake aborted.
Error: Missing files
at api.fail (C:\development\AtomicGameEngine\Build\node_modules\jake\lib\api
.js:336:18)
at null.<anonymous> (C:\development\AtomicGameEngine\Build\node_modules\jake
\lib\utils\index.js:124:9)
(See full trace by running task with --trace)

The build does still appear to complete.

**Comment by shaddockh** [comment]
FYI, This is the same issue as #783 and should be resolved by #788.

**Comment by mattbenic** [comment]
Apologies. It does look like it's resolved in your 783 branch.
