### ISSUE TITLE
WebView.browserHost not getting generated in WebView.d.ts

### ISSUE THREAD

**Issue by shaddockh** [AtomicGameEngine/AtomicGameEngine#815]
It appears that the WebView.browserHost variable is not being emitted in the d.ts file.  This is located at the root of the namespace and not in an embedded class that gets parsed, so how can that be defined so that it gets picked up?   Would this require a custom WebViewWork.d.ts?

**Comment by JoshEngebretson** [comment]
I see the WebView issues though am pretty snowed under this week.  Are they blockers?  Hope you got your grill on over Memorial Day weekend :cow:

**Comment by shaddockh** [comment]
Nope, not a blocker. I just needed verification that it's just in need of a work.d.ts file or something in the code.  If it's a d.ts, I can put that fix in.  

Grilling was good!  Got two days of grilling in between the rains. :)

**Comment by shaddockh** [comment]
This is exposed now...closing.
