### ISSUE TITLE
Atomic 3D demo - going through trees.

### ISSUE THREAD

**Issue by PolywickStudio** [AtomicGameEngine/AtomicGameEngine#820]
Please put colliders on the trees, in the demo app

You can go through the trees and that is wrong.

**Comment by JoshEngebretson** [comment]
Hello, please use the AtomicExamples repository to post issues with examples:

https://github.com/AtomicGameEngine/AtomicExamples

Help is also welcome, feel free to add colliders to the scene and make a PR :)
