### ISSUE TITLE
Chrome dev tools no longer working with embedded web views

### ISSUE THREAD

**Issue by shaddockh** [AtomicGameEngine/AtomicGameEngine#832]
The latest version of Chrome no longer can connect to the embedded web view.  This is due to the version of CEF using object.observe which has been depracated in the latest chrome.

The error occurring is:
```inspector.js:10744 Uncaught TypeError: Object.observe is not a function```

I believe updating CEF should resolve this issue.  As a workaround, attaching an older version of the Chromium web browser will work for now.

**Comment by JoshEngebretson** [comment]
Updating to Chrome 51, could take some elbow grease

**Comment by JoshEngebretson** [comment]
Closed via #862
