### ISSUE TITLE
Android support on all platforms

### ISSUE THREAD

**Issue by JimMarlowe** [AtomicGameEngine/AtomicGameEngine#844]
A proposal for enabling full android support on Win, OSX, Linux.

All platforms can produce debug and release apks. (#31)
If devices are connected, attempt installation, with later versions of Android things get complicated.
The paths are available on all platforms, some platforms can use system installed programs and paths. (#81)
Support direct typing into the path fields (#536)
All the paths and settings will be put into project BuildSettings.json file. (#818)
The icon is a button with current icon, and the filename next to it. Pressing the icon button brings up a finder to seek a new icon. (#754)

The [x] Release Path checkbox signifies that the user wants to build a release apk. It is unselected by default. It can be made insensitive until a release path has a value. 
Make the "Release Path" be the place where the user stores the ant.properties which contains the keystore and password info to make a release apk.
If the user selects Release and does not provide needed keystore information, a debug apk is created.

Build Settings Android layout

App Name :            [_____________]
App Package :        [_____________]
Company Name :   [_____________]
Product Name :      [_____________]

Android SDK Path :
[____________________] [Choose]

Android API Level:
[____________________] [Refresh]

Ant Path :
[____________________] [Choose]

Java JDK Path :
[____________________] [Choose]

[x] Release Path :
[____________________] [Choose]

[____________________] [Icon]  

Would you like to know more?

**Comment by JoshEngebretson** [comment]
This sounds great, I especially like the linking to existing issues that will be closed in  the process :)
