### ISSUE TITLE
Linux display issues with complex 3d models, Shadows

### ISSUE THREAD

**Issue by JimMarlowe** [AtomicGameEngine/AtomicGameEngine#863]
The linux Mesa display drivers has problems with complex 3d models and shadows. The toontown is really bad with the procsky, it'll be fine, then a visual mess, the model vertexes go bonkers, then it's fine again depending on the position of the sun. Urho3d has the same problem. When I run a Urho3D program on linux I have to add "-gl2 -noshadows" to the command line to make the display behave.

**Comment by JimMarlowe** [comment]
Possible resolutions:
-Have Mesa fix the display driver ( its been broke for year+)
-Do nothing but document the issue, the user can put these forceGL2 and shadow settings in their  <project>/Settings/Engine.json file, and this stops the problems in the player.
-Add a block of code in the programs main.js, like there is (sometimes) for iOS and android, with their shadow issues.
-Change the engine defaults for these two settings only for linux.

**Comment by JimMarlowe** [comment]
The last directive I know of from @JoshEngebretson on gitter was, "I would opt for detecting this driver and forcing shadows off/GL2 in this case with console log".
I can get the Open GL library information once the graphics engine starts, this includes the version  of the (suspected faulty) Mesa library. This can get us a number that we can compare against to see if the library is good or bad. Unfortunately, you cant set forceGL2 once the graphics engine is initialized, and you need it initialized in order to get the OGL information. The shadows, which are also part of this problem, can be turned on/off at any time. 

[Thu Jun 16 12:05:08 2016] INFO: GL Version: 3.3 (Core Profile) Mesa 10.1.3
[Thu Jun 16 12:05:08 2016] INFO: GL Renderer: Gallium 0.4 on AMD PALM
[Thu Jun 16 12:05:08 2016] INFO: GL Vendor: X.Org
[Thu Jun 16 12:05:08 2016] INFO: Driver type `Mesa` detected.
[Thu Jun 16 12:05:08 2016] INFO: Driver version 10.1.3 detected, the combined signature=101003
[Thu Jun 16 12:05:08 2016] INFO: GetForceGL2() is currently 0, setting default to 1
[Thu Jun 16 12:05:08 2016] ERROR: OpenGL 2 can only be forced before setting the initial screen mode

**Comment by JoshEngebretson** [comment]
Closed via #912
