### ISSUE TITLE
Remove dependency on ATL

### ISSUE THREAD

**Issue by CTrauma** [AtomicGameEngine/AtomicGameEngine#868]
I've been working on getting a headless build working on Windows using a clean Windows10 VM and then installing git, cmake, and vcbuildtools with Chocolatey as a way of having a relatively lightweight way to build in Windows.

The build fails because atlbase.h is included in AtomicGameEngine/Source/ThirdParty/nativefiledialog/nfd_win.cpp. Which use to be in the PSDK then removed, and then use to be in the DDK then removed and now it isn't in the vcbuildtools or VS Express either.

So after spending way more time than I would like to admit trying to find a clean way to pull the 1mb of files out of a 650mb iso of the old DDK from microsoft downloads I got frustrated and commented it out to see what the 'actual' dependencies were... and there aren't any, the file is just dependency rot.

I can either submit a PR back to the original project, which already has a healthy list of forgotten PRs or submit a PR to the ThirdParty sources here.

I think removing it is worth doing so there can be a lightweight build alternative for folks who don't need the full visual studio space hog install, and also makes it easy to automate the creation of a build environment which might help on-boarding with people new to building.

Thoughts..?

**Comment by JoshEngebretson** [comment]
Great find, just to be clear we just need to remove the reference to the file and voila?  If so, absolutely, it would still be a good idea to add an 

```
//ATOMIC: Removed reference to ATL
```

in the file, so if we do end up pulling from native file dialog, we can remember to remove it again :)

Thanks!

**Comment by CTrauma** [comment]
Yes I just commented it out in my tests which I can leave in the source with your comment above.

Removing the dependency on ATL is a huge win, it is a complete hassle because as I understand it ATL is proprietary and is only distributed with certain versions of Visual Studio, you can find it in older versions of the WDK but they don't make it easy.

Should have a soup to nuts example of building AtomicEditor on a fresh windows system in just a few lines using chocolatey and the Visual C++ Build Tools 2015 https://blogs.msdn.microsoft.com/vcblog/2016/03/31/announcing-the-official-release-of-the-visual-c-build-tools-2015/. If all goes well maybe I can put together a noobs script to automate the whole thing for non-devs who want to have cutting edge builds.
