### ISSUE TITLE
NPOT textures not working on WebGL

### ISSUE THREAD

**Issue by Anheurystics** [AtomicGameEngine/AtomicGameEngine#883]
I tried running the BunnyMark example on the WebGL target, and I got these errors:
[Screenshot](http://imgur.com/aNrkw5H)

I know the error is something about passing the next largest POT size for glTexImage2D, but I don't know where to edit that in the source code.

**Comment by JoshEngebretson** [comment]
This should be addressed now as Bunnymark uses a sprite sheet: https://github.com/AtomicGameEngine/AtomicExamples/tree/master/BunnyMark/JavaScript/Resources/Sprites
