### ISSUE TITLE
[Linux] keyboard mapping issues in script editor

### ISSUE THREAD

**Issue by guzzard** [AtomicGameEngine/AtomicGameEngine#884]
When using the script editor some keyboard keys behave strange when running on a build post 13th of June with the new CEF (was able to get around the editor crash using 'export MALLOC_CHECK_=1' as suggested by @CTrauma).

L = up
K = left
J = home
H = end
G = page down
F = page up
X = insert
C = delete

This behavior does not happen when running a build pre 13th of June when the old version of CEF.

**Comment by JimMarlowe** [comment]
Yes, the newer CEF introduced some unexpected changes. The unintended consequences of this is some of the hot keys now work, at the expense of letters. I'll get it fixed.
