### ISSUE TITLE
Jakefile needs to build linux libAtomicPlayer.so

### ISSUE THREAD

**Issue by JimMarlowe** [AtomicGameEngine/AtomicGameEngine#889]
The same problem exists on linux as did windows with PR #312, it needs to build the  androidPlayerBinary otherwise an android apk can be build successfully, but crashes on an android device because the libs/armeabi-v7a/libAtomicPlayer.so is missing.

**Comment by JoshEngebretson** [comment]
I think this has been fixed, can you please verify?  Thanks!
