### ISSUE TITLE
[Linux] Monaco editor rendering corrupted

### ISSUE THREAD

**Issue by guzzard** [AtomicGameEngine/AtomicGameEngine#908]
![corrupted_rendering](https://cloud.githubusercontent.com/assets/9007314/16601509/2c350002-430d-11e6-95ee-e8a5f5a5ce0d.png)

![corrupted_rendering2](https://cloud.githubusercontent.com/assets/9007314/16602270/01019f52-4313-11e6-958b-0dabb9653042.png)

![corrupted](https://cloud.githubusercontent.com/assets/9007314/16602725/bd5647ea-4316-11e6-9362-00cc2c99b32e.png)

Arial, 12pt:
![arial_12](https://cloud.githubusercontent.com/assets/9007314/16629895/162ea71c-43b8-11e6-963e-ed63886409c6.png)

Terminus, 14pt:
![terminus_14](https://cloud.githubusercontent.com/assets/9007314/16629901/1ca620ca-43b8-11e6-802b-3548b9c8be3b.png)

Vera, 12pt:
![vera_12](https://cloud.githubusercontent.com/assets/9007314/16629905/250609f6-43b8-11e6-8451-f1e58d139961.png)

Master built today. Code completion pop-up is unaffected regardless of font size and font family, however the rest of the text has some corruption in the rendering..

**Comment by shaddockh** [comment]
@guzzard  #909 just dropped into master which allows you to set "fontFamily" in prefs.  You may want to try to build latest master and change to a different font to see how that behaves.

**Comment by guzzard** [comment]
@shaddockh tested Arial, Terminus, FreeSans and Vera but all of them get corrupted unfortunately :-/

**Comment by guzzard** [comment]
Internal editor seems to work fine now on Linux. No crashing/exceptions, and the text renders correctly without artifacts.
