### ISSUE TITLE
Why does PIXEL_SIZE exist?

### ISSUE THREAD

**Issue by ejkoy** [AtomicGameEngine/AtomicGameEngine#942]
And what does PIXEL_SIZE mean? it's confusing me.

**Comment by JoshEngebretson** [comment]
Please use the QA system for questions: https://qa.atomicgameengine.com/

PIXEL_SIZE is a constant which scales sprites down for rendering, otherwise a 128x128 sprite would be 128 world units, which is rather enormous.  A similar constant multiplier is used in Unity
