### ISSUE TITLE
[Linux] Segmentation fault when running project

### ISSUE THREAD

**Issue by McFizh** [AtomicGameEngine/AtomicGameEngine#944]
When I create new 2D project and try to run it, the app shows for a second, then atomic crashes.

Platform: Fedora Core 24 , 64-bit
Kernel: 4.6.4-301.fc24.x86_64
Gcc: gcc version 6.1.1 20160621 (Red Hat 6.1.1-3) (GCC)

Git HEAD hash: e7255df3ce18bb17bf1f805a83aa2383873e6df7

dmesg output:
  traps: AtomicEditor[29909] general protection ip:d926dc sp:7f39155faa80 error:0 in AtomicEditor[400000+1bf9000]
  AtomicEditor[29908]: segfault at 28 ip 0000000000c21940 sp 00007ffc9a8a4f98 error 4 in AtomicEditor[400000+1bf9000]

(gdb) where
#0  0x0000000000d926dc in Atomic::VectorBuffer::Write(void const*, unsigned int) ()
#1  0x0000000000e76be2 in Atomic::IPCChannel::Receive() ()
#2  0x0000000000e77988 in Atomic::IPCBroker::ThreadFunction() ()
#3  0x0000000000cf4a0a in Atomic::ThreadFunctionStatic(void*) ()
#4  0x00007ffff7bc45ca in start_thread (arg=0x7fff65ad2700) at pthread_create.c:333
#5  0x00007ffff072cead in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

And this is what is printed on console:

[Fri Aug  5 17:34:34 2016] INFO: Opened log file /home/user/.local/share/AtomicEditor/Logs/AtomicEditor.log
[Fri Aug  5 17:34:34 2016] INFO: Created 3 worker threads
[Fri Aug  5 17:34:34 2016] INFO: Added resource path /home/user/AtomicGameEngine/Artifacts/AtomicEditor/Resources/CoreData/
[Fri Aug  5 17:34:34 2016] INFO: Added resource path /home/user/AtomicGameEngine/Artifacts/AtomicEditor/Resources/EditorData/
[Fri Aug  5 17:34:34 2016] DEBUG: Skipped autoload path 'Autoload' as it does not exist, check the documentation on how to set the 'resource prefix path'
[Fri Aug  5 17:34:34 2016] INFO: Set screen mode 3640x1023 windowed resizable
[Fri Aug  5 17:34:34 2016] INFO: Initialized input
[Fri Aug  5 17:34:34 2016] DEBUG: Loading resource Textures/Ramp.png
[Fri Aug  5 17:34:34 2016] DEBUG: Loading temporary resource Textures/Ramp.xml
[Fri Aug  5 17:34:34 2016] DEBUG: Loading resource Textures/Spot.png
[Fri Aug  5 17:34:34 2016] DEBUG: Loading temporary resource Textures/Spot.xml
[Fri Aug  5 17:34:34 2016] DEBUG: Loading resource Techniques/NoTexture.xml
[Fri Aug  5 17:34:34 2016] DEBUG: Loading resource RenderPaths/Forward.xml
[Fri Aug  5 17:34:34 2016] INFO: Initialized renderer
[Fri Aug  5 17:34:34 2016] INFO: Set audio mode 44100 Hz stereo interpolated
[Fri Aug  5 17:34:34 2016] INFO: Initialized engine
[Fri Aug  5 17:34:34 2016] ERROR: AtomicNETService binary not found:
[Fri Aug  5 17:34:34 2016] ERROR: Unable to start AtomicNETService
[0805/133434:ERROR:browser_main_loop.cc(231)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
[Fri Aug  5 17:34:35 2016] INFO: Initialized system user interface
[Fri Aug  5 17:34:35 2016] DEBUG: Loading resource UI/DefaultStyle.xml
[Fri Aug  5 17:34:35 2016] DEBUG: Loading resource Textures/UI.png
[Fri Aug  5 17:34:35 2016] DEBUG: Loading temporary resource Textures/UI.xml
[Fri Aug  5 17:34:35 2016] DEBUG: Loading resource Fonts/Anonymous Pro.ttf
[Fri Aug  5 17:34:35 2016] DEBUG: Font face Anonymous Pro (11pt) has 624 glyphs
[Fri Aug  5 17:34:35 2016] DEBUG: Started watching path /home/user/AtomicGameEngine/Artifacts/AtomicEditor/Resources/CoreData/
[Fri Aug  5 17:34:35 2016] DEBUG: Started watching path /home/user/AtomicGameEngine/Artifacts/AtomicEditor/Resources/EditorData/
[Fri Aug  5 17:34:35 2016] DEBUG: Window was resized to 1920x1016
[Fri Aug  5 17:34:35 2016] DEBUG: Window was moved to 1,1
[Fri Aug  5 17:34:35 2016] DEBUG: Reloading shaders
[Fri Aug  5 17:34:35 2016] DEBUG: Loading resource Shaders/GLSL/Basic.glsl
[Fri Aug  5 17:34:35 2016] DEBUG: Compiled vertex shader Basic(DIFFMAP VERTEXCOLOR)
[Fri Aug  5 17:34:35 2016] DEBUG: Compiled pixel shader Basic(DIFFMAP VERTEXCOLOR)
[Fri Aug  5 17:34:35 2016] DEBUG: Linked vertex shader Basic(DIFFMAP VERTEXCOLOR) and pixel shader Basic(DIFFMAP VERTEXCOLOR)
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
[Fri Aug  5 17:34:52 2016] DEBUG: Started watching path /home/user/AtomicProjects/MyGame2/Resources/
[Fri Aug  5 17:34:52 2016] INFO: Added resource path /home/user/AtomicProjects/MyGame2/Resources/
[Fri Aug  5 17:34:52 2016] ERROR: Could not open file /home/user/AtomicProjects/MyGame2/BuildSettings.json
[Fri Aug  5 17:34:52 2016] ERROR: Could not open file /home/user/AtomicProjects/MyGame2/UserPrefs.json
[Fri Aug  5 17:34:52 2016] DEBUG: Started watching path /home/user/AtomicProjects/MyGame2/Cache/
[Fri Aug  5 17:34:52 2016] INFO: Added resource path /home/user/AtomicProjects/MyGame2/Cache/
[Fri Aug  5 17:34:52 2016] INFO: CheckCacheFile:false - /home/user/AtomicProjects/MyGame2/Resources
[Fri Aug  5 17:34:52 2016] INFO: CheckCacheFile:false - /home/user/AtomicProjects/MyGame2/Resources/Scripts
[Fri Aug  5 17:34:52 2016] INFO: CheckCacheFile:false - /home/user/AtomicProjects/MyGame2/Resources/Sprites
[Fri Aug  5 17:34:52 2016] INFO: CheckCacheFile:false - /home/user/AtomicProjects/MyGame2/Resources/Components
[Fri Aug  5 17:34:52 2016] INFO: CheckCacheFile:false - /home/user/AtomicProjects/MyGame2/Resources/Scenes
[Fri Aug  5 17:34:52 2016] INFO: CheckCacheFile:false - /home/user/AtomicProjects/MyGame2/Resources/Scenes/Scene.scene
[Fri Aug  5 17:34:52 2016] INFO: ProjectBasedExtensionLoader: received a project loaded event for project at undefined
[Fri Aug  5 17:35:03 2016] INFO: Launching Broker /home/user/AtomicGameEngine/Artifacts/AtomicEditor/AtomicEditor --windowposx 0 --windowposy 0 --windowwidth 0 --windowheight 0 --resizable --fromEditorPlay --player --project "/home/user/AtomicProjects/MyGame2/"
[Fri Aug  5 17:35:03 2016] INFO: Adding ResourcePaths: CoreData;PlayerData;/home/user/AtomicProjects/MyGame2//;/home/user/AtomicProjects/MyGame2//Resources;/home/user/AtomicProjects/MyGame2/;/home/user/AtomicProjects/MyGame2/Cache
[Fri Aug  5 17:35:03 2016] INFO: Opened log file /home/user/.local/share/AtomicPlayer/Logs/AtomicPlayer.log
[Fri Aug  5 17:35:03 2016] INFO: Created 3 worker threads
[Fri Aug  5 17:35:03 2016] INFO: Added resource path /home/user/AtomicGameEngine/Artifacts/AtomicEditor/Resources/CoreData/
[Fri Aug  5 17:35:03 2016] INFO: Added resource path /home/user/AtomicGameEngine/Artifacts/AtomicEditor/Resources/PlayerData/
[Fri Aug  5 17:35:03 2016] INFO: Added resource path /home/user/AtomicProjects/MyGame2//
[Fri Aug  5 17:35:03 2016] INFO: Added resource path /home/user/AtomicProjects/MyGame2//Resources/
[Fri Aug  5 17:35:03 2016] INFO: Added resource path /home/user/AtomicProjects/MyGame2/
[Fri Aug  5 17:35:03 2016] INFO: Added resource path /home/user/AtomicProjects/MyGame2/Cache/
[Fri Aug  5 17:35:03 2016] DEBUG: Skipped autoload path 'Autoload' as it does not exist, check the documentation on how to set the 'resource prefix path'
[Fri Aug  5 17:35:03 2016] DEBUG: Loading resource Images/AtomicLogo32.png
[Fri Aug  5 17:35:03 2016] INFO: Set screen mode 3640x1023 windowed resizable
[Fri Aug  5 17:35:03 2016] INFO: Initialized input
[Fri Aug  5 17:35:03 2016] DEBUG: Loading resource Textures/Ramp.png
[Fri Aug  5 17:35:03 2016] DEBUG: Loading temporary resource Textures/Ramp.xml
[Fri Aug  5 17:35:03 2016] DEBUG: Loading resource Textures/Spot.png
[Fri Aug  5 17:35:03 2016] DEBUG: Loading temporary resource Textures/Spot.xml
[Fri Aug  5 17:35:03 2016] DEBUG: Loading resource Techniques/NoTexture.xml
[Fri Aug  5 17:35:03 2016] DEBUG: Loading resource RenderPaths/Forward.xml
[Fri Aug  5 17:35:03 2016] INFO: Initialized renderer
[Fri Aug  5 17:35:03 2016] INFO: Set audio mode 44100 Hz stereo interpolated
[Fri Aug  5 17:35:03 2016] INFO: Initialized engine
[Fri Aug  5 17:35:03 2016] INFO: Initialized system user interface
[Fri Aug  5 17:35:03 2016] DEBUG: Loading resource UI/DefaultStyle.xml
[Fri Aug  5 17:35:03 2016] DEBUG: Loading resource Textures/UI.png
[Fri Aug  5 17:35:03 2016] DEBUG: Loading temporary resource Textures/UI.xml
[Fri Aug  5 17:35:03 2016] DEBUG: Loading resource Fonts/Anonymous Pro.ttf
[Fri Aug  5 17:35:03 2016] DEBUG: Font face Anonymous Pro (11pt) has 624 glyphs
[0805/133503:ERROR:browser_main_loop.cc(231)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
[0805/133503:ERROR:socket_posix.cc(124)] bind() returned an error, errno=98: Address already in use
[0805/133503:ERROR:devtools_http_handler.cc(228)] Cannot start http server for devtools. Stop devtools.
[Fri Aug  5 17:35:03 2016] INFO: Starting IPCWorker --ipc-server=91
[Fri Aug  5 17:35:03 2016] INFO: Starting IPCWorker --ipc-client=92
[Fri Aug  5 17:35:03 2016] ERROR: Opened IPC transport fd = 92
[Fri Aug  5 17:35:03 2016] INFO: Loading scene from Scenes/Scene.scene
[Fri Aug  5 17:35:03 2016] DEBUG: Loading resource Components/Spinner.js
[Fri Aug  5 17:35:03 2016] DEBUG: Loading resource Sprites/star.png
[Fri Aug  5 17:35:03 2016] DEBUG: Window was moved to 1,1
[Fri Aug  5 17:35:03 2016] DEBUG: Window was resized to 1920x1043
[Fri Aug  5 17:35:03 2016] DEBUG: Reloading shaders
[Fri Aug  5 17:35:03 2016] DEBUG: Loading resource Shaders/GLSL/Atomic2D.glsl
[Fri Aug  5 17:35:03 2016] DEBUG: Compiled vertex shader Atomic2D()
[Fri Aug  5 17:35:03 2016] DEBUG: Compiled pixel shader Atomic2D()
[Fri Aug  5 17:35:03 2016] DEBUG: Linked vertex shader Atomic2D() and pixel shader Atomic2D()
Segmentation fault (core dumped)

**Comment by JoshEngebretson** [comment]
Is this a release build, it would be if build with ./Build_AtomicEditor.sh

There is an issue with release builds currently that doesn't manifest in Debug builds

**Comment by McFizh** [comment]
Yes, this is a release build

**Comment by JoshEngebretson** [comment]
Closed via #982
