### ISSUE TITLE
Update "Learn" site with updated keyboard shortcuts for the Scene editor

### ISSUE THREAD

**Issue by shaddockh** [AtomicGameEngine/AtomicGameEngine#946]
The Atomic Game Engine Learn site needs to have the list of keyboard shortcuts updated.

For instance:  SHIFT+Drag object will duplicate the object.

I'm sure there are other shortcuts that have been added recently as well.

**Comment by LaraEngebretson** [comment]
Moved keyboard shortcuts to the Wiki: [Scene Editor Hotkeys](https://github.com/AtomicGameEngine/AtomicGameEngine/wiki/Scene-Editor-Hotkeys)
