### ISSUE TITLE
Atomic .Net VS2015 preoject integration issues

### ISSUE THREAD

**Issue by mattbenic** [AtomicGameEngine/AtomicGameEngine#952]
To be able to keep our code in separate libraries, we're working in a custom .sln, with the Atomic-generated AtomicProject.csproj added to it. Working like this we've run into the following:

Adding a .cs file to the project from the AtomicEditor opens the AtomicProject.sln without updating the .csproj first. This means having to go back to the editor and manually regenerate the project first. 
- [x] Project should first regenerate when a file is added, before opening the solution
- [x] Ideally, only the .csproj should be regenerated, not the .sln, allowing devs to add projects to the solution which would be opened by the editor

Adding new files to the project in VS adds them to the AtomicNET directory tree, instead of to Resources. Combined with the above workflow issues adding through the editor this makes adding new files awkward.
- [ ] If the .csproj was kept in the atomic project root, files could rather be generated in /Resources/Scripts, with binaries still being generated to /Resources/AtomicNET if necessary

When generating the .csproj, source files are added using absolute, instead of relative paths. While this is not an issue if the .csproj is regenerated by every developer on the project, the need to do that means losing references added to the project.
- [x] Files should be added using relative paths.

When regenerating the .csproj, both dependencies and NuGet settings are lost. This means every time the AtomicProject.csproj is regenerated (whenever a file is added), all dependencies must be re-added.
- [x] Automatically adding all .dlls under /Resources or /Resources/Plugins to the AtomicProject.csproj's  dependencies when regenerating would be one way to solve the dependencies problem.
- [ ] I'm not sure if there's a way to regenerate a .csproj while preserving some aspects :/ We use a <name>.vcxproj.user in other solutions. This can be copied into the same directory as the <name>.vcproj and its content will be added to project settings when loading, adding the auto-generated aspects to this file instead of the .vcproj might be a solution.
- [ ] A minor one, but naming the .csproj and .dll according to the project itself would be nice, as well as setting the .csproj's default namespace to the name of the project.

**Comment by JoshEngebretson** [comment]
#962 addresses the checked boxes.  Not overwriting the solution and binary references being automatically setup for the generated project should be a pretty big win on usability.  

(**Important: We need to reuse the GUID of projects between regeneration of the csproj/sln as this will help maintain references.**  This isn't currently done, so let me know if this is a show stopper and I'll get right on it)

1) I'd really like to keep the generated C# project stuff out of the project root.  I am not sure if we can setup a default "this is where new source files go when creating them in VS for the auto-generated Atomic project assembly", could be tricky/fragile. 

2)   Are you using NuGet packages with "AtomicProject.dll" now?  If so, cool :)  Though, there really isn't a way in the project itself to define these for the generated project.  We probably need a configuration file for more advanced things like this... NuGet settings for other projects in the solution should be maintained.

3)  .vcxproj.user is currently generated if it does not exist to setup paths for the AtomicPlayer when running from VS, we could add more features and as it is XML probably not terrible to merge. 

4)  I think we'll probably rename AtomicProject.dll to the project's name, or have it be a setting (could have illegal project names), though for now some WIP stuff is keyed off of it.

**Comment by mattbenic** [comment]
Awesome! I'll move our stuff over to using the Atomic generated .sln when I'm done with the current block so I can give it a test. I'll be working on game specifics after this so that'll be perfect.

1) Is there any specific reason you don't want the .sln/.csproj in the root? Perhaps if the Resources directory was explicitly added to the project, adding new scripts under that would put them in the right place?

2) I'm using NuGet in our other lib projects, not in the AtomicProject.

3) Cool, we use it for the same reason on the c++ project (setting the debug parameters). Very useful. I'm not sure if there are any limitations on what can go into it, I _think_ it may be anything that can go in the main .csproj.

4) Yeah, I'm not sure what the limits are on naming. We routinely use "." in our project filenames, but I haven't tried anything more exotic.

**Comment by JoshEngebretson** [comment]
The sln/csproj are temporary files, I kind of want to contain them in the AtomicNET folder.   When creating a new file in VS, would still need to navigate to wherever in Resources for the location of the file.  

Maybe we can link the folders under Resources in the csproj for AtomicProject?  I wonder if a file created under such a link would be in the right spot on the file system, would have to keep the solution from autogenerating too when the file watcher noticed the new asset... there are a lot of catch 22's when using an IDE and an autogenerated IDE project/solution... simultaneously :)

**Comment by JoshEngebretson** [comment]
I am going to close this as it is pretty out of date and don't *think* these are issues anymore or are covered in other discussions/issues.
