### ISSUE TITLE
Improved TypeScript support for external editing.

### ISSUE THREAD

**Issue by Kobusvdwalt** [AtomicGameEngine/AtomicGameEngine#959]
If the user opens a project in a external editor like Atom, everything should be setup by default so that they don't have to create additional files manually. 

A easy solution would be to copy the Atom.d.ts file into the atomic project folder under a new TypeScript\Typings folder. So it would be MyGameExample\TypesScript\Atomic.d.ts
We should also setup a tsconfig.json file in the root of the project.

I would like to work on this.

**Comment by shaddockh** [comment]
Take a look at
https://github.com/AtomicGameEngine/AtomicGameEngine/blob/master/Script/AtomicEditor/hostExtensions/languageExtensions/TypscriptLanguageExtension.ts#L135

This is where the current TS Language Extension builds up an in-memory ```tsconfig.json``` and pulls the latest ```Atomic.d.ts``` from the editor bundle.  Adding a new menu item for ```Set up project for external editor``` or something to that effect could be built to generate the appropriate files in the current project and/or update the Atomic.d.ts when a new editor is released.
