### ISSUE TITLE
Scene Editor: Position Inspector doesn’t update transform while object selected, need to click off object and back on again to see changes reflected.

### ISSUE THREAD

**Issue by mattbenic** [AtomicGameEngine/AtomicGameEngine#96]

**Comment by JoshEngebretson** [comment]
Close via https://github.com/AtomicGameEngine/AtomicGameEngine/pull/188

![nodemove](https://cloud.githubusercontent.com/assets/376203/9236145/d80aa54e-40f7-11e5-84ab-c447f48111f4.gif)
