### ISSUE TITLE
Linux Package for Atomic Game Engine

### ISSUE THREAD

**Issue by JimMarlowe** [AtomicGameEngine/AtomicGameEngine#976]
Create a linux package of the Atomic Game engine.

Create Build/CIScripts/GenLinuxEditor.js to compile and assemble the package
Tthe target format for the package is .deb
The media is deployed into /usr/share and the binaries in /opt with links in /usr/bin

**Comment by JimMarlowe** [comment]
In an effort to fix the linux script to enable packaging, it allowed another problem to be worked on, that being the editor, when built from source, does not get help, examples or deployable data included.
This issue has been expanded to take these into account, and to do this on all platforms.

**Comment by JoshEngebretson** [comment]
Cool, help/examples should be optional as they are time/space consuming for local builds, and I have been working on the deployable data (including Android/iOS binaries)

I think the plan should be for Build/CIScripts to go away and focus on the Build/Scripts so they handle development, binary/redistribuable, and code signed builds of the editor.  

On master, Build_AtomicEditor.bat/.sh can build ```--with-android``` if specified and it will also handle ``--with-ios``` on mac shortly.  

Windows batch file programming is pretty problematic (and bash has its own quirks), if we're going to be adding many command line flags it probably makes sense to forward the entire command line to jake so we can parse the command line in JS, which has some decent ways to do it and then don't have to be maintained in two different spots.  

Another option is to use environment variables, at least in the short term to bootstrap the process and then work out the command line options, so checking whether ```ATOMIC_EDITOR_DOCS``` is defined or not... I would say the docs task could include examples

**Comment by JimMarlowe** [comment]
Aside from getting a linux package built, giving the user the ability to get the full Atomic programming experience when compiling from source is very desirable. How that is delivered is a good discussion to have. Given that the Build_AtomicEditor.xxx script is the user entry point, we should make it easy for them to pick what they may need. They should be able to discover the options without a search of the internet. Maybe print out the options when it starts executing (and a --help option), and show them what they will be getting, that way, if its not what they want, they can kill it and restart with the right options.
The deployables are another problem. For some, you need additional services to generate them that the user shouldn't need. Maybe use the CI to generate and package them when it does the validation builds, so the editor pick which ones it can support.

**Comment by JimMarlowe** [comment]
@CTrauma I've had some success with making a .deb with fpm. This command works:
`fpm  -s dir -t deb --name atomicgameengine  -v 1.0  --deb-no-default-config-files 
 --license MIT --vendor "THUNDERBEAST GAMES, LLC" 
 --description "The Atomic Game Engine is a cross-platform game editor" 
 --maintainer info@atomicgameengine.com --url http://atomicgameengine.com 
 --prefix /usr/local/games/AtomicGameEngine  
 -C <mydir>/AtomicGameEngine/Artifacts/AtomicEditor  . `
I picked /usr/local/games/ because I didn't have a /opt, good or bad. It needs some scripts to put in the link to /usr/bin after install, and another script to remove the link on uninstall, fpm allows for this.

**Comment by CTrauma** [comment]
I had something similar, would have to check to see when I'm in ssh distance to it, do we also want to install docs and examples? and do we want those as a sub-dir of AtomicGameEngine or do we want them in 'share' ?

**Comment by JimMarlowe** [comment]
If we do the monolithic install (basically the AtomicGameEngine/Artifacts/AtomicEditor directory), like what is done on windows, the docs and examples can now be filled in with build command line arguments (though Deployments are still an issue). If we split out anything (docs) to be more well behaved, then we'll also have to fix the editor plumbing to look for it in that place.
Apparently mint/ubuntu 17.x> no longer create /opt by default, which would have been the ideal spot. I don't know if it makes a difference if the monolith then goes into /usr/local or /usr/share, since the user will just run the .deb.

**Comment by JimMarlowe** [comment]
@CTrauma another mystery solved? - dependencies. According to https://www.debian.org/doc/manuals/maint-guide/dreq.en.html, the way they recommend to manually find exact build dependencies for /usr/bin/foo is `$ objdump -p /usr/bin/foo | grep NEEDED` and that seems to work for the AtomicEditor binary, and those items can be included in the fpm command. 
Still struggling with the preinstall and postinstall script locations, I think the package will have to be staged in /tmp and follow the debian directory format.

**Comment by JimMarlowe** [comment]
Using a gui called debreate, I've been able to create atomic.deb that I can move between my computers. Its not perfect, yet, I still haven’t figured out how to specify the dependencies correctly, and there is something wrong in the post install, so it doesn't show up in the menus immediately. I fixed a number of lintian errors and warnings.  Then, to turn the processing back into a script form.
![atomic-menuz](https://cloud.githubusercontent.com/assets/19511757/18959108/d582c460-8619-11e6-8bcf-5cf92b4cc14d.png)

**Comment by JimMarlowe** [comment]
It lives. The package that is generated has more lintian errors than the one I generated with debreate, but its not really clear who cares about lintian errors.  Packages will still load if there are lintian errors.  There are also some real problems identified (besides CEF) with static libs attached. 
The problem with the menu entry not showing up on some distros was a bug, which has a workaround, which I applied. 
It needs the dependencies added, and eventually, a dynamic version.

**Comment by CTrauma** [comment]
So did you use the project that debreate created as a baseline and just tweak it a bit?

**Comment by JimMarlowe** [comment]
I only used debreate to make an initial .deb, and look at it's staging area. Then I had to do the atomic version long hand, since debcreate isn’t script-able, but it was easier once I saw a successful creation process.

**Comment by JimMarlowe** [comment]
This task is completed, the dependencies are set, the deb name follows the atomic naming convention, and the deb appears to function properly to install/reinstall/remove.
To create a package, on linux, run ./Build_AtomicEditor.sh --package
