### ISSUE TITLE
getJSComponent fails if called immediately after createChildPrefab

### ISSUE THREAD

**Issue by bitonator** [AtomicGameEngine/AtomicGameEngine#991]
Creating this issue to submit a PR

I added a function called `callme` in `Coin.js` in the platformer example, and then added this in level.js

```
var node = self.scene.createChildPrefab("Coin", "Prefabs/Coin.prefab");
var script=node.getJSComponent("Coin");
script.callme();
```

This fails with a message that `callme` is undefined.

Looked through the code, looks like when a prefab is loaded `JSComponent::InitInstance` is called only in `JSComponent::Update`, so the instance isn't initialized immediately after `createChildPrefab`

**Comment by JoshEngebretson** [comment]
Thanks, closing
