### ISSUE TITLE
C# inline initialized Vector2 (and possibly other) inspector fields cause dll parsing to fail

### ISSUE THREAD

**Issue by mattbenic** [AtomicGameEngine/AtomicGameEngine#994]
If a Vector2 inspector field is added to a component, and inline initialized, an exception is raised inspecting the constructor of the component:

```
public class Foo : CSComponent
{
   [Inspector]
   private Vector2 myVecValue = Vector2.One;
}
```

Inline initializing basic types does not have this effect.

**Comment by JoshEngebretson** [comment]
This could be pretty darn tricky to handle... starting to see why C# runtime reflection has some limitations :)

For CS components, we *might* be able to instantiate and inspect whatever default values are... this is a prime reason to keep all logic out of constructors (ie. now allow them)

**Comment by JoshEngebretson** [comment]
This appears resolved, note that the inspector won't receive the default value as this would be require executing the IL or inspecting/resolving external assemblies:

![issue994](https://cloud.githubusercontent.com/assets/376203/20410529/586dbedc-acd2-11e6-8009-9bfd4094623b.PNG)
